Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-04, with the labels that each got.

#438 Polish Questionnaire UI
  questionnaire/src/App.scss
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/common/Formation.jsx
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/Remerciements.jsx
  questionnaire/src/components/pages/questionnaire/Autorisations.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
  questionnaire/src/components/pages/questionnaire/notes/Note.jsx
  questionnaire/src/components/pages/questionnaire/notes/NoteMoyenne.jsx
  questionnaire/src/components/pages/questionnaire/notes/NoteMoyenne.scss
  questionnaire/src/components/pages/questionnaire/notes/Notes.jsx
  questionnaire/src/components/pages/questionnaire/notes/note.scss
  questionnaire/src/components/pages/questionnaire/notes/stars.scss
Labels: master, ready

#441 Force star font to be loaded before first hover
  questionnaire/src/components/pages/questionnaire/notes/Stars.jsx
Labels: master, ready

#443 Allow EFK stack to be started locally
  docker-compose.override.yml
  misc/efk/elasticsearch/Dockerfile
  misc/efk/elasticsearch/app/elasticsearch.yml
  misc/efk/fluentbit/Dockerfile
  misc/efk/fluentbit/conf/fluent-bit.conf
  misc/efk/fluentbit/conf/parsers.conf
  misc/efk/fluentbit/conf/plugins.conf
  misc/efk/kibana/Dockerfile
  misc/efk/kibana/app/kibana.yml
Labels: ready

#447 Log response body for specific routes
  backend/src/http/middlewares.js
  backend/src/http/server.js
  backend/src/jobs/job-utils.js
Labels: ready

#449 Regroup all middlewares into a single file
  backend/src/http/middlewares.js
  backend/src/http/server.js
Labels: ready

#450 Configure docker-compose to be used in dev mode
  backoffice/Dockerfile
  docker-compose.override.yml
  misc/efk/fluentbit/conf/fluent-bit.conf
  misc/efk/fluentbit/conf/scripts.lua
Labels: ready

#444 Rename parameter to identify kairos login
  backend/src/http/routes/api/kairos.js
  backend/src/http/routes/backoffice/auth/login.js
  backend/test/integration/http/routes/kairos-test.js
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/account/service/loginService.js
  backoffice/src/components/login/LoginWithAccessToken.jsx
Labels: bug, master, ready

#445 Move /api/* routes into api folder
  backend/src/http/routes/api/backoffice/auth/account.js
  backend/src/http/routes/api/backoffice/auth/forgottenPassword.js
  backend/src/http/routes/api/backoffice/auth/login.js
  backend/src/http/routes/api/backoffice/export.js
  backend/src/http/routes/api/backoffice/financeur/financeur.js
  backend/src/http/routes/api/backoffice/moderateur/gestion-organismes.js
  backend/src/http/routes/api/backoffice/moderateur/moderation.js
  backend/src/http/routes/api/backoffice/moderateur/utils/convertOrganismeToDTO.js
  backend/src/http/routes/api/backoffice/moderateur/utils/moderationStats.js
  backend/src/http/routes/api/backoffice/organismes/consultation.js
  backend/src/http/routes/api/backoffice/organismes/organisme.js
  backend/src/http/routes/api/backoffice/stats.js
  backend/src/http/routes/api/stats.js
  backend/src/http/routes/api/swagger.js
  backend/src/http/routes/api/swagger.yml
  backend/src/http/server.js
  backend/test/integration/http/routes/v1/actions-test.js
  backend/test/integration/http/routes/v1/avis-test.js
  backend/test/integration/http/routes/v1/formations-test.js
  backend/test/integration/http/routes/v1/organismes-formateurs-test.js
  backend/test/integration/http/routes/v1/ping-test.js
  backend/test/integration/http/routes/v1/sessions-test.js
  backend/test/integration/http/routes/v1/stats-test.js
  backend/test/unit/regions-test.js
Labels: ready

#451 Fix nginx log rotation
  docker-compose.yml
  misc/nginx/Dockerfile
  misc/nginx/app/logrotate.d/logrotate.conf
  misc/nginx/app/nginx/nginx.conf
  misc/nginx/app/start.sh
Labels: ready

#453 Mise en production
  .travis.yml
  backend/src/http/middlewares.js
  backend/src/http/routes/api/backoffice/auth/account.js
  backend/src/http/routes/api/backoffice/auth/forgottenPassword.js
  backend/src/http/routes/api/backoffice/auth/login.js
  backend/src/http/routes/api/backoffice/export.js
  backend/src/http/routes/api/backoffice/financeur/financeur.js
  backend/src/http/routes/api/backoffice/moderateur/gestion-organismes.js
  backend/src/http/routes/api/backoffice/moderateur/moderation.js
  backend/src/http/routes/api/backoffice/moderateur/utils/convertOrganismeToDTO.js
  backend/src/http/routes/api/backoffice/moderateur/utils/moderationStats.js
  backend/src/http/routes/api/backoffice/organismes/consultation.js
  backend/src/http/routes/api/backoffice/organismes/organisme.js
  backend/src/http/routes/api/backoffice/stats.js
  backend/src/http/routes/api/stats.js
  backend/src/http/routes/api/swagger.js
  backend/src/http/routes/api/swagger.yml
  backend/src/http/routes/front/front.js
  backend/src/http/server.js
  backend/src/http/views/front/stats.ejs
  backend/src/jobs/job-utils.js
  backend/test/integration/http/routes/v1/actions-test.js
  backend/test/integration/http/routes/v1/avis-test.js
  backend/test/integration/http/routes/v1/formations-test.js
  backend/test/integration/http/routes/v1/organismes-formateurs-test.js
  backend/test/integration/http/routes/v1/ping-test.js
  backend/test/integration/http/routes/v1/sessions-test.js
  backend/test/integration/http/routes/v1/stats-test.js
  backend/test/unit/regions-test.js
  backoffice/Dockerfile
  docker-compose.override.yml
  docker-compose.test.yml
  docker-compose.yml
  misc/efk/elasticsearch/Dockerfile
  misc/efk/elasticsearch/app/elasticsearch.yml
  misc/efk/fluentbit/Dockerfile
  misc/efk/fluentbit/conf/fluent-bit.conf
  misc/efk/fluentbit/conf/parsers.conf
  misc/efk/fluentbit/conf/plugins.conf
  misc/efk/fluentbit/conf/scripts.lua
  misc/efk/kibana/Dockerfile
  misc/efk/kibana/app/kibana.yml
  misc/nginx/Dockerfile
  misc/nginx/app/logrotate.d/logrotate.conf
  misc/nginx/app/nginx/nginx.conf
  misc/nginx/app/start.sh
Labels: master, ready

#457 Use ip instead of Kibana domain name
  backend/src/http/routes/front/front.js
Labels: bug, master, ready

#456 Fix logrotation in nginx container
  misc/nginx/app/start.sh
Labels: bug, master, ready

#455 Prevent multiple questionnaire submit
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/remove-departements.js
  backend/src/jobs/data/migration/remove-duplicated-documents.js
  backend/src/jobs/data/migration/remove-regions.js
  questionnaire/src/components/pages/Questionnaire.jsx
Labels: bug, master, ready

#460 Update Kairos documentation
  API.md
  misc/specifications/kairos/api-kairos.svg
  misc/specifications/kairos/api-kairos.txt
Labels: master, ready

#462 Mise en production
  backend/src/jobs/archive/index.js
  docker-compose.override.yml
  docker-compose.yml
Labels: master, ready

#464 Update Stars component to support decimal numbers
  backend/src/http/routes/front/questionnaire.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/dataset/index.js
  backend/test/integration/http/routes/front/questionnaire-test.js
  backoffice/src/components/backoffice/common/deprecated/Stars.js
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Stagiaire.jsx
Labels: ready

#440 Compute score in decimals
  backend/src/http/routes/api/kairos.js
  backend/src/http/routes/api/v1/actions.js
  backend/src/http/routes/api/v1/avis.js
  backend/src/http/routes/api/v1/dto/convertToExposableAction.js
  backend/src/http/routes/api/v1/dto/convertToExposableFormation.js
  backend/src/http/routes/api/v1/dto/convertToExposableOrganismeFomateur.js
  backend/src/http/routes/api/v1/dto/convertToExposableSession.js
  backend/src/http/routes/api/v1/dto/createActionDTO.js
  backend/src/http/routes/api/v1/dto/createAvisDTO.js
  backend/src/http/routes/api/v1/dto/createFormationDTO.js
  backend/src/http/routes/api/v1/dto/createNoteDTO.js
  backend/src/http/routes/api/v1/dto/createOrganismeFomateurDTO.js
  backend/src/http/routes/api/v1/dto/createPaginationDTO.js
  backend/src/http/routes/api/v1/dto/createScoreDTO.js
  backend/src/http/routes/api/v1/dto/createSessionDTO.js
  backend/src/http/routes/api/v1/formations.js
  backend/src/http/routes/api/v1/organismes-formateurs.js
  backend/src/http/routes/api/v1/sessions.js
  backend/src/http/routes/api/v1/utils/validators.js
  backend/src/http/routes/front/questionnaire.js
  backend/src/jobs/$round.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/import/formations/generateActions.js
  backend/src/jobs/import/formations/generateFormations.js
  backend/src/jobs/import/formations/generateSessions.js
  backend/src/jobs/import/formations/roundNotes.js
  backend/src/jobs/import/organismes/computeOrganismesScore.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
  backend/test/integration/http/routes/front/questionnaire-test.js
  backend/test/integration/http/routes/v1/actions-test.js
  backend/test/integration/http/routes/v1/formations-test.js
  backend/test/integration/http/routes/v1/organismes-formateurs-test.js
  backend/test/integration/http/routes/v1/sessions-test.js
  backend/test/integration/jobs/import/formations/generateActions-test.js
  backend/test/integration/jobs/import/formations/generateFormations-test.js
  backend/test/integration/jobs/import/formations/generateSessions-test.js
  backend/test/integration/jobs/import/organismes/computeOrganismesScore-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
  backend/test/unit/utils/createAvisDTO-test.js
  backoffice/src/components/backoffice/common/deprecated/Stars.js
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Stagiaire.jsx
Labels: ready

#463 Split questionnaire
  backend/src/http/public/img/logo-pole-emploi-530.png
  questionnaire/public/images/logo-pole-emploi-530.png
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/common/Formation.jsx
  questionnaire/src/components/common/formation.scss
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/questionnaire.scss
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
  questionnaire/src/components/pages/questionnaire/notes/Note.jsx
  questionnaire/src/components/pages/questionnaire/notes/Notes.jsx
  questionnaire/src/components/pages/questionnaire/notes/Stars.jsx
  questionnaire/src/components/pages/questionnaire/notes/note.scss
  questionnaire/src/components/pages/questionnaire/notes/notes.scss
  questionnaire/src/components/pages/questionnaire/notes/stars.scss
  questionnaire/src/data.json
Labels: ready

#465 Store logrotate status
  misc/nginx/Dockerfile
  misc/nginx/app/logrotate.d/cron.daily/logrotate
  misc/nginx/app/logrotate.d/logrotate.conf
Labels: master, ready

#466 Allow job logs to sent to Kibana
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/common/components/logger.js
  backend/src/components.js
  backend/src/jobs/job-utils.js
  backend/test/helpers/test-logger.js
  docker-compose.override.yml
  docker-compose.test.yml
  misc/efk/fluentbit/conf/fluent-bit.conf
Labels: ready

#467 Fix reconciliation query ($eq)
  backend/src/jobs/import/formations/generateActions.js
  backend/src/jobs/import/formations/generateFormations.js
  backend/src/jobs/import/formations/generateSessions.js
  backend/test/integration/jobs/import/formations/generateActions-test.js
  backend/test/integration/jobs/import/formations/generateFormations-test.js
  backend/test/integration/jobs/import/formations/generateSessions-test.js
Labels: master, ready

#468 Fail organisme script when file cannot be found
  backend/src/jobs/import/organismes/generateOrganismesFromKairos.js
  backend/test/integration/jobs/import/organismes/generateOrganismesFromKairos-test.js
Labels: ready

#474 fix typo
  questionnaire/src/components/pages/Questionnaire.jsx
Labels: ready

#475 Rename logger name the same than ES index name
  backend/src/jobs/job-utils.js
  misc/efk/fluentbit/conf/fluent-bit.conf
Labels: ready

#461 Regroup all stats into a component
  backend/src/common/components/stats.js
  backend/src/components.js
  backend/src/http/routes/api/stats.js
  backend/src/http/routes/front/front.js
Labels: ready

#476 configure code region for export SMS
  backend/src/jobs/phoning/export-stagiaires.js
  backend/src/jobs/phoning/index.js
Labels: ready

#477 Add function to close log streams
  backend/src/common/components/logger.js
  backend/src/jobs/job-utils.js
Labels: master, ready

#479 Fix calls to logger
  backend/src/common/components/logger.js
Labels: bug, master, ready

#480 Fix GA variable
  questionnaire/public/index.html
Labels: bug, master, ready

#482 Fix google and hotjar on backoffice
  backoffice/public/index.html
  docker-compose.override.yml
  questionnaire/public/index.html
Labels: bug, master, ready

#484 questionnaire: design page 2
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/questionnaire.scss
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
Labels: ready

#487 export sms stats
  backend/src/jobs/phoning/export-stats.js
  backend/src/jobs/phoning/stats.js
Labels: ready

#486 Add migration to fix invalid reported state
  backend/src/jobs/data/migration/fix-invalid-reported.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/remove-duplicated-documents.js
Labels: ready

#485 Add script to generate CSV with avis non reconciliables
  backend/src/common/utils/stream-utils.js
  backend/src/jobs/stats/buildAvisNonReconciliableCSV.js
Labels: ready

#489 Mise en production
  backend/src/common/components/stats.js
  backend/src/common/utils/stream-utils.js
  backend/src/components.js
  backend/src/http/routes/api/stats.js
  backend/src/http/routes/front/front.js
  backend/src/jobs/data/migration/fix-invalid-reported.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/remove-duplicated-documents.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/phoning/export-stagiaires.js
  backend/src/jobs/phoning/export-stats.js
  backend/src/jobs/phoning/index.js
  backend/src/jobs/phoning/stats.js
  backend/src/jobs/stats/buildAvisNonReconciliableCSV.js
  misc/efk/fluentbit/conf/fluent-bit.conf
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/questionnaire.scss
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
Labels: ready

#490 Rename date filter when importing stagiaire
  backend/src/jobs/archive/archive.js
  backend/src/jobs/archive/index.js
  backend/src/jobs/import/trainee/index.js
  backend/src/jobs/import/trainee/traineeImporter.js
  backend/test/integration/jobs/import/trainee/traineeImporter-test.js
Labels: master, ready

#488 Suffix all route files with -routes
  backend/src/http/routes/api/backoffice/auth/account-routes.js
  backend/src/http/routes/api/backoffice/auth/forgottenPassword-routes.js
  backend/src/http/routes/api/backoffice/auth/login-routes.js
  backend/src/http/routes/api/backoffice/export-routes.js
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backend/src/http/routes/api/backoffice/moderateur/gestion-organismes-routes.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js
  backend/src/http/routes/api/backoffice/organismes/consultation-routes.js
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backend/src/http/routes/api/backoffice/stats-routes.js
  backend/src/http/routes/api/kairos-routes.js
  backend/src/http/routes/api/stats-routes.js
  backend/src/http/routes/api/swagger-routes.js
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/ping-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/routes/front/mailing-routes.js
  backend/src/http/routes/front/questionnaire-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/backoffice/consultation-routes-test.js
  backend/test/integration/http/routes/backoffice/financeur-routes-test.js
  backend/test/integration/http/routes/backoffice/forgottenPassword-routes-test.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-routes-test.js
  backend/test/integration/http/routes/backoffice/login-routes-test.js
  backend/test/integration/http/routes/backoffice/moderation-routes-test.js
  backend/test/integration/http/routes/backoffice/organisme-routes-test.js
  backend/test/integration/http/routes/front/mailing-routes-test.js
  backend/test/integration/http/routes/front/questionnaire-routes-test.js
  backend/test/integration/http/routes/kairos-routes-test.js
  backend/test/integration/http/routes/v1/actions-routes-test.js
  backend/test/integration/http/routes/v1/avis-routes-test.js
  backend/test/integration/http/routes/v1/formations-routes-test.js
  backend/test/integration/http/routes/v1/organismes-formateurs-routes-test.js
  backend/test/integration/http/routes/v1/ping-routes-test.js
  backend/test/integration/http/routes/v1/sessions-routes-test.js
  backend/test/integration/http/routes/v1/stats-routes-test.js
Labels: ready

#491 Add missing indexes
  backend/src/jobs/data/indexes/mongoIndexes.js
Labels: master, ready

#492 Handle invalid code postal from intercarif
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
Labels: ready

#481 Add components to create AB tests with Google Optimize
  docker-compose.override.yml
  questionnaire/Dockerfile
  questionnaire/public/index.html
  questionnaire/src/components/common/ABTest.jsx
  questionnaire/src/components/pages/Questionnaire.jsx
Labels: ready

#494 Fix organisme's email shown in backoffice
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.jsx
Labels: master, ready

#495 Close logger with a message
  backend/src/common/components/logger.js
Labels: bug, master, ready

#498 Questionnaire : fix some CSS
  questionnaire/src/components/pages/questionnaire.scss
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
  questionnaire/src/components/pages/questionnaire/notes/notes.scss
Labels: ready

#499 Design questionnaire
  backend/src/http/public/img/labonneformation.jpg
  backend/src/http/public/img/labonneformation.png
  questionnaire/src/components/pages/Remerciements.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/badwords.scss
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
Labels: ready

#500 Update questionnaire wording
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
Labels: master, ready

#496 Add reconciliation metadata (+stats scripts)
  backend/src/common/utils/stream-utils.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/export/exportAvisNonReconciliableCSV.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/import/formations/addReconciliationAvisMetadata.js
  backend/src/jobs/import/formations/index.js
  backend/src/jobs/kpi/computeAvisNonReconciliablesStats.js
  backend/src/jobs/kpi/computeFormationsCertifiantesStats.js
  backend/src/jobs/stats/kpi/utils/generate-fake-comments.js
  backend/test/integration/jobs/import/formations/addReconciliationAvisMetadata-test.js
Labels: ready

#497 Replace certifinfos filter with a region filter
  backend/config/regions.json
  backend/src/jobs/import/trainee/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/trainee/index.js
  backend/src/jobs/import/trainee/traineeImporter.js
  backend/test/helpers/data/stagiaires-pe-ara-conseil-regional.csv
  backend/test/helpers/data/stagiaires-pe-ara-non-certifiantes.csv
  backend/test/helpers/data/stagiaires-pe.csv
  backend/test/integration/jobs/import/trainee/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/trainee/traineeImporter-test.js
  backend/test/unit/regions-test.js
Labels: ready

#501 Remove migration script
  backend/src/jobs/data/migration/fix-invalid-reported.js
  backend/src/jobs/data/migration/index.js
Labels: ready
