Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-05, with the labels that each got.

#505 login page new design
  backoffice/src/components/backoffice/common/deprecated/DeprecatedHeader.jsx
  backoffice/src/components/backoffice/common/deprecated/header.css
  backoffice/src/components/login/ForgottenPassword.jsx
  backoffice/src/components/login/ForgottenPassword.scss
  backoffice/src/components/login/LoginForm.jsx
  backoffice/src/components/login/LoginForm.scss
  backoffice/src/styles/deprecated/anotea-deprecated.scss
Labels: ready

#503 fix emoji in inputs
  backend/src/http/routes/front/utils/userInput.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/removeEmoji.js
  backend/test/unit/userInput.js
Labels: ready

#506 Add script to update certifinfos in avis
  backend/src/common/utils/stream-utils.js
  backend/src/jobs/import/certifinfos/index.js
  backend/src/jobs/import/certifinfos/updateCertifinfos.js
  backend/test/helpers/data/certifinfos.csv
  backend/test/integration/jobs/import/certifinfos/updateCertifinfos-test.js
Labels: ready

#423 Anotea Widget
  docker-compose.yml
  misc/nginx/app/nginx/conf.d/locations.inc
  widget/.gitignore
  widget/Dockerfile
  widget/misc/nginx/default.conf
  widget/package-lock.json
  widget/package.json
  widget/public/favicon.ico
  widget/public/highlight/highlight.pack.js
  widget/public/highlight/solarized-light.css
  widget/public/index.html
  widget/public/logo.svg
  widget/public/manifest.json
  widget/public/style.css
  widget/src/App.jsx
  widget/src/App.test.js
  widget/src/index.js
  widget/src/lib/avisService.js
  widget/src/serviceWorker.js
  widget/src/utils/http-client.js
  widget/src/widget/AnoteaTinyWidget.jsx
  widget/src/widget/AnoteaWebComponent.jsx
  widget/src/widget/AnoteaWidget.jsx
  widget/src/widget/AvisAvecCommentaire.css.js
  widget/src/widget/AvisAvecCommentaire.jsx
  widget/src/widget/AvisAvecCommentaireLarge.css.js
  widget/src/widget/AvisAvecCommentaireLarge.jsx
  widget/src/widget/Stars.jsx
  widget/src/widget/Verified.js
  widget/src/widget/anoteaTinyWidget.css.js
  widget/src/widget/anoteaWidget.css.js
  widget/src/widget/fontawesome.css.js
  widget/src/widget/stars.css.js
Labels: ready

#509 Widget quick fix (font awesome)
  widget/public/index.html
  widget/src/widget/AnoteaTinyWidget.jsx
  widget/src/widget/AnoteaWebComponent.jsx
  widget/src/widget/AnoteaWidget.jsx
Labels: ready

#507 Add slack notifications during import/send stagiaires emails
  backend/package-lock.json
  backend/package.json
  backend/src/jobs/import/trainee/index.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
Labels: ready

#511 fix public url for stylesheet
  widget/public/index.html
Labels: ready

#512 Prepare migration to mailjet
  backend/config/custom-environment-variables.json
  docker-compose.override.yml
  misc/efk/fluentbit/conf/fluent-bit.conf
Labels: ready

#510 Send Slack notification when sending email to organimes
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/src/jobs/job-utils.js
  backend/src/jobs/mailing/organismes/account/AccountMailer.js
  backend/src/jobs/mailing/organismes/account/index.js
  backend/src/jobs/mailing/organismes/notifications/NotificationMailer.js
  backend/src/jobs/mailing/organismes/notifications/index.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
  backend/test/integration/jobs/mailing/organismes/account/AccountMailer-test.js
  backend/test/integration/jobs/mailing/organismes/account/actions/ResendAction-test.js
  backend/test/integration/jobs/mailing/organismes/account/actions/SendAction-test.js
  backend/test/integration/jobs/mailing/organismes/notifications/NotificationMailer-test.js
Labels: ready

#513 Widget : hotjar integration
  widget/public/index.html
  widget/src/widget/AvisAvecCommentaire.jsx
  widget/src/widget/AvisAvecCommentaireLarge.jsx
  widget/src/widget/ContactStagiaire.jsx
  widget/src/widget/contactStagiaire.css.js
Labels: ready

#514 Widget GA tracker
  widget/Dockerfile
  widget/src/widget/AvisAvecCommentaire.jsx
  widget/src/widget/AvisAvecCommentaireLarge.jsx
  widget/src/widget/GATracker.jsx
Labels: ready

#515 wording Moyens -> Matériels
  backoffice/src/components/backoffice/common/deprecated/AdviceRates.js
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Notes.jsx
  backoffice/src/components/backoffice/organisation/sessionStats.js
  widget/src/widget/AnoteaWidget.jsx
Labels: ready

#517 Widget : Microsoft Edge + IE11 support
  widget/Dockerfile
  widget/package.json
  widget/src/App.jsx
  widget/src/widget/AnoteaTinyWidget.jsx
  widget/src/widget/AnoteaWidget.jsx
  widget/src/widget/GATracker.jsx
Labels: ready

#518 Add stats about formations and avis
  backend/src/common/components/stats.js
  backend/src/http/routes/api/stats-routes.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/stats.ejs
  backend/src/jobs/data/indexes/mongoIndexes.js
Labels: ready

#516 Rename formations dir into reconciliation
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/import/reconciliation/addReconciliationAvisMetadata.js
  backend/src/jobs/import/reconciliation/generateActions.js
  backend/src/jobs/import/reconciliation/generateFormations.js
  backend/src/jobs/import/reconciliation/generateSessions.js
  backend/src/jobs/import/reconciliation/index.js
  backend/test/integration/jobs/import/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/import/reconciliation/generateActions-test.js
  backend/test/integration/jobs/import/reconciliation/generateFormations-test.js
  backend/test/integration/jobs/import/reconciliation/generateSessions-test.js
Labels: ready

#519 Fix emoji migration script
  backend/src/jobs/data/migration/removeEmoji.js
Labels: ready

#520 microsoft edge fix + chrome one windows
  widget/package-lock.json
  widget/public/index.html
  widget/src/App.jsx
  widget/src/widget/AnoteaWidget.jsx
Labels: ready

#521 Widget : Microsoft Edge CSS
  widget/public/index.html
  widget/src/App.jsx
  widget/src/widget/AnoteaWidget.jsx
  widget/src/widget/AvisAvecCommentaire.css.js
  widget/src/widget/AvisAvecCommentaire.jsx
  widget/src/widget/AvisAvecCommentaireLarge.css.js
  widget/src/widget/anoteaTinyWidget.css.js
  widget/src/widget/anoteaWidget.css.js
Labels: ready

#523 Add missing polyfill
  backoffice/public/index.html
  questionnaire/public/index.html
Labels: bug, master, ready

#524 Move ARG in Dockerfile to reuse cache
  questionnaire/Dockerfile
  widget/Dockerfile
Labels: ready

#527 Remove useless avis fields during reconciliation
  backend/src/jobs/import/reconciliation/generateActions.js
  backend/src/jobs/import/reconciliation/generateFormations.js
  backend/src/jobs/import/reconciliation/generateSessions.js
  backend/test/integration/jobs/import/reconciliation/generateActions-test.js
  backend/test/integration/jobs/import/reconciliation/generateFormations-test.js
  backend/test/integration/jobs/import/reconciliation/generateSessions-test.js
Labels: bug, master, ready

#526 Activate GZIP compression
  backend/package-lock.json
  backend/package.json
  backend/src/http/server.js
Labels: ready

#528 change questionnaire wording
  questionnaire/src/components/pages/questionnaire/Autorisations.jsx
Labels: ready

#530 enable guadeloupe
  backend/config/regions.json
  backend/test/unit/regions-test.js
Labels: ready

#532 Split widget document between github and static html page
  README.md
  WIDGET.md
  backend/src/http/public/img/logo.svg
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/doc/widget.ejs
  widget/public/doc.html
  widget/public/js/anotea-widget.js
  widget/src/components/common/Footer.jsx
  widget/src/components/common/Verified.jsx
  widget/src/components/common/images/logo-anotea.png
  widget/src/components/common/images/logo-pole-emploi.png
Labels: ready

#531 Return results when import stagiaires is done (fix)
  backend/src/jobs/import/trainee/index.js
Labels: bug, master, ready

#534 missing logo
  backend/src/http/public/img/regions/logo-email/logo_8.png
Labels: ready

#535 Use iframe resizer to ensure widget's height
  WIDGET.md
  backend/src/http/views/front/doc/widget.ejs
  widget/package-lock.json
  widget/package.json
  widget/public/js/anotea-widget.js
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/ListeWidget.scss
  widget/src/components/common/Propulsed.jsx
  widget/src/components/common/Propulsed.scss
  widget/src/index.js
Labels: ready

#539 Kairos organismes stats
  backend/src/common/components/stats.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/stats.ejs
Labels: ready

#537 Update app ports and fix widget port
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/doc/widget.ejs
  questionnaire/package.json
  widget/package.json
  widget/public/js/anotea-widget.js
Labels: ready

#540 Remove data fix
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/removeEmoji.js
Labels: ready

#536 Mise en production
  WIDGET.md
  backend/src/common/components/stats.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/doc/widget.ejs
  backend/src/http/views/front/stats.ejs
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/removeEmoji.js
  questionnaire/package.json
  widget/package-lock.json
  widget/package.json
  widget/public/js/anotea-widget.js
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/ListeWidget.scss
  widget/src/components/common/Propulsed.jsx
  widget/src/components/common/Propulsed.scss
  widget/src/index.js
Labels: ready

#541 Remove contact stagiaires and polish doc
  WIDGET.md
  backend/src/http/views/front/doc/widget.ejs
Labels: bug, master, ready

#543 Fix widget pagination when requesting formation/action/session
  backend/src/http/views/front/doc/widget.ejs
  widget/src/components/services/formationService.js
Labels: bug, master, ready

#545 Fix origin parameter during login with access token
  backoffice/src/App.jsx
Labels: bug, master, ready

#548 Fix iframe resizer and add test page
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/doc/widget-tests.ejs
  backend/src/http/views/front/doc/widget.ejs
  widget/public/js/anotea-widget.js
Labels: bug, master, ready

#550 Move anotea-widget.js to be served has a static backend resource
  WIDGET.md
  backend/.gitignore
  backend/Dockerfile
  backend/package-lock.json
  backend/package.json
  backend/src/http/public/static/js/widget/anotea-widget.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/server.js
  backend/src/http/views/front/doc/widget-tests.ejs
  backend/src/http/views/front/doc/widget.ejs
  widget/package-lock.json
  widget/package.json
Labels: bug, master, ready

#551 Use a parameter to redirect widget when ANOTEA_ENV=dev
  WIDGET.md
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package.json
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/views/front/doc/widget-tests.ejs
  backend/src/http/views/front/doc/widget.ejs
  backend/tester.html
Labels: bug, master, ready

#542 Add script to activate eligibility per region
  backend/src/jobs/data/migration/activateEligibility.js
  backend/src/jobs/data/migration/index.js
Labels: ready

#553 Move notices into static folder to prevent collisions
  backend/src/http/public/static/notices/notice-11.pdf
  backend/src/http/public/static/notices/notice-17.pdf
  backend/src/http/public/static/notices/notice-2.pdf
  backoffice/src/components/backoffice/common/deprecated/DeprecatedHeader.jsx
  backoffice/src/components/backoffice/organisation/Notice.js
Labels: ready

#552 Reorder routes files
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/api/questionnaire/utils/analytics.js
  backend/src/http/routes/api/questionnaire/utils/badwords.js
  backend/src/http/routes/api/questionnaire/utils/badwords.txt
  backend/src/http/routes/api/questionnaire/utils/userInput.js
  backend/src/http/routes/front/front-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/routes/front/mailing-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/backoffice/consultation-routes-test.js
  backend/test/integration/http/routes/api/backoffice/financeur-routes-test.js
  backend/test/integration/http/routes/api/backoffice/forgottenPassword-routes-test.js
  backend/test/integration/http/routes/api/backoffice/gestion-organismes-routes-test.js
  backend/test/integration/http/routes/api/backoffice/login-routes-test.js
  backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
  backend/test/integration/http/routes/api/backoffice/organisme-routes-test.js
  backend/test/integration/http/routes/api/kairos-routes-test.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js
  backend/test/integration/http/routes/api/v1/ping-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/http/routes/api/v1/stats-routes-test.js
  backend/test/integration/http/routes/headers-test.js
  backend/test/unit/analytics-test.js
  backend/test/unit/badwords-test.js
  backend/test/unit/userInput.js
Labels: ready

#557 Ajout de l'onglet "rejetés" sur le BO financeur
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#559 change delay to hide popup on advice publish event
  backoffice/src/components/backoffice/common/message/LocalMessage.jsx
Labels: ready

#558 Show region logo when codeFinanceur=2
  backend/src/http/public/static/images/regions/logo-email/logo_12.png
  backend/src/http/public/static/images/regions/logo-email/logo_15.png
  backend/src/http/public/static/images/regions/logo-email/logo_5.png
  backend/src/http/public/static/images/regions/logo-email/logo_9.png
  questionnaire/public/images/regions/region-10.png
  questionnaire/public/images/regions/region-12.png
  questionnaire/public/images/regions/region-13.png
  questionnaire/public/images/regions/region-14.png
  questionnaire/public/images/regions/region-15.png
  questionnaire/public/images/regions/region-16.png
  questionnaire/public/images/regions/region-18.png
  questionnaire/public/images/regions/region-2.png
  questionnaire/public/images/regions/region-3.png
  questionnaire/public/images/regions/region-4.png
  questionnaire/public/images/regions/region-5.png
  questionnaire/public/images/regions/region-6.png
  questionnaire/public/images/regions/region-7.png
  questionnaire/public/images/regions/region-8.png
  questionnaire/public/images/regions/region-9.png
  questionnaire/src/components/common/Footer.jsx
Labels: ready

#544 enable haut de france
  backend/config/regions.json
  backend/src/http/public/img/regions/logo-questionnaire/carif-10.png
  backend/src/http/public/img/regions/logo-questionnaire/region-10.png
  backend/test/unit/regions-test.js
Labels: master, ready

#529 enable martinique
  backend/config/regions.json
  backend/src/http/public/img/regions/logo-email/logo_13.png
  backend/test/unit/regions-test.js
Labels: master, ready

#546 Reconciliation without aggregation
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/kairos-routes.js
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/dto/createActionDTO.js
  backend/src/http/routes/api/v1/dto/createFormationDTO.js
  backend/src/http/routes/api/v1/dto/createNoteDTO.js
  backend/src/http/routes/api/v1/dto/createOrganismeFomateurDTO.js
  backend/src/http/routes/api/v1/dto/createPaginationDTO.js
  backend/src/http/routes/api/v1/dto/createScoreDTO.js
  backend/src/http/routes/api/v1/dto/createSessionDTO.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/http/routes/api/v1/utils/dto.js
  backend/src/http/routes/api/v1/utils/roundNotes.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/import/reconciliation/addReconciliationAvisMetadata.js
  backend/src/jobs/import/reconciliation/generateActions.js
  backend/src/jobs/import/reconciliation/generateFormations.js
  backend/src/jobs/import/reconciliation/generateSessions.js
  backend/src/jobs/import/reconciliation/index.js
  backend/src/jobs/import/reconciliation/tasks/addReconciliationAvisMetadata.js
  backend/src/jobs/import/reconciliation/tasks/reconcile.js
  backend/src/jobs/import/reconciliation/tasks/removePreviousImports.js
  backend/src/jobs/import/reconciliation/tasks/utils/computeScore.js
  backend/src/jobs/import/reconciliation/tasks/utils/findAvisReconciliables.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileActions.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileFormation.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileSessions.js
  backend/src/jobs/job-utils.js
  backend/test/helpers/data/dataset.js
  backend/test/helpers/test-database.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/jobs/import/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileFormations-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileSessions-test.js
  backend/test/integration/jobs/import/reconciliation/removePreviousImports-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
  backoffice/src/components/backoffice/account/service/loginService.js
Labels: ready

#562 Fix logo position and size
  backend/src/http/public/img/regions/logo-email/logo_10.png
  questionnaire/src/components/pages/remerciements.scss
Labels: master, ready

#561 Remove stats routes
  backend/src/http/routes/api/stats-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/stats.ejs
  backend/test/integration/http/routes/api/v1/stats-routes-test.js
Labels: ready

#564 Mise en production
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/kairos-routes.js
  backend/src/http/routes/api/stats-routes.js
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/dto/createActionDTO.js
  backend/src/http/routes/api/v1/dto/createFormationDTO.js
  backend/src/http/routes/api/v1/dto/createNoteDTO.js
  backend/src/http/routes/api/v1/dto/createOrganismeFomateurDTO.js
  backend/src/http/routes/api/v1/dto/createPaginationDTO.js
  backend/src/http/routes/api/v1/dto/createScoreDTO.js
  backend/src/http/routes/api/v1/dto/createSessionDTO.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/http/routes/api/v1/utils/dto.js
  backend/src/http/routes/api/v1/utils/roundNotes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/stats.ejs
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/import/reconciliation/addReconciliationAvisMetadata.js
  backend/src/jobs/import/reconciliation/generateActions.js
  backend/src/jobs/import/reconciliation/generateFormations.js
  backend/src/jobs/import/reconciliation/generateSessions.js
  backend/src/jobs/import/reconciliation/index.js
  backend/src/jobs/import/reconciliation/tasks/addReconciliationAvisMetadata.js
  backend/src/jobs/import/reconciliation/tasks/reconcile.js
  backend/src/jobs/import/reconciliation/tasks/removePreviousImports.js
  backend/src/jobs/import/reconciliation/tasks/utils/computeScore.js
  backend/src/jobs/import/reconciliation/tasks/utils/findAvisReconciliables.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileActions.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileFormation.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileSessions.js
  backend/src/jobs/job-utils.js
  backend/test/helpers/data/dataset.js
  backend/test/helpers/test-database.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/http/routes/api/v1/stats-routes-test.js
  backend/test/integration/jobs/import/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileFormations-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileSessions-test.js
  backend/test/integration/jobs/import/reconciliation/removePreviousImports-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
  backoffice/src/components/backoffice/account/service/loginService.js
Labels: master, ready

#566 Split npm cache and build layer in Dockerfiles
  backoffice/Dockerfile
  questionnaire/Dockerfile
  widget/Dockerfile
Labels: ready

#567 Add popup example
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/doc/popup.ejs
  misc/dotfiles/anotea-idea-code-style.xml
Labels: master, ready

#568 Move region filters into an import section
  backend/config/regions.json
  backend/src/jobs/import/stagiaires/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/import/stagiaires/traineeImporter.js
  backend/src/jobs/import/stagiaires/utils.js
  backend/src/jobs/import/stagiaires/validateCsvFile.js
  backend/src/jobs/import/stagiaires/validateTrainee.js
  backend/test/integration/jobs/import/stagiaires/ileDeFranceCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/traineeImporter-test.js
  backend/test/integration/jobs/import/stagiaires/validateCsvFile-test.js
  backend/test/unit/regions-test.js
Labels: ready

#569 merging the stats branches
  backend/src/http/routes/api/public-stats.js
  backend/src/http/server.js
Labels: ready
