Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-09, with the labels that each got.

#817 financer BO : sort organisations by alpha order
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
Labels: ready

#816 script : export avis with unknown cedex
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/export/exportAvisCedexInconnu.js
Labels: ready

#824 Activation Centre-Val de Loire
  backend/config/regions.json
  backend/src/jobs/data/auth/createNewAccount.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/test/integration/http/routes/api/regions-routes-test.js
Labels: master, ready

#822 Prepare BO Financeur stats
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/avis/Avis.jsx
  backoffice/src/components/backoffice/common/avis/Avis.scss
  backoffice/src/components/backoffice/common/avis/Commentaire.jsx
  backoffice/src/components/backoffice/common/avis/Commentaire.scss
  backoffice/src/components/backoffice/common/avis/Edition.jsx
  backoffice/src/components/backoffice/common/avis/Formation.jsx
  backoffice/src/components/backoffice/common/avis/Formation.scss
  backoffice/src/components/backoffice/common/avis/Notes.jsx
  backoffice/src/components/backoffice/common/avis/Notes.scss
  backoffice/src/components/backoffice/common/avis/Reponse.jsx
  backoffice/src/components/backoffice/common/avis/Reponse.scss
  backoffice/src/components/backoffice/common/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/common/avis/Stagiaire.scss
  backoffice/src/components/backoffice/common/avis/Titre.jsx
  backoffice/src/components/backoffice/common/avis/Titre.scss
  backoffice/src/components/backoffice/common/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/common/library/Button.jsx
  backoffice/src/components/backoffice/financeur/Avis.jsx
  backoffice/src/components/backoffice/financeur/FinanceurRoutes.jsx
  backoffice/src/components/backoffice/financeur/avis/AvisPanel.jsx
  backoffice/src/components/backoffice/financeur/avis/AvisPanel.scss
  backoffice/src/components/backoffice/financeur/avis/Filter.jsx
  backoffice/src/components/backoffice/financeur/avis/FiltersResume.jsx
  backoffice/src/components/backoffice/financeur/avis/PeriodeFilter.jsx
  backoffice/src/components/backoffice/financeur/avis/PeriodeFilter.scss
  backoffice/src/components/backoffice/financeur/avis/Resume.jsx
  backoffice/src/components/backoffice/financeur/avis/SideMenu.jsx
  backoffice/src/components/backoffice/financeur/avis/Titre.jsx
  backoffice/src/components/backoffice/financeur/avis/financeurService.js
  backoffice/src/components/backoffice/financeur/avis/sideMenu.css
  backoffice/src/components/backoffice/financeur/stats/StatistiquesPanel.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/organisation/searchForm.js
Labels: ready

#829 Update courriel images
  backoffice/src/components/backoffice/moderateur/courrriels/images/OF_JoinAnotéa.png
  backoffice/src/components/backoffice/moderateur/courrriels/images/OF_NewMDP.png
  backoffice/src/components/backoffice/moderateur/courrriels/images/OF_NonLus.png
  backoffice/src/components/backoffice/moderateur/courrriels/images/OF_ReponseRejeté.png
  backoffice/src/components/backoffice/moderateur/courrriels/images/Stag_6mois.png
  backoffice/src/components/backoffice/moderateur/courrriels/images/Stag_AvisRejeté.png
  backoffice/src/components/backoffice/moderateur/courrriels/images/Stag_DonnerVotreAvis.png
Labels: ready

#825 Add migration script to remove invalid stagiaires (+since)
  backend/config/regions.json
  backend/src/common/components/regions.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/fixAvisCreated.js
  backend/src/jobs/data/migration/tasks/markOrphanComments.js
  backend/src/jobs/data/migration/tasks/removeInvalidStagiares.js
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/test/helpers/data/stagiaires-idf-old.csv
  backend/test/helpers/data/stagiaires-pe-old.csv
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/import/stagiaires/ileDeFranceCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
  backend/test/integration/jobs/import/stagiaires/poleEmploiCSVHandler-test.js
  backend/test/unit/regions-test.js
Labels: bug, master, ready

#831 Handle empty inseeCode in datalake export
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/test/helpers/data/stagiaires-pe-updated.csv
  backend/test/integration/jobs/import/stagiaires/refreshTrainee-test.js
Labels: master, ready

#832 Add migration script to unset deprecated reconciliation status
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropDeprecatedCollections.js
  backend/src/jobs/data/migration/tasks/removeInvalidStagiares.js
  backend/src/jobs/data/migration/tasks/unsetDeprecatedMeta.js
  backend/src/jobs/data/migration/tasks/unsetRefreshedStatus.js
Labels: master, ready

#834 Enhance optOut logs
  backend/src/jobs/data/optOut/tasks/optOutStagiaire.js
Labels: ready

#833 Update widget documentation
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/doc/widget-tests.ejs
  backend/src/http/views/front/doc/widget.ejs
  backend/src/jobs/data/migration/tasks/dropDeprecatedCollections.js
  backend/src/jobs/data/migration/tasks/removeInvalidComments.js
  backend/src/jobs/data/migration/tasks/unsetDeprecatedMeta.js
Labels: master, ready

#835 Bump project dependencies
  backend/package-lock.json
  backend/package.json
  backoffice/package-lock.json
  backoffice/package.json
  questionnaire/package-lock.json
  questionnaire/package.json
  stats/package-lock.json
  stats/package.json
  widget/package-lock.json
  widget/package.json
Labels: ready

#836 Remove unused npm dependencies
  backend/package.json
  backoffice/package-lock.json
  backoffice/package.json
  questionnaire/package-lock.json
  questionnaire/package.json
  stats/package-lock.json
  stats/package.json
  widget/package.json
Labels: ready

#839 Activation des emails aux organismes pour CVL
  backend/config/regions.json
Labels: master, ready

#842 enable moderation on reported advices
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationReponsesPanel.jsx
Labels: ready

#844 fix log for advice publish action
  backend/src/http/routes/api/backoffice/moderateur/moderation-avis-routes.js
Labels: ready

#840 update wording template stagiaire
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#847 fix: show advice as 'Archivé'
  backoffice/src/components/backoffice/common/avis/Stagiaire.jsx
Labels: ready

#848 Add exportCommentairesPublies script
  backend/src/jobs/export/exportCommentairesPublies.js
Labels: ready

#849 Update campaigne used for questionnaire 6 mois
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/tasks/Questionnaire6MoisMailer.js
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/test/integration/jobs/mailing/stagiaires/questionnaire6mois/Questionnaire6MoisMailer-test.js
Labels: master, ready

#850 fix signature
  backend/src/smtp/views/organisme_avis_signale_publie.ejs
  backend/src/smtp/views/organisme_avis_signale_rejete.ejs
Labels: ready

#843 send email when reject advice for alert
  backend/src/common/components/mailing/sendAlerteMail.js
  backend/src/components.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-avis-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/server.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_alerte.ejs
  backend/src/smtp/views/avis_alerte.txt
  backend/test/helpers/fake-mailer.js
  backend/test/integration/http/routes/api/backoffice/moderation-avis-routes-test.js
  backoffice/src/components/backoffice/common/avis/buttons/RejectButton.jsx
Labels: ready

#853 Prevent questionnaire6mois email to be resend to same stagiaire
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/tasks/Questionnaire6MoisMailer.js
  backend/test/integration/jobs/mailing/stagiaires/questionnaire6mois/Questionnaire6MoisMailer-test.js
Labels: master, ready

#851 Remove contact stagiaire
  backend/src/http/routes/api/contactStagiaires-routes.js
  backend/src/http/routes/api/exports-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/contactStagiaires-routes-test.js
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/common/ContactStagiaire.jsx
  widget/src/components/common/ContactStagiaire.scss
  widget/src/services/widgetService.js
Labels: ready

#854 Polish UI Form
  backoffice/src/components/backoffice/common/page/form/Date.scss
  backoffice/src/components/backoffice/common/page/form/Periode.jsx
  backoffice/src/components/backoffice/common/page/form/Periode.scss
  backoffice/src/components/backoffice/common/page/form/Select.scss
  backoffice/src/components/backoffice/financeur/pages/FinanceurPage.jsx
  backoffice/src/components/backoffice/misc/LibraryPage.jsx
Labels: ready

#855 Fix MonCompte rendering in BO Financeur
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/financeur/FinanceurHeaderItems.jsx
  backoffice/src/components/backoffice/financeur/FinanceurRoutes.jsx
  backoffice/src/components/backoffice/financeur/pages/FinanceurPage.jsx
  backoffice/src/components/backoffice/misc/account/mon-compte/MonComptePage.jsx
Labels: ready

#856 email : fix web view
  backend/src/http/routes/front/html-routes.js
Labels: ready

#858 Update widget components according to new UI
  WIDGET.md
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/common/Avis.jsx
  widget/src/components/common/Avis.scss
  widget/src/components/common/Header.jsx
  widget/src/components/common/Notes.jsx
  widget/src/components/common/Notes.scss
  widget/src/components/common/Tooltip.scss
  widget/src/components/common/Verified.jsx
  widget/src/components/common/Verified.scss
  widget/src/components/common/images/logo-pole-emploi.svg
  widget/src/components/common/options/Option.jsx
  widget/src/components/common/options/WidgetContext.jsx
  widget/src/styles/variables.scss
Labels: ready

#857 Fix email token tracking for organismes
  backend/src/http/routes/front/html-routes.js
  backend/test/integration/http/routes/front/http-routes-test.js
  backend/test/integration/http/routes/front/mailing-routes-test.js
Labels: bug, master, ready

#859 fix email template header for gmail
  backend/src/smtp/views/avis_alerte.ejs
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/avis_publie.ejs
  backend/src/smtp/views/common/header.css
  backend/src/smtp/views/common/header.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_avis_signale_publie.ejs
  backend/src/smtp/views/organisme_avis_signale_rejete.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#861 Add elapsedTime and response size in http logs
  backend/src/http/middlewares/middlewares.js
  backend/src/http/middlewares/utils/createResponseRecorder.js
Labels: master, ready

#860 Add Cache-Control header to force index.html to be reloaded
  backoffice/misc/nginx/default.conf
  backoffice/public/images/logo.png
  questionnaire/misc/nginx/default.conf
  stats/misc/nginx/default.conf
  widget/misc/nginx/default.conf
Labels: master, ready

#863 Send backoffice arrays with streams
  backend/src/http/routes/api/backoffice/moderateur/gestion-organismes-routes.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-avis-routes.js
Labels: ready

#862 Rework BO moderation components according to UI
  backoffice/package.json
  backoffice/src/App.jsx
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Button.jsx
  backoffice/src/components/backoffice/common/GridDisplayer.scss
  backoffice/src/components/backoffice/common/header/Header.jsx
  backoffice/src/components/backoffice/common/header/Header.scss
  backoffice/src/components/backoffice/common/header/logo-financeur.svg
  backoffice/src/components/backoffice/common/header/logo-moderateur.svg
  backoffice/src/components/backoffice/common/header/logo-organisme.svg
  backoffice/src/components/backoffice/common/page/Page.jsx
  backoffice/src/components/backoffice/common/page/Page.scss
  backoffice/src/components/backoffice/common/page/form/Form.jsx
  backoffice/src/components/backoffice/common/page/form/InputText.jsx
  backoffice/src/components/backoffice/common/page/form/InputText.scss
  backoffice/src/components/backoffice/common/page/panel/Panel.jsx
  backoffice/src/components/backoffice/common/page/panel/Panel.scss
  backoffice/src/components/backoffice/common/page/panel/filters/Filter.jsx
  backoffice/src/components/backoffice/common/page/panel/filters/Filter.scss
  backoffice/src/components/backoffice/common/page/panel/filters/Filters.jsx
  backoffice/src/components/backoffice/common/page/panel/filters/Filters.scss
  backoffice/src/components/backoffice/common/page/panel/filters/SearchInputFilter.jsx
  backoffice/src/components/backoffice/common/page/panel/filters/Toolbar.jsx
  backoffice/src/components/backoffice/common/page/panel/filters/Toolbar.scss
  backoffice/src/components/backoffice/common/page/tabs/Tabs.jsx
  backoffice/src/components/backoffice/financeur/pages/FinanceurPage.jsx
  backoffice/src/components/backoffice/financeur/pages/panels/AvisPanel.jsx
  backoffice/src/components/backoffice/financeur/pages/panels/StatsPanel.jsx
  backoffice/src/components/backoffice/misc/LibraryPage.jsx
  backoffice/src/components/backoffice/misc/account/mon-compte/MonComptePage.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/courriels/CourrielsPage.jsx
  backoffice/src/components/backoffice/moderateur/courriels/CourrielsPage.scss
  backoffice/src/components/backoffice/moderateur/courriels/CourrielsPanel.scss
  backoffice/src/components/backoffice/moderateur/gestion-organismes/GestionOrganismePage.jsx
  backoffice/src/components/backoffice/moderateur/gestion-organismes/GestionOrganismePage.scss
  backoffice/src/components/backoffice/moderateur/gestion-organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion-organismes/components/ExportButton.jsx
  backoffice/src/components/backoffice/moderateur/gestion-organismes/components/ExportButton.scss
  backoffice/src/components/backoffice/moderateur/gestion-organismes/gestionOrganismesService.js
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationAvisPage.jsx
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationAvisPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationReponsesPage.jsx
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationReponsesPanel.jsx
  backoffice/src/components/backoffice/organisation/DeprecatedPanel.jsx
  backoffice/src/components/backoffice/organisation/DeprecatedPanel.scss
  backoffice/src/components/backoffice/organisation/MonComptePanel.jsx
  backoffice/src/components/backoffice/organisation/MonComptePanel.scss
  backoffice/src/styles/variables.scss
Labels: ready

#830 Replace inseeCode by communes
  backend/src/common/components/communes.js
  backend/src/common/components/postalCodes.js
  backend/src/components.js
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/routes/front/utils/externalLinks.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropInseeCodeCollection.js
  backend/src/jobs/data/migration/tasks/removeInvalidComments.js
  backend/src/jobs/export/exportAvisCedexInconnu.js
  backend/src/jobs/import/communes/index.js
  backend/src/jobs/import/communes/tasks/importCommunes.js
  backend/src/jobs/import/insee/importers/cedex.js
  backend/src/jobs/import/insee/importers/postalCodes.js
  backend/src/jobs/import/insee/index.js
  backend/test/helpers/data/cedex.csv
  backend/test/helpers/data/communes.csv
  backend/test/helpers/data/laposte_hexasmal-echantillon.csv
  backend/test/helpers/data/laposte_hexasmal.csv
  backend/test/helpers/data/liste-des-cedex-echantillon.csv
  backend/test/helpers/data/liste-des-cedex.csv
  backend/test/integration/http/routes/front/utils/externalLinks-test.js
  backend/test/integration/jobs/import/communes/importCommunes-test.js
  backend/test/integration/jobs/import/insee/inseeImporter-test.js
Labels: ready

#865 fix web view for stagiaire email
  backend/src/http/routes/front/html-routes.js
Labels: bug, master, ready

#864 Add application name into http logs
  backend/src/http/middlewares/middlewares.js
  backend/src/http/middlewares/utils/createDatalakeExporter.js
  backend/src/http/middlewares/utils/findApplication.js
  backend/test/integration/http/routes/api/v1/datalake-exporter-test.js
Labels: master, ready

#867 Fix widget liste
  widget/src/components/ListeWidget.jsx
Labels: bug, master, ready

#841 Update votre_avis.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#870 Template mail
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#871 Fix codeFinanceur filter
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backend/test/integration/http/routes/api/backoffice/financeur-routes-test.js
  backend/test/integration/http/routes/api/backoffice/moderation-avis-routes-test.js
Labels: bug, master, ready

#868 Rework authentication pages with new UI
  backend/src/http/routes/api/backoffice/auth/forgottenPassword-routes.js
  backend/src/http/routes/api/backoffice/auth/login-routes.js
  backend/src/http/routes/api/backoffice/auth/password-routes.js
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backend/src/http/routes/api/kairos-routes.js
  backend/src/http/server.js
  backend/src/smtp/mailer.js
  backend/test/helpers/test-server.js
  backend/test/integration/http/routes/api/backoffice/login-routes-test.js
  backend/test/integration/http/routes/api/backoffice/organisme-routes-test.js
  backend/test/integration/http/routes/api/backoffice/password-routes-test.js
  backend/test/integration/http/routes/api/kairos-routes-test.js
  backoffice/src/App.jsx
  backoffice/src/App.scss
  backoffice/src/components/WithRouter.jsx
  backoffice/src/components/anonymous/ActivationComptePage.jsx
  backoffice/src/components/anonymous/AuthForm.jsx
  backoffice/src/components/anonymous/AuthForm.scss
  backoffice/src/components/anonymous/AuthRoutes.jsx
  backoffice/src/components/anonymous/LoginPage.jsx
  backoffice/src/components/anonymous/LoginPage.scss
  backoffice/src/components/anonymous/MotDePasseOubliePage.jsx
  backoffice/src/components/anonymous/ReinitialisationMotDePassePage.jsx
  backoffice/src/components/anonymous/loginService.js
  backoffice/src/components/anonymous/passwordService.js
  backoffice/src/components/backoffice/common/Loader.jsx
  backoffice/src/components/backoffice/common/deprecated/DeprecatedToolbar.js
  backoffice/src/components/backoffice/common/header/Header.jsx
  backoffice/src/components/backoffice/common/header/Header.scss
  backoffice/src/components/backoffice/common/header/logo-default.svg
  backoffice/src/components/backoffice/common/message/Alert.jsx
  backoffice/src/components/backoffice/common/message/Alert.scss
  backoffice/src/components/backoffice/common/message/GlobalMessage.jsx
  backoffice/src/components/backoffice/common/page/Page.jsx
  backoffice/src/components/backoffice/common/page/Page.scss
  backoffice/src/components/backoffice/common/page/form/InputText.jsx
  backoffice/src/components/backoffice/common/page/form/InputText.scss
  backoffice/src/components/backoffice/common/page/panel/Panel.jsx
  backoffice/src/components/backoffice/common/page/panel/Panel.scss
  backoffice/src/components/backoffice/financeur/financeurService.js
  backoffice/src/components/backoffice/financeur/pages/panels/AvisPanel.jsx
  backoffice/src/components/backoffice/financeur/pages/panels/StatsPanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion-organismes/GestionOrganismePage.jsx
  backoffice/src/components/backoffice/moderateur/gestion-organismes/gestionOrganismesService.js
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationAvisPage.jsx
  backoffice/src/components/backoffice/organisation/AccountActivation.jsx
  backoffice/src/components/backoffice/organisation/service/organismeService.js
  backoffice/src/components/login/ForgottenPassword.jsx
  backoffice/src/components/login/ForgottenPassword.scss
  backoffice/src/components/login/LoginForm.jsx
  backoffice/src/components/login/LoginForm.scss
  backoffice/src/components/login/LoginWithAccessToken.jsx
  backoffice/src/index.js
  backoffice/src/styles/variables.scss
  backoffice/src/utils/http-client.js
  backoffice/src/utils/route-utils.js
  backoffice/src/utils/session.js
  backoffice/src/utils/token.js
  backoffice/src/utils/validation.js
Labels: ready

#874 [BOOF-2] Regroup avis stuff under /backoffice/avis
  backend/src/common/utils/financeurs.js
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/http/routes/api/backoffice/financeur-routes.js
  backend/src/http/routes/api/backoffice/utils/avisCSVColumnsMapper.js
  backend/src/http/routes/api/backoffice/utils/computeAvisStats.js
  backend/src/http/routes/api/backoffice/utils/searchQueries.js
  backend/src/http/routes/api/backoffice/utils/validators.js
  backend/src/http/server.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropInseeCodeCollection.js
  backend/src/jobs/data/migration/tasks/removeInvalidProperties.js
  backend/test/helpers/test-server.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backend/test/integration/http/routes/api/backoffice/consultation-routes-test.js
  backend/test/integration/http/routes/api/backoffice/financeur-routes-test.js
  backend/test/integration/http/routes/api/backoffice/organisme-routes-test.js
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/avisService.js
  backoffice/src/components/backoffice/common/avis/Edition.jsx
  backoffice/src/components/backoffice/common/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/common/avis/Titre.jsx
  backoffice/src/components/backoffice/common/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/common/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/common/organisme/Organisme.jsx
  backoffice/src/components/backoffice/common/organisme/Organisme.scss
  backoffice/src/components/backoffice/common/organisme/buttons/EditButton.jsx
  backoffice/src/components/backoffice/common/organisme/buttons/Edition.jsx
  backoffice/src/components/backoffice/common/page/form/InputText.jsx
  backoffice/src/components/backoffice/financeur/financeurService.js
  backoffice/src/components/backoffice/financeur/pages/FinanceurPage.jsx
  backoffice/src/components/backoffice/financeur/pages/panels/AvisPanel.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/backoffice/moderateur/gestion-organismes/GestionOrganismePage.jsx
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationAvisPage.jsx
  backoffice/src/components/backoffice/moderateur/moderation-avis/ModerationReponsesPage.jsx
  backoffice/src/components/backoffice/moderateur/moderation-avis/moderationService.js
Labels: ready

#869 Show only 2 commentaires on liste and rework pagination
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/CarrouselWidget.scss
  widget/src/components/ListeWidget.jsx
  widget/src/components/ListeWidget.scss
  widget/src/components/common/Notes.jsx
  widget/src/components/common/Tooltip.scss
  widget/src/services/http-client.js
Labels: master, ready

#877 Add --codeFinanceur param to be able to create valid account
  backend/src/jobs/data/auth/createNewAccount.js
Labels: bug, master, ready

#866 Analyse de l'activité des OF sur le backoffice
  backend/src/common/components/moderation.js
  backend/src/http/routes/api/backoffice/auth/login-routes.js
  backend/src/http/routes/api/backoffice/organismes/consultation-routes.js
  backend/src/http/routes/api/exports-routes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/removeEvents.js
Labels: ready

#879 add carif logo for PDL
  backend/config/regions.json
  backend/test/unit/regions-test.js
  questionnaire/public/images/regions/carif-17.png
  questionnaire/src/components/pages/Remerciements.jsx
Labels: ready

#880 Update questionnaire6mois campaign
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/tasks/Questionnaire6MoisMailer.js
  backend/test/integration/jobs/mailing/stagiaires/questionnaire6mois/Questionnaire6MoisMailer-test.js
Labels: master, ready

#878 Split /accounts into /activation and /me routes
  backend/src/http/routes/api/backoffice/accounts-routes.js
  backend/src/http/routes/api/backoffice/activation-routes.js
  backend/src/http/routes/api/backoffice/me-routes.js
  backend/src/http/server.js
  backend/src/smtp/mailer.js
  backend/test/integration/http/routes/api/backoffice/activation-routes-test.js
  backend/test/integration/http/routes/api/backoffice/me-routes-test.js
  backoffice/src/components/anonymous/ActivationComptePage.jsx
  backoffice/src/components/anonymous/AuthRoutes.jsx
  backoffice/src/components/anonymous/LoginPage.jsx
  backoffice/src/components/anonymous/MotDePasseOubliePage.jsx
  backoffice/src/components/anonymous/ReinitialisationMotDePassePage.jsx
  backoffice/src/components/anonymous/activationService.js
  backoffice/src/components/anonymous/authService.js
  backoffice/src/components/anonymous/loginService.js
  backoffice/src/components/anonymous/passwordService.js
  backoffice/src/components/backoffice/meService.js
  backoffice/src/components/backoffice/misc/account/mon-compte/MonComptePage.jsx
  backoffice/src/components/backoffice/organisation/ChangePassword.jsx
Labels: ready
