Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-08, with the labels that each got.

#779 Add npmrc for all node projects
  backend/.npmrc
  backoffice/.npmrc
  questionnaire/.npmrc
  stats/.npmrc
  widget/.npmrc
Labels: ready

#780 template unsubscribe
  backend/src/http/views/front/mailing/unsubscribe.ejs
Labels: ready

#781 Web view for emails
  backend/src/common/components/mailing/sendReponseRejeteeNotification.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/mailing/legal/mentions.ejs
  backend/src/http/views/front/mailing/unsubscribe.ejs
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#783 wording email + hide web view link on browser
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/legal/stagiaires/mentions.ejs
  backend/src/smtp/views/legal/stagiaires/mentions.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#785 link to web view
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#770 departements filter
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/financeur/CodeFinancerSearchForm.js
  backoffice/src/components/backoffice/financeur/EntitySearchForm.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/financeur/OrganisationSearchForm.js
  backoffice/src/components/backoffice/financeur/filters/filter.jsx
  backoffice/src/components/backoffice/financeur/service/financeurService.js
  backoffice/src/components/backoffice/financeur/trainingSearchForm.js
Labels: ready

#787 Template email
  backend/src/http/public/static/images/regions/logo-email/logo_10.png
  backend/src/http/public/static/images/regions/logo-email/logo_11.png
  backend/src/http/public/static/images/regions/logo-email/logo_12.png
  backend/src/http/public/static/images/regions/logo-email/logo_13.png
  backend/src/http/public/static/images/regions/logo-email/logo_14.png
  backend/src/http/public/static/images/regions/logo-email/logo_15.png
  backend/src/http/public/static/images/regions/logo-email/logo_16.png
  backend/src/http/public/static/images/regions/logo-email/logo_17.png
  backend/src/http/public/static/images/regions/logo-email/logo_18.png
  backend/src/http/public/static/images/regions/logo-email/logo_2.png
  backend/src/http/public/static/images/regions/logo-email/logo_3.png
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/src/http/public/static/images/regions/logo-email/logo_5.png
  backend/src/http/public/static/images/regions/logo-email/logo_6.png
  backend/src/http/public/static/images/regions/logo-email/logo_7.png
  backend/src/http/public/static/images/regions/logo-email/logo_8.png
  backend/src/http/public/static/images/regions/logo-email/logo_9.png
  backend/src/http/views/errors/401.ejs
  backend/src/http/views/errors/403.ejs
  backend/src/http/views/errors/404.ejs
  backend/src/http/views/errors/error.ejs
  backend/src/http/views/front/mailing/unsubscribe.ejs
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/common/header.ejs
  backend/src/smtp/views/common/legal/financeurs/mentions.ejs
  backend/src/smtp/views/common/legal/financeurs/mentions.txt
  backend/src/smtp/views/common/legal/organismes/mentions.ejs
  backend/src/smtp/views/common/legal/organismes/mentions.txt
  backend/src/smtp/views/common/legal/stagiaires/mentions.ejs
  backend/src/smtp/views/common/legal/stagiaires/mentions.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#788 Fix template path
  backend/src/smtp/views/avis_injure.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisation_password.txt
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_avis_non_lus.txt
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
  backend/src/smtp/views/password_forgotten.txt
  backend/src/smtp/views/questionnaire_6mois.txt
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#789 Fix bo
  backend/src/smtp/views/common/header.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
Labels: ready

#790 quick fix
  backend/src/smtp/views/common/header.ejs
Labels: ready

#791 fix unsubscribe
  backend/src/http/views/front/mailing/unsubscribe.ejs
Labels: ready

#763 Refacto bo financeur
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/financeur/CodeFinancerSearchForm.js
  backoffice/src/components/backoffice/financeur/EntitySearchForm.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/financeur/OrganisationSearchForm.js
  backoffice/src/components/backoffice/financeur/filters/filter.jsx
  backoffice/src/components/backoffice/financeur/service/financeurService.js
  backoffice/src/components/backoffice/financeur/trainingSearchForm.js
Labels: ready

#786 refacto bo moderation's header to be used in bo financeur
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/FinanceurHeaderItems.jsx
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Header.scss
  backoffice/src/components/backoffice/common/Link.jsx
  backoffice/src/components/backoffice/common/ModerateurHeaderItems.jsx
  backoffice/src/components/backoffice/financeur/FinanceurRoutes.jsx
Labels: ready

#793 fix email organisme
  backend/src/smtp/mailer.js
Labels: bug, master

#794 improve badword detection
  backend/src/http/routes/api/questionnaire/utils/badwords.js
  backend/src/http/routes/api/questionnaire/utils/badwords.txt
  backend/test/unit/badwords-test.js
Labels: bug, master, ready

#796 add signature to emails
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/avis_injure.txt
  backend/src/smtp/views/common/signature.ejs
  backend/src/smtp/views/common/signature.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisation_password.txt
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_avis_non_lus.txt
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/password_forgotten.txt
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/questionnaire_6mois.txt
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#795 notification email suite signalement avis
  backend/src/common/components/mailing/sendSignalementAccepteNotification.js
  backend/src/common/components/mailing/sendSignalementRejeteNotification.js
  backend/src/components.js
  backend/src/http/routes/api/backoffice/moderateur/moderateur-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/organisation_password.txt
  backend/src/smtp/views/organisme_avis_signale_publie.ejs
  backend/src/smtp/views/organisme_avis_signale_publie.txt
  backend/src/smtp/views/organisme_avis_signale_rejete.ejs
  backend/src/smtp/views/organisme_avis_signale_rejete.txt
Labels: ready

#798 adding signature to email notification : avis signale
  backend/src/smtp/views/organisme_avis_signale_publie.ejs
  backend/src/smtp/views/organisme_avis_signale_publie.txt
  backend/src/smtp/views/organisme_avis_signale_rejete.ejs
  backend/src/smtp/views/organisme_avis_signale_rejete.txt
Labels: ready

#801 import cedex to insee table
  backend/src/common/components/postalCodes.js
  backend/src/components.js
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backend/src/http/routes/front/utils/externalLinks.js
  backend/src/jobs/import/insee/importers/cedex.js
  backend/src/jobs/import/insee/importers/postalCodes.js
  backend/src/jobs/import/insee/index.js
  backend/test/helpers/data/correspondance-code-insee-code-postal-echantillon.csv
  backend/test/helpers/data/liste-des-cedex-echantillon.csv
  backend/test/helpers/data/liste-des-cedex.csv
  backend/test/integration/http/routes/front/utils/externalLinks-test.js
  backend/test/integration/jobs/import/insee/inseeImporter-test.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/financeur/service/financeurService.js
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
  backoffice/src/components/backoffice/organisation/entitySearchForm.js
  backoffice/src/components/backoffice/organisation/searchForm.js
  backoffice/src/components/backoffice/organisation/service/organismeService.js
Labels: ready

#802 Fix email orga
  backend/src/smtp/mailer.js
Labels: bug, master, ready

#799 component for periodes filter
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/package-lock.json
  backoffice/package.json
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/financeur/PeriodeFilter.jsx
  backoffice/src/components/backoffice/financeur/PeriodeFilter.scss
  backoffice/src/components/backoffice/financeur/service/financeurService.js
Labels: ready

#807 add a scrollable year dropdown
  backoffice/src/components/backoffice/financeur/PeriodeFilter.jsx
Labels: ready

#809 use scheduledEndDate for endDate
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/financeur/PeriodeFilter.jsx
  backoffice/src/components/backoffice/financeur/service/financeurService.js
Labels: ready

#810 fix account template
  backend/src/smtp/views/organisation_password.ejs
Labels: bug, master, ready

#813 tag archived avis in BO financeur
  backend/src/common/utils/getStatus.js
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/financeur/Avis.jsx
Labels: ready

#811 BO : sort places
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#815 remove timeout
  backend/test/integration/http/routes/front/utils/externalLinks-test.js
Labels: ready

#812 Fix reponse in widget
  widget/src/components/common/Avis.jsx
Labels: master, ready

#819 translate datepicker in FR
  backoffice/src/components/backoffice/financeur/PeriodeFilter.jsx
Labels: ready

#820 Extract MonCompte Routes
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/account/MonCompteRoutes.jsx
  backoffice/src/components/backoffice/account/mon-compte/ChangePassword.jsx
  backoffice/src/components/backoffice/account/mon-compte/MonComptePanel.jsx
  backoffice/src/components/backoffice/account/mon-compte/MonComptePanel.scss
  backoffice/src/components/backoffice/account/mon-compte/MonCompteService.js
  backoffice/src/components/backoffice/account/mon-compte/changePassword.scss
  backoffice/src/components/backoffice/financeur/FinanceurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/login/ForgottenPassword.jsx
  backoffice/src/components/login/forgottenPasswordService.js
Labels: ready
