Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-10, with the labels that each got.

#882 Fix sanitize and Add moderation status in questionnaire
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/api/questionnaire/utils/userInput.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/unit/userInput-test.js
Labels: bug, ready

#883 updating email screenshots
  backoffice/src/components/backoffice/moderateur/courriels/CourrielsPage.jsx
  backoffice/src/components/backoffice/moderateur/courriels/images/OF_JoinAnotéa.png
  backoffice/src/components/backoffice/moderateur/courriels/images/OF_NewMDP.png
  backoffice/src/components/backoffice/moderateur/courriels/images/OF_NonLus.png
  backoffice/src/components/backoffice/moderateur/courriels/images/OF_ReponseRejeté.png
  backoffice/src/components/backoffice/moderateur/courriels/images/OF_SignaléPublié.png
  backoffice/src/components/backoffice/moderateur/courriels/images/OF_SignaléRejeté.png
  backoffice/src/components/backoffice/moderateur/courriels/images/Stag_AvisPublié.png
  backoffice/src/components/backoffice/moderateur/courriels/images/Stag_DonnerVotreAvis.png
Labels: ready

#885 fix export on BO financeur
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
Labels: bug, master, ready

#887 Rollback old export for organisme
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backoffice/src/components/backoffice/common/deprecated/DeprecatedToolbar.js
Labels: bug, master, ready

#886 fix typo on homepage
  backend/src/http/views/front/homepage.ejs
Labels: master, ready

#888 Fix empty qualification in export
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
Labels: master, ready

#890 remove email notification when publishing avis
  backend/src/common/components/mailing/sendAvisPublieMail.js
  backend/src/components.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-avis-routes.js
  backend/src/smtp/mailer.js
  backend/test/helpers/fake-mailer.js
Labels: bug, master, ready

#891 Pass configuration object to passwords component during init
  backend/src/common/components/password.js
  backend/src/common/components/passwords.js
  backend/src/components.js
  backend/src/http/routes/api/backoffice/activation-routes.js
  backend/src/http/routes/api/backoffice/login-routes.js
  backend/src/http/routes/api/backoffice/me-routes.js
  backend/src/http/routes/api/backoffice/password-routes.js
  backend/src/jobs/data/auth/createNewAccount.js
  backend/src/jobs/data/auth/hashPassword.js
  backend/src/jobs/data/reset/index.js
  backend/src/jobs/data/reset/tasks/resetPasswords.js
  backend/test/helpers/test-components.js
  backend/test/unit/password-test.js
Labels: ready

#892 Add pastille stats on OrganismePage
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/http/routes/api/backoffice/avis/avisQueryFactory.js
  backend/src/http/routes/api/backoffice/avis/searchQueryFactory.js
  backend/src/http/routes/api/backoffice/stats-routes.js
  backend/src/http/routes/api/backoffice/stats/computeAvisStats.js
  backend/src/http/routes/api/backoffice/stats/computeModerationStats.js
  backend/src/http/routes/api/backoffice/stats/computeStagiairesStats.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backend/test/integration/http/routes/api/backoffice/stats-routes-test.js
  backoffice/src/components/financeur/components/AvisPanel.jsx
  backoffice/src/components/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/moderateur/moderation-avis/ModerationAvisPage.jsx
  backoffice/src/components/moderateur/moderation-avis/ModerationReponsesPage.jsx
  backoffice/src/components/organisme/OrganismePage.jsx
  backoffice/src/components/organisme/components/AvisPanel.jsx
  backoffice/src/components/organisme/components/StagiairesStats.jsx
  backoffice/src/services/statsService.js
Labels: ready

#893 Add new badwords
  backend/src/http/routes/api/questionnaire/utils/badwords.txt
Labels: ready

#897 Fix reset email script
  backend/src/jobs/data/reset/tasks/resetEmails.js
Labels: ready

#896 Remove unused properties when importing stagiaire
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/removeStagiairesUnusedProperties.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/refreshTrainee.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#895 Inline moderation header
  backoffice/src/App.jsx
  backoffice/src/components/anonymous/ReinitialisationMotDePassePage.jsx
  backoffice/src/components/common/Dropdown.scss
  backoffice/src/components/common/Pastille.jsx
  backoffice/src/components/common/Pastille.scss
  backoffice/src/components/common/header/Header.scss
  backoffice/src/components/common/header/Link.jsx
  backoffice/src/components/common/page/panel/filters/Filter.jsx
  backoffice/src/components/common/page/panel/filters/Filter.scss
  backoffice/src/components/moderateur/ModerateurHeaderItems.jsx
Labels: ready

#899 Add lastStatusUpdate property when creating respone
  backend/src/common/components/consultation.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdatePropertyIntoReponse.js
  backend/src/jobs/data/migration/tasks/removeEvents.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backoffice/src/components/organisme/components/AvisPanel.jsx
Labels: ready

#898 Change compound key to ensure stagiare unicity
  backend/src/common/utils/financeurs.js
  backend/src/common/utils/object-utils.js
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/fixCodeFinanceurs.js
  backend/src/jobs/data/migration/tasks/removeDuplicatedStagiaires.js
  backend/src/jobs/data/migration/tasks/removeUselessMetaReconciliations.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/src/jobs/import/stagiaires/tasks/refreshTrainee.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/data/removeDuplicatedStagiaires-test.js
Labels: ready

#900 Remove unused npm dependencies
  backoffice/package-lock.json
  backoffice/package.json
  questionnaire/package-lock.json
  questionnaire/package.json
  stats/package.json
  widget/package-lock.json
  widget/package.json
Labels: ready

#901 Remove formacode property duplication
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/tasks/removeStagiairesUnusedProperties.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/jobs/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
Labels: ready

#903 remove questionnaire 6 mois preview + fix label
  backoffice/src/components/moderateur/courriels/CourrielsPage.jsx
  backoffice/src/components/moderateur/courriels/images/Stag_6mois.png
Labels: ready

#904 Remove unused features property in user
  backend/src/http/routes/api/backoffice/login-routes.js
  backend/src/jobs/data/auth/createNewAccount.js
  backend/src/jobs/data/auth/generateJwtTokenForModerateur.js
  backend/src/jobs/data/dataset/tasks/createAccounts.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/removeFeaturesPropertyInAccounts.js
Labels: ready

#902 Reverse NoteDetails order
  backoffice/src/components/common/page/panel/results/stats/NoteDetails.jsx
Labels: ready

#906 Fix widget pagination padding
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/CarrouselWidget.scss
Labels: bug, master, ready

#905 Move titleMasked under comment property
  backend/src/common/components/moderation.js
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/moveTitleMaskedProperty.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
  backoffice/src/components/common/avis/Titre.jsx
Labels: ready

#912 Update Diagram
  misc/doc/diagram/anotea-diagram.drawio
  misc/doc/diagram/anotea-diagram.svg
Labels: master, ready

#911 [MIGRATION-4] Add dnIndividuNational again
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#910 [MIGRATION-3] Add migration scripts tests
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdateIntoReponse.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdatePropertyIntoReponse.js
  backend/src/jobs/data/migration/tasks/addMissingModerationStatus.js
  backend/src/jobs/data/migration/tasks/moveEditedCommentProperty.js
  backend/src/jobs/data/migration/tasks/moveTitleMasked.js
  backend/src/jobs/data/migration/tasks/moveTrackingIntoStagiaires.js
  backend/src/jobs/data/migration/tasks/pushMetaResfreshedIntoHistory.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/data/migration/addLastStatusUpdateIntoReponse-test.js
  backend/test/integration/jobs/data/migration/addReadProperty-test.js
  backend/test/integration/jobs/data/migration/moveEditedComment-test.js
  backend/test/integration/jobs/data/migration/moveTitleMasked-test.js
  backend/test/integration/jobs/data/migration/moveTrackingIntoStagiaires-test.js
  backend/test/integration/jobs/data/migration/pushMetaResfreshedIntoHistory-test.js
  backend/test/integration/jobs/data/migration/removeDuplicatedStagiaires-test.js
  backend/test/integration/jobs/data/migration/removeUselessMetaReconciliations-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#909 [MIGRATION-2] Move clickLinks into stagiaire
  backend/src/http/routes/front/html-routes.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdateIntoReponse.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdatePropertyIntoReponse.js
  backend/src/jobs/data/migration/tasks/addMissingModerationStatus.js
  backend/src/jobs/data/migration/tasks/moveEditedCommentProperty.js
  backend/src/jobs/data/migration/tasks/moveTitleMasked.js
  backend/src/jobs/data/migration/tasks/moveTrackingIntoStagiaires.js
  backend/src/jobs/data/migration/tasks/pushMetaResfreshedIntoHistory.js
  backend/src/jobs/data/migration/tasks/removeUnusedProperties.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/data/migration/addLastStatusUpdateIntoReponse-test.js
  backend/test/integration/jobs/data/migration/addReadProperty-test.js
  backend/test/integration/jobs/data/migration/moveEditedComment-test.js
  backend/test/integration/jobs/data/migration/moveTitleMasked-test.js
  backend/test/integration/jobs/data/migration/moveTrackingIntoStagiaires-test.js
  backend/test/integration/jobs/data/migration/pushMetaResfreshedIntoHistory-test.js
  backend/test/integration/jobs/data/migration/removeDuplicatedStagiaires-test.js
  backend/test/integration/jobs/data/migration/removeUselessMetaReconciliations-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#907 [MIGRATION-1] Push editedComment into history
  backend/src/common/components/moderation.js
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/common/utils/object-utils.js
  backend/src/http/routes/front/html-routes.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdateIntoReponse.js
  backend/src/jobs/data/migration/tasks/addLastStatusUpdatePropertyIntoReponse.js
  backend/src/jobs/data/migration/tasks/addMissingModerationStatus.js
  backend/src/jobs/data/migration/tasks/moveEditedCommentProperty.js
  backend/src/jobs/data/migration/tasks/moveTitleMasked.js
  backend/src/jobs/data/migration/tasks/moveTrackingIntoStagiaires.js
  backend/src/jobs/data/migration/tasks/pushMetaResfreshedIntoHistory.js
  backend/src/jobs/data/migration/tasks/removeUnusedProperties.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/refreshTrainee.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/jobs/data/migration/addLastStatusUpdateIntoReponse-test.js
  backend/test/integration/jobs/data/migration/addReadProperty-test.js
  backend/test/integration/jobs/data/migration/moveEditedComment-test.js
  backend/test/integration/jobs/data/migration/moveTitleMasked-test.js
  backend/test/integration/jobs/data/migration/moveTrackingIntoStagiaires-test.js
  backend/test/integration/jobs/data/migration/pushMetaResfreshedIntoHistory-test.js
  backend/test/integration/jobs/data/migration/removeDuplicatedStagiaires-test.js
  backend/test/integration/jobs/data/migration/removeUselessMetaReconciliations-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
  backend/test/integration/jobs/import/stagiaires/refreshTrainee-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
  backoffice/src/components/common/avis/Avis.jsx
  backoffice/src/components/common/avis/Commentaire.jsx
  backoffice/src/components/common/avis/CommentaireEditor.jsx
Labels: ready

#908 Align header elements in widget list
  widget/src/components/ListeWidget.jsx
Labels: bug, master, ready

#913 BO tiny fixes and improvements
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/http/routes/api/backoffice/formations-routes.js
  backend/src/http/routes/api/backoffice/queries/avisCSVColumnsMapper.js
  backend/src/http/routes/api/backoffice/queries/searchQueryFactory.js
  backend/src/http/routes/api/backoffice/stats-routes.js
  backend/src/http/routes/api/public-stats-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/backoffice/formations-routes-test.js
  backoffice/src/App.jsx
  backoffice/src/components/common/Button.jsx
  backoffice/src/components/common/Button.scss
  backoffice/src/components/common/Pastille.jsx
  backoffice/src/components/common/Pastille.scss
  backoffice/src/components/common/avis/Avis.jsx
  backoffice/src/components/common/avis/Avis.scss
  backoffice/src/components/common/avis/Stagiaire.jsx
  backoffice/src/components/common/avis/buttons/MarkAsReadButton.jsx
  backoffice/src/components/common/avis/buttons/ReportButton.jsx
  backoffice/src/components/common/header/Header.jsx
  backoffice/src/components/common/header/Header.scss
  backoffice/src/components/common/header/logo-financeur.svg
  backoffice/src/components/common/header/logo-moderateur.svg
  backoffice/src/components/common/header/logo-organisme.svg
  backoffice/src/components/common/header/logo.svg
  backoffice/src/components/common/message/LocalMessage.jsx
  backoffice/src/components/common/message/LocalMessage.scss
  backoffice/src/components/common/organisme/buttons/Edition.jsx
  backoffice/src/components/common/page/panel/filters/Filter.jsx
  backoffice/src/components/financeur/FinanceurHeaderItems.jsx
  backoffice/src/components/financeur/FinanceurPage.jsx
  backoffice/src/components/financeur/components/QueryBadges.jsx
  backoffice/src/components/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/moderateur/moderation-avis/ModerationAvisPage.jsx
  backoffice/src/components/organisme/OrganismeHeaderItems.jsx
  backoffice/src/components/organisme/OrganismePage.jsx
  backoffice/src/components/organisme/components/StatsPanel.jsx
  backoffice/src/styles/global.scss
Labels: ready

#914 Rework avis search validation
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/http/routes/api/backoffice/profiles/financeur.js
  backend/src/http/routes/api/backoffice/profiles/getProfile.js
  backend/src/http/routes/api/backoffice/profiles/moderateur.js
  backend/src/http/routes/api/backoffice/profiles/organisme.js
  backend/src/http/routes/api/backoffice/queries/searchQueryFactory.js
  backend/src/http/routes/api/backoffice/stats-routes.js
  backend/src/http/routes/api/backoffice/utils/computeAvisStats.js
  backend/src/http/routes/api/backoffice/utils/computeStagiairesStats.js
  backend/src/http/routes/api/backoffice/utils/getAvisCSV.js
  backend/src/http/routes/api/v1/utils/validators.js
  backend/src/http/routes/validators-utils.js
  backend/test/helpers/test-server.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-financeur-test.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-moderateur-test.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-organisme-test.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backend/test/integration/http/routes/api/backoffice/stats-routes-test.js
Labels: ready

#915 Remove unused export scripts and routes
  backend/src/http/routes/api/exports-routes.js
  backend/src/jobs/export/exportCommentairesPublies.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
Labels: ready

#916 Remove Periode icon (new UI)
  backoffice/src/components/common/page/form/Periode.jsx
Labels: ready

#920 Rework dataset generator script
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/dataset/tasks/createStagiaires.js
  backend/src/jobs/data/dataset/tasks/emulateBackofficeActions.js
  backoffice/src/components/common/Pastille.jsx
  backoffice/src/components/financeur/FinanceurPage.jsx
  backoffice/src/components/organisme/OrganismePage.jsx
Labels: ready

#922 Bo Fixes
  backend/src/http/routes/api/backoffice/profiles/financeur.js
  backend/src/http/routes/api/backoffice/profiles/moderateur.js
  backend/src/http/routes/api/backoffice/utils/getAvisCSV.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-test.js
  backoffice/src/components/common/avis/CommentaireEditor.jsx
  backoffice/src/components/common/avis/Reponse.jsx
  backoffice/src/components/common/avis/buttons/PublishButton.jsx
  backoffice/src/components/common/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/common/page/panel/results/stats/NoteDetails.jsx
  backoffice/src/components/financeur/components/CommentairesStats.jsx
  backoffice/src/components/moderateur/moderation-avis/ModerationAvisPage.jsx
  backoffice/src/components/moderateur/moderation-avis/ModerationReponsesPage.jsx
Labels: ready

#927 Fix Header pastille in BO Modération
  backend/src/http/routes/api/backoffice/avis-routes.js
  backoffice/src/components/moderateur/ModerateurHeaderItems.jsx
Labels: master, ready

#928 Fix login when organisme logged with email
  backend/src/http/routes/api/backoffice/login-routes.js
  backend/src/jobs/mailing/organismes/account/actions/ResendAction.js
  backend/src/jobs/mailing/organismes/account/actions/SendAction.js
  backend/test/integration/http/routes/api/backoffice/login-routes-test.js
Labels: bug, master, ready

#929 Fix organisme change password feature
  backend/src/http/routes/api/backoffice/me-routes.js
  backend/test/integration/http/routes/api/backoffice/me-routes-test.js
Labels: bug, master, ready

#930 Add user into Sentry context
  backend/src/common/components/sentry.js
  backend/src/http/middlewares/middlewares.js
  backend/src/http/routes/api/v1/ping-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/v1/ping-routes-test.js
Labels: master, ready

#931 Fix commentaires stats
  backend/src/http/routes/api/backoffice/utils/computeAvisStats.js
  backend/test/integration/http/routes/api/backoffice/stats-routes-test.js
  backoffice/src/components/financeur/components/CommentairesStats.jsx
  backoffice/src/components/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/moderateur/moderation-avis/ModerationReponsesPage.jsx
Labels: bug, master, ready

#924 Add reconciliated status
  backoffice/src/components/common/Button.jsx
  backoffice/src/components/common/Button.scss
  backoffice/src/components/common/Tooltip.jsx
  backoffice/src/components/common/Tooltip.scss
  backoffice/src/components/common/avis/Avis.jsx
  backoffice/src/components/common/avis/Stagiaire.jsx
  backoffice/src/components/common/avis/Stagiaire.scss
  backoffice/src/components/financeur/FinanceurPage.jsx
  backoffice/src/components/financeur/components/FinanceurAvisPanel.jsx
  backoffice/src/components/financeur/components/FinanceurStatsPanel.jsx
  backoffice/src/components/organisme/OrganismePage.jsx
  backoffice/src/components/organisme/components/OrganismeAvisPanel.jsx
  backoffice/src/components/organisme/components/OrganismeStatsPanel.jsx
  backoffice/src/styles/global.scss
Labels: ready

#932 Add protection (shield) in moderation/consultation
  backend/src/common/components/consultation.js
  backend/src/common/components/moderation.js
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-moderateur-test.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-organisme-test.js
Labels: ready

#933 Update CourrielsPage.jsx
  backoffice/src/components/moderateur/courriels/CourrielsPage.jsx
  backoffice/src/components/moderateur/courriels/images/Stag_AvisRejetéAlerte.png
  backoffice/src/components/moderateur/courriels/images/Stag_AvisRejetéInjure.png
Labels: master, ready

#938 fix logo position and size
  backend/src/http/public/static/css/front/errors.css
  backend/src/http/views/errors/401.ejs
  backend/src/http/views/errors/403.ejs
  backend/src/http/views/errors/404.ejs
  backend/src/http/views/errors/error.ejs
Labels: bug, master, ready

#941 Add archived and reported into pie
  backend/src/http/routes/api/backoffice/utils/computeAvisStats.js
  backend/test/integration/http/routes/api/backoffice/stats-routes-test.js
  backoffice/src/components/common/page/panel/results/stats/Pie.jsx
  backoffice/src/components/financeur/components/CommentairesStats.jsx
  backoffice/src/components/financeur/components/CommentairesStats.scss
Labels: ready

#942 Fix filter stats on BO OF
  backoffice/src/components/organisme/components/OrganismeAvisPanel.jsx
Labels: ready

#944 fix stars display on backoffice OF
  backoffice/src/components/common/avis/Stars.jsx
Labels: ready

#945 Mise en production
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/renamePublishedStatuses.js
  backend/src/jobs/data/migration/tasks/unsetReportedQualification.js
  backoffice/src/components/common/avis/Stars.jsx
Labels: master

#949 fix notes seules
  backend/src/http/routes/api/backoffice/utils/computeAvisStats.js
  backend/src/http/routes/api/backoffice/utils/computeStagiairesStats.js
  backend/test/integration/http/routes/api/backoffice/stats-routes-test.js
Labels: bug, master, ready
