Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-06, with the labels that each got.

#571 Replace carif collection with region data
  backend/config/regions.json
  backend/src/components.js
  backend/src/http/public/static/images/regions/logo-email/logo_14.png
  backend/src/http/public/static/images/regions/logo-email/logo_16.png
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/jobs/data/dataset/createRegionalData.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/migration/activateEligibility.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/removeCarifCollection.js
  backend/src/jobs/import/stagiaires/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/phoning/export-stagiaires.js
  backend/src/jobs/phoning/index.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/backoffice/forgottenPassword-routes-test.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/import/stagiaires/traineeImporter-test.js
  backend/test/unit/regions-test.js
  questionnaire/public/images/regions/carif-12.png
  questionnaire/public/images/regions/carif-13.png
  questionnaire/public/images/regions/carif-14.png
  questionnaire/public/images/regions/carif-15.png
  questionnaire/public/images/regions/carif-16.png
  questionnaire/public/images/regions/carif-18.png
  questionnaire/public/images/regions/carif-2.png
  questionnaire/public/images/regions/carif-3.png
  questionnaire/public/images/regions/carif-4.png
  questionnaire/public/images/regions/carif-5.png
  questionnaire/public/images/regions/carif-6.png
  questionnaire/public/images/regions/carif-7.png
  questionnaire/public/images/regions/carif-8.png
  questionnaire/public/images/regions/carif-9.png
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/pages/Remerciements.jsx
Labels: ready

#573 domain mail stats CSV export
  backend/src/http/routes/api/stats-routes.js
  backend/src/jobs/stats/emails/domainMailStatsBuilder.js
  backend/src/jobs/stats/emails/emailStatsBuilder.js
  backend/src/jobs/stats/emails/index.js
Labels: ready

#570 Add a marker to all widget http calls
  widget/src/utils/http-client.js
Labels: master, ready

#574 Mise en production
  backend/config/regions.json
  backend/src/components.js
  backend/src/http/public/static/images/regions/logo-email/logo_14.png
  backend/src/http/public/static/images/regions/logo-email/logo_16.png
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/api/stats-routes.js
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/jobs/data/dataset/createRegionalData.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/migration/activateEligibility.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/removeCarifCollection.js
  backend/src/jobs/import/stagiaires/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/import/stagiaires/traineeImporter.js
  backend/src/jobs/import/stagiaires/utils.js
  backend/src/jobs/import/stagiaires/validateCsvFile.js
  backend/src/jobs/import/stagiaires/validateTrainee.js
  backend/src/jobs/phoning/export-stagiaires.js
  backend/src/jobs/phoning/index.js
  backend/src/jobs/stats/emails/domainMailStatsBuilder.js
  backend/src/jobs/stats/emails/emailStatsBuilder.js
  backend/src/jobs/stats/emails/index.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/backoffice/forgottenPassword-routes-test.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/jobs/import/stagiaires/ileDeFranceCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/traineeImporter-test.js
  backend/test/integration/jobs/import/stagiaires/validateCsvFile-test.js
  backend/test/unit/regions-test.js
  backoffice/Dockerfile
  questionnaire/Dockerfile
  questionnaire/public/images/regions/carif-12.png
  questionnaire/public/images/regions/carif-13.png
  questionnaire/public/images/regions/carif-14.png
  questionnaire/public/images/regions/carif-15.png
  questionnaire/public/images/regions/carif-16.png
  questionnaire/public/images/regions/carif-18.png
  questionnaire/public/images/regions/carif-2.png
  questionnaire/public/images/regions/carif-3.png
  questionnaire/public/images/regions/carif-4.png
  questionnaire/public/images/regions/carif-5.png
  questionnaire/public/images/regions/carif-6.png
  questionnaire/public/images/regions/carif-7.png
  questionnaire/public/images/regions/carif-8.png
  questionnaire/public/images/regions/carif-9.png
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/pages/Remerciements.jsx
  widget/Dockerfile
Labels: master, ready

#575 Resend avis emails after 6 days instead of 7
  backend/config/default.json
Labels: master, ready

#577 Mise en production
  backend/config/regions.json
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/test/unit/regions-test.js
  questionnaire/public/images/regions/region-4.png
Labels: master, ready

#578 update martinique configuration + logo
  backend/config/regions.json
  backend/src/http/public/static/images/regions/logo-email/logo_13.png
  questionnaire/public/images/regions/region-13.png
Labels: ready

#579 change delay to hide popup on advice publish event
  backoffice/src/components/backoffice/common/message/LocalMessage.jsx
Labels: ready

#582 don't care if advice is published or not
  backend/src/jobs/stats/emails/emailStatsBuilder.js
Labels: ready

#585 Mise en production pour la martinique
  backend/config/regions.json
  backend/src/http/public/static/images/regions/logo-email/logo_13.png
  questionnaire/public/images/regions/region-13.png
Labels: master, ready

#580 Fetch paginated avis inside widget
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
  backend/src/http/routes/api/swagger.yml
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/common/Avis.scss
  widget/src/components/services/formationService.js
  widget/src/components/services/organismeService.js
  widget/src/services/http-client.js
  widget/src/services/widgetService.js
Labels: ready

#565 fix css to correspond to emeline's maquettes
  backoffice/src/components/login/ForgottenPassword.jsx
  backoffice/src/components/login/ForgottenPassword.scss
  backoffice/src/components/login/LoginForm.jsx
  backoffice/src/components/login/LoginForm.scss
Labels: ready

#586 Add contact stagiaires into Carrousel
  widget/public/index.html
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/common/ContactStagiaire.jsx
Labels: ready

#587 Fix session date in widget
  widget/src/components/common/Avis.jsx
Labels: bug, master, ready

#547 enable normandie
  backend/config/regions.json
  backend/test/unit/regions-test.js
Labels: ready

#590 Add an env attribute to force widget env url
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
Labels: ready

#592 Fix contactez-nous link
  backoffice/src/components/login/ForgottenPassword.jsx
  widget/src/services/http-client.js
Labels: ready

#591 Mise en production
  backend/config/regions.json
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
  backend/src/http/routes/api/swagger.yml
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/http/routes/api/v1/utils/validators.js
  backend/src/http/views/front/doc/widget-tests.ejs
  backend/src/jobs/import/stagiaires/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/stats/emails/emailStatsBuilder.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/jobs/import/stagiaires/traineeImporter-test.js
  backend/test/unit/regions-test.js
  backoffice/src/components/backoffice/common/message/LocalMessage.jsx
  backoffice/src/components/login/ForgottenPassword.jsx
  backoffice/src/components/login/ForgottenPassword.scss
  backoffice/src/components/login/LoginForm.jsx
  backoffice/src/components/login/LoginForm.scss
  docker-compose.override.yml
  questionnaire/src/components/common/Footer.jsx
  widget/public/index.html
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/common/Avis.scss
  widget/src/components/common/ContactStagiaire.jsx
  widget/src/components/common/Notes.jsx
  widget/src/components/common/Notes.scss
  widget/src/components/common/images/help.png
  widget/src/components/services/formationService.js
  widget/src/components/services/organismeService.js
  widget/src/services/http-client.js
  widget/src/services/widgetService.js
Labels: master

#595 Polish widget
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/CarrouselWidget.scss
  widget/src/components/ListeWidget.jsx
Labels: master, ready

#588 fix export for rejected advices
  backend/src/http/routes/api/backoffice/export-routes.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#589 fix aggregation : advice with comment count
  backend/src/jobs/stats/emails/emailStatsBuilder.js
Labels: ready

#572 Stats app
  backend/src/http/routes/api/public-stats.js
  backend/src/http/server.js
  docker-compose.yml
  misc/nginx/app/nginx/conf.d/locations.inc
  stats/.gitignore
  stats/Dockerfile
  stats/package-lock.json
  stats/package.json
  stats/public/favicon.ico
  stats/public/index.html
  stats/public/manifest.json
  stats/src/App.css
  stats/src/App.jsx
  stats/src/App.scss
  stats/src/App.test.js
  stats/src/components/DropDown.jsx
  stats/src/components/DropDown.scss
  stats/src/components/Filter.jsx
  stats/src/components/Filter.scss
  stats/src/components/FiltersList.jsx
  stats/src/components/FiltersList.scss
  stats/src/components/Header.jsx
  stats/src/components/Header.scss
  stats/src/components/Loader.jsx
  stats/src/components/Loader.scss
  stats/src/components/Loader.svg
  stats/src/components/SearchButton.jsx
  stats/src/components/SearchButton.scss
  stats/src/components/StatsTable.jsx
  stats/src/components/StatsTable.scss
  stats/src/components/images/logo-anotea.png
  stats/src/components/services/avisService.js
  stats/src/components/services/organismeService.js
  stats/src/constantes/AvisFilters.js
  stats/src/constantes/OrganismesFilters.js
  stats/src/index.css
  stats/src/index.js
  stats/src/logo.svg
  stats/src/serviceWorker.js
  stats/src/styles/variables.scss
  stats/src/utils/http-client.js
Labels: ready

#594 Polish slack notification when sending emails
  backend/src/jobs/mailing/stagiaires/avis/index.js
Labels: ready

#600 send email when response is rejected
  backend/src/common/components/mailing/sendInjureMail.js
  backend/src/common/components/mailing/sendReponseRejeteeNotification.js
  backend/src/common/components/moderation.js
  backend/src/components.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
  backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
Labels: ready

#598 add email on forgotten password screen
  backoffice/src/components/login/ForgottenPassword.jsx
Labels: ready

#603 Convert script to be able to create account
  backend/src/jobs/auth/createNewAccount.js
  backend/src/jobs/data/indexes/mongoIndexes.js
Labels: master, ready

#597 Activate Occitanie again
  backend/config/regions.json
  backend/test/unit/regions-test.js
Labels: master, ready

#602 Activation des emails organismes pour Guadeloupe et HDF
  backend/config/regions.json
Labels: master, ready

#606 Send arrays as streams in API
  backend/src/common/utils/stream-utils.js
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/http/routes/routes-utils.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
Labels: ready

#605 adding label to pie charts
  backoffice/package-lock.json
  backoffice/package.json
  backoffice/src/components/backoffice/organisation/Graphes.js
Labels: ready

#601 Add reponse status
  backend/src/common/utils/getReponseStatus.js
  backend/src/http/routes/api/backoffice/export-routes.js
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
Labels: ready

#610 Fix stats app path
  backend/src/http/routes/front/html-routes.js
  stats/package.json
Labels: ready

#611 Reformat stats code
  stats/public/index.html
  stats/src/App.css
  stats/src/App.jsx
  stats/src/App.scss
  stats/src/App.test.js
  stats/src/components/DropDown.jsx
  stats/src/components/DropDown.scss
  stats/src/components/Filter.jsx
  stats/src/components/Filter.scss
  stats/src/components/FiltersList.jsx
  stats/src/components/FiltersList.scss
  stats/src/components/Header.jsx
  stats/src/components/Header.scss
  stats/src/components/Loader.scss
  stats/src/components/SearchButton.scss
  stats/src/components/StatsTable.jsx
  stats/src/components/StatsTable.scss
  stats/src/constantes/AvisFilters.js
  stats/src/constantes/OrganismesFilters.js
  stats/src/index.css
  stats/src/serviceWorker.js
Labels: ready

#608 Add Course and CourseInstance
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/utils/schema.js
  backend/src/jobs/import/reconciliation/tasks/reconcile.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileActions.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileFormation.js
  backend/src/jobs/import/reconciliation/tasks/utils/reconcileSessions.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileSessions-test.js
Labels: ready

#607 Add test about email in rejectReponse (+fix logger)
  backend/src/components.js
  backend/test/helpers/fake-mailer.js
  backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
Labels: ready

#612 Add stats to compare reconciliation with/out certification
  backend/src/common/components/stats.js
  backend/src/http/views/front/stats.ejs
Labels: ready

#614 remove unique index (collisions)
  backend/src/jobs/data/indexes/mongoIndexes.js
Labels: ready

#609 allow moderator to edit tags
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
Labels: ready

#615 update stats calculation
  backend/src/http/routes/api/backoffice/stats-routes.js
  backend/src/jobs/stats/emails/emailStatsBuilder.js
  backoffice/src/components/backoffice/financeur/stats/Graph.js
  backoffice/src/components/backoffice/financeur/stats/Table.js
Labels: ready

#616 add reponse to BO financeur
  backoffice/src/components/backoffice/common/utils/getReponseStatus.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
  backoffice/src/styles/deprecated/anotea-deprecated.scss
Labels: ready

#617 Rework script messages sent to slack
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/mailing/organismes/account/index.js
  backend/src/jobs/mailing/organismes/notifications/index.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
Labels: ready

#621 remove SessionStats React component
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
  backoffice/src/components/backoffice/organisation/sessionStats.js
  backoffice/src/styles/deprecated/anotea-deprecated.scss
Labels: ready

#618 Add stats to compare reconciliation with/out certification
  backend/src/common/components/stats.js
  backend/src/http/views/front/stats.ejs
Labels: ready

#619 Prepare organismes to be patched
  backend/src/jobs/data/corrector/stagiaires/index.js
  backend/src/jobs/data/corrector/stagiaires/tasks/correctCertifinfos.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/indexes/index.js
  backend/src/jobs/data/indexes/tasks/createIndexes.js
  backend/src/jobs/data/indexes/tasks/dropIndexes.js
  backend/src/jobs/data/indexes/tasks/findUnusedIndexes.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/src/jobs/import/stagiaires/tasks/utils/utils.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/src/jobs/import/stagiaires/tasks/validateCsvFile.js
  backend/src/jobs/import/stagiaires/traineeImporter.js
  backend/test/helpers/test-database.js
  backend/test/integration/jobs/data/corrector/stagiaires/correctCertifinfos-test.js
  backend/test/integration/jobs/import/stagiaires/ileDeFranceCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
  backend/test/integration/jobs/import/stagiaires/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/stagiaires/validateCsvFile-test.js
Labels: ready

#620 add rejected response tab
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
  backoffice/src/components/backoffice/organisation/service/organismeService.js
  backoffice/src/styles/deprecated/anotea-deprecated.scss
Labels: ready

#625 sort by reponse date
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
Labels: ready

#613 Filter reconciliated avis based on certifInfos
  backend/src/common/components/stats.js
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/jobs/data/migration/cleanCertifInfos.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/import/reconciliation/tasks/reconcile.js
  backend/src/jobs/import/reconciliation/tasks/reconcile/reconcileActions.js
  backend/src/jobs/import/reconciliation/tasks/reconcile/reconcileFormation.js
  backend/src/jobs/import/reconciliation/tasks/reconcile/reconcileSessions.js
  backend/src/jobs/import/reconciliation/tasks/reconcile/utils/filterAvisReconciliables.js
  backend/src/jobs/import/reconciliation/tasks/reconcile/utils/findAvisReconciliables.js
  backend/test/integration/jobs/import/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/import/reconciliation/reconcileSessions-test.js
Labels: ready

#622 Remove --append option in import stagiaires script
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#623 Sync comment and trainee collections
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/syncStagiaireAndAvis.js
Labels: ready

#624 Patch organisme responsable/formateurs
  backend/src/jobs/data/corrector/stagiaires/index.js
  backend/src/jobs/data/patch/stagiaires/index.js
  backend/src/jobs/data/patch/stagiaires/tasks/patchCertifInfos.js
  backend/src/jobs/data/patch/stagiaires/tasks/patchOrganismeResponsable.js
  backend/test/integration/jobs/data/stagiaires/patchCertifInfos-test.js
  backend/test/integration/jobs/data/stagiaires/patchOrganismeResponsable-test.js
Labels: ready

#626 Activation de la région Nouvelle Aquitaine
  backend/config/regions.json
  backend/test/unit/regions-test.js
Labels: master, ready

#627 Activation Normandie, Bretagne, Martinique emails
  backend/config/regions.json
Labels: master, ready

#629 Clean reconciliation metadata
  backend/src/common/components/stats.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/cleanReconciliationMetadata.js
  backend/src/jobs/export/exportAvisReconciliableCSV.js
  backend/src/jobs/reconciliation/tasks/addReconciliationAvisMetadata.js
  backend/test/integration/jobs/reconciliation/addReconciliationAvisMetadata-test.js
Labels: ready

#631 Show number and percentage on stats
  backend/src/common/components/stats.js
Labels: ready

#632 Calcul des Taux de commentaires en fonction de countAdvicesModerated
  backoffice/src/components/backoffice/financeur/stats/Table.js
Labels: ready

#630 Reconciliation par SIREN
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileActions.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileFormation.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileSessions.js
  backend/src/jobs/reconciliation/tasks/reconcile/utils/findAvisReconciliables.js
  backend/src/jobs/reconciliation/tasks/reconcile/utils/getReconcilatedAvis.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
Labels: ready

#633 Fix BO stars
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Stagiaire.jsx
Labels: ready

#635 Deactivate features
  backend/src/common/components/mailing/sendReponseRejeteeNotification.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js
  backend/src/http/routes/api/public-stats.js
  backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#638 Add env attributes and avis-details option
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
  widget/src/App.jsx
  widget/src/App.scss
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/common/Avis.jsx
  widget/src/components/common/Notes.jsx
  widget/src/components/common/Notes.scss
  widget/src/components/common/Tooltip.jsx
  widget/src/components/common/Tooltip.scss
  widget/src/components/common/images/help.png
  widget/src/components/common/options/Option.jsx
  widget/src/components/common/options/OptionsContext.jsx
Labels: ready

#640 Rename --file parameter
  backend/src/jobs/import/organismes/index.js
Labels: ready

#642 clean up reponse in CSV export
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
Labels: ready

#643 bigger pie chart
  backoffice/src/components/backoffice/organisation/Graphes.js
Labels: ready

#645 add loader spinner on password forgotten ask
  backoffice/src/components/login/ForgottenPassword.jsx
  backoffice/src/components/login/ForgottenPassword.scss
Labels: ready

#646 Add routes to get all regions
  backend/src/common/components/regions.js
  backend/src/http/routes/api/regions-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/regions-routes-test.js
Labels: ready

#651 Activation emails OF Nouvelle-Aquitaine et Occitanie
  backend/config/regions.json
Labels: master, ready

#647 New contact stagiaire button
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/common/utils/stream-utils.js
  backend/src/http/middlewares.js
  backend/src/http/routes/api/contact-stagiaires-routes.js
  backend/src/http/routes/routes-utils.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/contact-stagiaires-routes-test.js
  backoffice/src/components/backoffice/common/library/Button.scss
  questionnaire/src/components/common/library/Button.scss
  widget/src/App.jsx
  widget/src/components/common/ContactStagiaire.jsx
  widget/src/components/common/ContactStagiaire.scss
  widget/src/components/common/library/Button.scss
  widget/src/components/common/library/Modal.jsx
  widget/src/components/common/library/Modal.scss
  widget/src/services/http-client.js
  widget/src/services/widgetService.js
  widget/src/utils.js
Labels: ready

#648 Ensure xss questionnaire
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/api/questionnaire/utils/userInput.js
  backend/test/unit/userInput-test.js
  backend/test/unit/userInput.js
Labels: ready

#649 Move pagination button upper
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/CarrouselWidget.scss
  widget/src/components/common/Avis.scss
Labels: ready

#650 Send notifications to organismes once a month
  backend/config/default.json
  backend/test/integration/jobs/mailing/organismes/notifications/NotificationMailer-test.js
Labels: ready

#652 add pastille to BO moderation header
  backend/src/http/routes/api/backoffice/moderateur/stats.js
  backend/src/http/server.js
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Header.scss
  backoffice/src/components/backoffice/moderateur/moderation/moderationService.js
Labels: ready

#658 Add new streamToCSV util (+DQS export)
  backend/src/common/utils/stream-utils.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/job-utils.js
Labels: ready

#653 Affichage des réponses sans commentaires dans le widget
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js
  backend/src/http/routes/api/swagger.yml
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createAccounts.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/dataset/tasks/dumpAvis.js
  backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
  widget/src/components/common/Avis.jsx
Labels: ready

#660 adding taux repondants
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backoffice/src/components/backoffice/organisation/Graphes.js
  backoffice/src/components/backoffice/organisation/Graphes.scss
Labels: ready

#654 Refacto stats
  stats/src/components/common/Loader.jsx
  stats/src/components/stats/filters/DropDown.jsx
  stats/src/components/stats/filters/Filter.jsx
  stats/src/components/stats/filters/FiltersList.jsx
  stats/src/components/stats/filters/constantes/AvisFilters.js
  stats/src/components/stats/filters/constantes/OrganismesFilters.js
Labels: ready

#662 Change wording & add hovers
  stats/src/components/stats/ApiStatsTable.jsx
  stats/src/components/stats/Header.jsx
  stats/src/components/stats/OrganismesStatsTable.jsx
  stats/src/components/stats/StatsTable.scss
Labels: ready

#663 add hover for avis part
  stats/src/components/stats/AvisStatsTable.jsx
Labels: ready
