Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-11, with the labels that each got.

#954 Remove useless docker command
  misc/nginx/app/start.sh
Labels: master, ready

#955 Fix conseil region since filter
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/test/helpers/data/stagiaires-pe-ara-conseil-regional.csv
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#952 Ouverture CR sur region BFC
  backend/config/regions.json
  backend/src/http/public/static/images/regions/logo-email/logo_3.png
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/test/helpers/data/stagiaires-pe-ara-conseil-regional.csv
  backend/test/helpers/data/stagiaires-pe-bfc.csv
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
  questionnaire/public/images/regions/carif-3.png
  questionnaire/public/images/regions/region-3.png
Labels: master, ready

#956 fix header margin/padding for email clients
  backend/src/smtp/views/common/header.css
Labels: bug, master, ready

#958 Remove popup doc
  backend/src/http/routes/front/html-routes.js
  backend/src/http/views/front/doc/popup.ejs
Labels: ready

#957 Handle postal/insee code wit 2A and 2B
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildSession.js
  backend/test/helpers/data/stagiaires-pe-corse.csv
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: master, ready

#962 Enhance application detection in export
  backend/src/http/middlewares/utils/findApplication.js
Labels: master, ready

#959 Hide reponse when avis has been rejected
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/test/unit/utils/convertCommentToAvis-test.js
Labels: master, ready

#963 Enhance project starter
  README.md
  backend/package.json
  backend/src/http/public/static/images/logo-pole-emploi.svg
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createStagiaires.js
  backend/src/jobs/stats/index.js
  backend/src/jobs/stats/tasks/computeStats.js
  backend/src/jobs/stats/tasks/stats/computeApiStats.js
  backend/src/jobs/stats/tasks/stats/computeAvisStats.js
  backend/src/jobs/stats/tasks/stats/computeCampaignStats.js
  backend/src/jobs/stats/tasks/stats/computeOrganismesStats.js
  dev.yml
  docker-compose.override.yml
  misc/doc/diagram/anotea-diagram.drawio
  misc/doc/diagram/anotea-docker-diagram.svg
  widget/src/App.jsx
Labels: master, ready

#964 Add script to export commentaires
  backend/src/jobs/export/exportCommentaires.js
Labels: master, ready

#966 Add bash script to start Anotea easily
  README.md
  dev.sh
Labels: master, ready

#953 [CERTIFINFOS-1] Import new certifInfos CSV
  backend/src/common/components/workflow.js
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/backoffice/utils/getAvisCSV.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/front/utils/externalLinks.js
  backend/src/jobs/data/dataset/tasks/createStagiaires.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/renameCertifInfosAndFormacodes.js
  backend/src/jobs/data/migration/tasks/unsetPatchCertifInfos.js
  backend/src/jobs/export/exportCertifInfos.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/import/stagiaires/tasks/handlers/ileDeFranceCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/utils/validateTrainee.js
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/tasks/Questionnaire6MoisMailer.js
  backend/src/jobs/patch/certifInfos/index.js
  backend/src/jobs/patch/certifInfos/tasks/refreshCertifInfos.js
  backend/src/jobs/reconciliation/tasks/addReconciliationAvisMetadata.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/test/helpers/data/certifinfos-1toN.csv
  backend/test/helpers/data/certifinfos-Nto1.csv
  backend/test/helpers/data/certifinfos-chaine.csv
  backend/test/helpers/data/certifinfos-chaine1toN.csv
  backend/test/helpers/data/certifinfos.csv
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  backend/test/integration/http/routes/front/utils/externalLinks-test.js
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
  backend/test/integration/jobs/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
  backend/test/integration/jobs/refresh/refreshCertifInfos-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
Labels: ready

#968 Change BO Orgasnime stats order
  backoffice/src/components/organisme/components/OrganismeStatsPanel.jsx
Labels: ready

#970 Add ES2017/2018 polyfills
  backoffice/package-lock.json
  backoffice/package.json
  backoffice/public/index.html
  backoffice/src/index.js
  questionnaire/package-lock.json
  questionnaire/package.json
  questionnaire/public/index.html
  questionnaire/src/index.js
  widget/package-lock.json
  widget/package.json
Labels: master, ready

#969 Convert resendEmail route into a delete option
  backend/src/common/components/database.js
  backend/src/common/components/workflow.js
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/sanitizeAvisCreated.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-moderateur-test.js
  backoffice/src/components/common/avis/buttons/EditButton.jsx
  backoffice/src/services/avisService.js
  widget/src/components/common/Avis.jsx
Labels: ready

#972 Remove qualification column when exporting avis csv
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/http/routes/api/backoffice/utils/getAvisCSV.js
Labels: master, ready

#971 Add option to skip npm when using dev.sh
  dev.sh
Labels: ready

#975 Allow login with upper case characters
  backend/src/http/routes/api/backoffice/login-routes.js
  backend/test/integration/http/routes/api/backoffice/login-routes-test.js
Labels: ready

#973 Centralize GlobalMessage in App component
  backoffice/src/App.jsx
  backoffice/src/components/AppContext.jsx
  backoffice/src/components/anonymous/ActivationComptePage.jsx
  backoffice/src/components/anonymous/LoginPage.jsx
  backoffice/src/components/anonymous/MotDePasseOubliePage.jsx
  backoffice/src/components/anonymous/ReinitialisationMotDePassePage.jsx
  backoffice/src/components/common/avis/Avis.jsx
  backoffice/src/components/common/header/Header.jsx
  backoffice/src/components/common/organisme/buttons/EditButton.jsx
  backoffice/src/components/common/organisme/buttons/Edition.jsx
  backoffice/src/components/common/page/Page.jsx
  backoffice/src/components/financeur/FinanceurPage.jsx
  backoffice/src/components/misc/MonComptePage.jsx
  backoffice/src/components/moderateur/gestion-organismes/GestionOrganismePage.jsx
  backoffice/src/components/organisme/OrganismePage.jsx
Labels: ready

#974 Add sentry in backoffice
  backend/src/common/components/sentry.js
  backoffice/Dockerfile
  backoffice/package-lock.json
  backoffice/package.json
  backoffice/src/index.js
  backoffice/src/utils/sentry.js
  docker-compose.override.yml
Labels: ready

#980 Change dataset account logins
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createAccounts.js
Labels: ready

#979 Fix organisme shield (siret->siren)
  backend/src/common/utils/asSiren.js
  backend/src/http/routes/api/backoffice/profiles/organisme.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-organisme-test.js
Labels: bug, master, ready

#982 Refresh dnIndividuNational and idLocal properties
  backend/src/jobs/import/stagiaires/tasks/refreshTrainee.js
  backend/test/helpers/data/stagiaires-pe-refreshed.csv
  backend/test/integration/jobs/import/stagiaires/refreshTrainee-test.js
Labels: bug, ready

#983 Remove react-intl
  backoffice/package.json
  backoffice/src/App.jsx
  backoffice/src/components/common/PrettyDate.jsx
  backoffice/src/components/common/avis/Formation.jsx
  backoffice/src/index.js
  backoffice/src/utils/moment-fr.js
Labels: ready
