Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-12, with the labels that each got.

#986 Prevent duplicated certifInfos elements
  backend/src/common/utils/object-utils.js
  backend/src/jobs/import/stagiaires/tasks/refreshTrainee.js
  backend/src/jobs/patch/certifInfos/tasks/refreshCertifInfos.js
  backend/test/integration/jobs/patch/refreshCertifInfos-test.js
Labels: master, ready

#988 Emails regions route
  backend/src/http/middlewares/middlewares.js
  backend/src/http/routes/api/regions-routes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/regions-routes-test.js
Labels: ready

#987 Fix certifInfos history
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/removeUselessHistoryElements.js
  backend/src/jobs/data/migration/tasks/sanitizePhoneNumbers.js
  backend/src/jobs/import/stagiaires/tasks/refreshTrainee.js
  backend/src/jobs/patch/certifInfos/tasks/refreshCertifInfos.js
  backend/test/integration/jobs/import/stagiaires/refreshTrainee-test.js
  backend/test/integration/jobs/patch/refreshCertifInfos-test.js
Labels: bug, master, ready

#989 Limit reponse length
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-organisme-test.js
  backoffice/src/components/common/avis/ReponseEditor.jsx
Labels: bug, master, ready

#990 Send send slack notifications only when necessary
  backend/src/jobs/archive/index.js
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/mailing/organismes/account/index.js
  backend/src/jobs/mailing/organismes/notifications/index.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
Labels: master, ready

#993 Add alt on all images
  backend/src/common/components/emails/common/header.mjml.ejs
  backend/src/common/components/emails/organismes/activationCompteEmail.mjml.ejs
  backend/src/common/components/emails/stagiaires/avisStagiaireEmail.mjml.ejs
Labels: master, ready

#992 Update faq_financeurs.ejs
  backend/src/http/views/front/faq_financeurs.ejs
Labels: ready

#995 Add characters counter in textarea reponse
  backoffice/src/components/common/avis/ReponseEditor.jsx
  backoffice/src/components/common/avis/ReponseEditor.scss
Labels: ready

#997 Move LibraryPage into anonymous route
  backoffice/src/App.jsx
  backoffice/src/components/anonymous/AnonymousRoutes.jsx
  backoffice/src/components/anonymous/LibraryPage.jsx
  backoffice/src/components/anonymous/LibraryPage.scss
  backoffice/src/components/common/MonComptePage.jsx
  backoffice/src/components/financeur/FinanceurRoutes.jsx
  backoffice/src/components/misc/MiscRoutes.jsx
  backoffice/src/components/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/organisme/OrganismeRoutes.jsx
Labels: ready

#996 Unify how mailing cli parameters are read
  backend/src/jobs/import/stagiaires/index.js
  backend/src/jobs/mailing/organismes/account/index.js
  backend/src/jobs/mailing/organismes/notifications/index.js
  backend/src/jobs/mailing/organismes/questionnaire/index.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/index.js
Labels: ready

#998 Change pie colors on BO OF
  backoffice/src/components/common/page/panel/results/stats/Pie.jsx
  backoffice/src/components/financeur/components/CommentairesStats.jsx
  backoffice/src/components/organisme/components/StagiairesStats.jsx
Labels: ready

#991 Update faq_stagiaires.ejs
  backend/src/http/views/front/faq_financeurs.ejs
  backend/src/http/views/front/faq_stagiaires.ejs
Labels: ready

#999 Rename region-* images into conseil-regional-*
  backend/src/common/components/emails/common/header.mjml.ejs
  backend/src/http/public/static/images/regions/conseil-regional-10.png
  backend/src/http/public/static/images/regions/conseil-regional-11.png
  backend/src/http/public/static/images/regions/conseil-regional-12.png
  backend/src/http/public/static/images/regions/conseil-regional-13.png
  backend/src/http/public/static/images/regions/conseil-regional-14.png
  backend/src/http/public/static/images/regions/conseil-regional-15.png
  backend/src/http/public/static/images/regions/conseil-regional-16.png
  backend/src/http/public/static/images/regions/conseil-regional-17.png
  backend/src/http/public/static/images/regions/conseil-regional-18.png
  backend/src/http/public/static/images/regions/conseil-regional-2.png
  backend/src/http/public/static/images/regions/conseil-regional-3.png
  backend/src/http/public/static/images/regions/conseil-regional-4.png
  backend/src/http/public/static/images/regions/conseil-regional-5.png
  backend/src/http/public/static/images/regions/conseil-regional-6.png
  backend/src/http/public/static/images/regions/conseil-regional-7.png
  backend/src/http/public/static/images/regions/conseil-regional-8.png
  backend/src/http/public/static/images/regions/conseil-regional-9.png
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/dataset/tasks/createStagiaires.js
  questionnaire/public/images/regions/conseil-regional-10.png
  questionnaire/public/images/regions/conseil-regional-11.png
  questionnaire/public/images/regions/conseil-regional-12.png
  questionnaire/public/images/regions/conseil-regional-13.png
  questionnaire/public/images/regions/conseil-regional-14.png
  questionnaire/public/images/regions/conseil-regional-15.png
  questionnaire/public/images/regions/conseil-regional-16.png
  questionnaire/public/images/regions/conseil-regional-17.png
  questionnaire/public/images/regions/conseil-regional-18.png
  questionnaire/public/images/regions/conseil-regional-2.png
  questionnaire/public/images/regions/conseil-regional-3.png
  questionnaire/public/images/regions/conseil-regional-4.png
  questionnaire/public/images/regions/conseil-regional-5.png
  questionnaire/public/images/regions/conseil-regional-6.png
  questionnaire/public/images/regions/conseil-regional-7.png
  questionnaire/public/images/regions/conseil-regional-8.png
  questionnaire/public/images/regions/conseil-regional-9.png
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/pages/Remerciements.jsx
  questionnaire/src/images/logo-pole-emploi.png
  questionnaire/src/images/logo-pole-emploi.svg
  questionnaire/src/lib/getToken.js
Labels: ready

#994 Add PDF stats export
  backoffice/Dockerfile
  backoffice/package-lock.json
  backoffice/package.json
  backoffice/src/components/common/Button.jsx
  backoffice/src/components/common/header/Header.jsx
  backoffice/src/components/common/header/Header.svg
  backoffice/src/components/common/header/Link.jsx
  backoffice/src/components/common/header/logo-financeur.svg
  backoffice/src/components/common/page/panel/Panel.scss
  backoffice/src/components/common/page/panel/results/stats/NoteDetails.jsx
  backoffice/src/components/common/page/panel/results/stats/NoteExplications.jsx
  backoffice/src/components/common/page/panel/results/stats/NoteExplications.scss
  backoffice/src/components/common/page/panel/results/stats/Star.jsx
  backoffice/src/components/common/page/panel/results/stats/Star.png
  backoffice/src/components/common/page/panel/summary/BadgeSummary.jsx
  backoffice/src/components/common/page/panel/summary/BadgeSummary.scss
  backoffice/src/components/common/page/panel/summary/TextSummary.jsx
  backoffice/src/components/common/page/panel/summary/TextSummary.scss
  backoffice/src/components/common/pdf/PDF.jsx
  backoffice/src/components/common/pdf/PDF.scss
  backoffice/src/components/common/pdf/logo-financeur.png
  backoffice/src/components/financeur/FinanceurPage.jsx
  backoffice/src/components/financeur/components/CommentairesStats.jsx
  backoffice/src/components/financeur/components/FinanceurAvisPanel.jsx
  backoffice/src/components/financeur/components/FinanceurStatsPanel.jsx
  backoffice/src/styles/global.scss
  backoffice/src/utils/pdf.js
Labels: ready

#1004 Add Google Analytics click tracker
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/src/common/components/sentry.js
  backoffice/Dockerfile
  backoffice/package-lock.json
  backoffice/package.json
  backoffice/public/index.html
  backoffice/public/manifest.json
  backoffice/src/App.jsx
  backoffice/src/components/WithRouter.jsx
  backoffice/src/components/analytics/AnalyticsContext.jsx
  backoffice/src/components/analytics/WithAnalytics.jsx
  backoffice/src/components/anonymous/ActivationComptePage.jsx
  backoffice/src/components/anonymous/ReinitialisationMotDePassePage.jsx
  backoffice/src/components/common/Button.jsx
  backoffice/src/components/common/MonComptePage.jsx
  backoffice/src/components/common/PrettyDate.jsx
  backoffice/src/components/common/avis/Avis.jsx
  backoffice/src/components/common/header/Header.jsx
  backoffice/src/components/common/page/Page.jsx
  backoffice/src/components/common/page/form/Form.jsx
  backoffice/src/components/common/page/form/Periode.jsx
  backoffice/src/components/common/page/form/Select.jsx
  backoffice/src/components/common/page/form/date/Date.jsx
  backoffice/src/components/common/page/form/date/Date.scss
  backoffice/src/components/common/page/form/date/datepicker.js
  backoffice/src/components/common/page/form/date/datepicker.scss
  backoffice/src/components/common/page/panel/Panel.jsx
  backoffice/src/components/common/page/panel/Panel.scss
  backoffice/src/components/common/page/panel/filters/Filter.jsx
  backoffice/src/components/common/page/panel/filters/Filter.scss
  backoffice/src/components/common/page/panel/pagination/Pagination.jsx
  backoffice/src/components/common/page/panel/results/AvisResults.jsx
  backoffice/src/components/common/page/tabs/Tab.jsx
  backoffice/src/components/common/page/tabs/Tab.scss
  backoffice/src/components/financeur/FinanceurPage.jsx
  backoffice/src/components/moderateur/ModerateurHeaderItems.jsx
  backoffice/src/components/moderateur/courriels/OrganismesEmailsPreviewPage.jsx
  backoffice/src/components/moderateur/courriels/StagiairesEmailsPreviewPage.jsx
  backoffice/src/components/moderateur/gestion-organismes/GestionOrganismePage.jsx
  backoffice/src/components/moderateur/gestion-organismes/components/Organisme.jsx
  backoffice/src/components/moderateur/gestion-organismes/components/Organisme.scss
  backoffice/src/components/moderateur/gestion-organismes/components/buttons/EditButton.jsx
  backoffice/src/components/moderateur/gestion-organismes/components/buttons/Edition.jsx
  backoffice/src/components/organisme/OrganismePage.jsx
  backoffice/src/index.js
  backoffice/src/styles/global.scss
  backoffice/src/utils/financeurs.js
  backoffice/src/utils/hotjar.js
  backoffice/src/utils/password-utils.js
  backoffice/src/utils/sentry.js
  docker-compose.override.yml
Labels: ready

#1001 Widget sort
  backend/src/http/routes/api/v1/actions-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/formations-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/http/routes/api/v1/reconcilication/findDocumentsAsStream.js
  backend/src/http/routes/api/v1/reconcilication/getAvis.js
  backend/src/http/routes/api/v1/reconcilication/getDocument.js
  backend/src/http/routes/api/v1/reconcilication/reconciliation.js
  backend/src/http/routes/api/v1/sessions-routes.js
  backend/src/http/routes/api/v1/utils/buildSort.js
  backend/src/http/routes/api/v1/utils/dto.js
  backend/src/http/routes/api/v1/utils/roundNotes.js
  backend/src/http/routes/api/v1/utils/schema.js
  backend/src/http/routes/api/v1/utils/validators.js
  backend/src/http/routes/routes-utils.js
  backend/src/http/server.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  widget/src/App.jsx
  widget/src/components/CarrouselWidget.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/ListeWidget.scss
  widget/src/services/widgetService.js
Labels: ready

#1010 Get ride of rxjs
  backend/package-lock.json
  backend/package.json
  backend/src/common/utils/stream-utils.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/import/intercarif/importIntercarif.js
  backend/src/jobs/import/intercarif/index.js
  backend/src/jobs/import/intercarif/tasks/importIntercarif.js
  backend/src/jobs/import/intercarif/tasks/utils/sanitizeJson.js
  backend/src/jobs/import/intercarif/tasks/utils/xmlToJson.js
  backend/src/jobs/import/intercarif/utils/getFormationsFromXml.js
  backend/src/jobs/import/intercarif/utils/unpackGzFile.js
  backend/test/helpers/with-mongodb.js
  backend/test/integration/jobs/import/intercarif/importIntercarif-test.js
  backend/test/unit/jobs/import/intercarif/getFormationsFromXml-test.js
Labels: ready

#1009 Enhance reconciliation tests
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
Labels: ready

#1012 Modal contact new home
  backend/src/http/public/static/css/front/modal-contact.css
  backend/src/http/public/static/js/contact.js
  backend/src/http/views/contact.ejs
  backend/src/http/views/front/faq_organismes.ejs
  backend/src/http/views/front/faq_stagiaires.ejs
  backend/src/http/views/front/footer.ejs
  backend/src/http/views/front/homepage.ejs
  backend/src/http/views/modal-contact.ejs
  backoffice/src/components/anonymous/ContactRegion.jsx
  backoffice/src/components/anonymous/ContactRegion.scss
Labels: ready

#1013 Sort avis by scheduledEndDate instead of date
  backend/src/http/routes/api/v1/reconcilication/getAvis.js
  backend/src/http/routes/api/v1/utils/buildSort.js
  backend/src/http/routes/api/v1/utils/dto.js
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/formations-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
  widget/src/App.jsx
  widget/src/components/ListeWidget.jsx
  widget/src/components/WidgetContext.jsx
  widget/src/components/common/Header.jsx
Labels: ready

#1011 Remove accord and accordEntreprise
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/deprecatedProperties.js
  backend/src/jobs/stats/tasks/stats/computeCampaignStats.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/questionnaire/Autorisations.jsx
  questionnaire/src/components/pages/questionnaire/Autorisations.scss
  stats/src/components/stats/AvisStatsTable.jsx
Labels: ready

#1007 Update npm dependencies for node.js v12
  backoffice/package-lock.json
  backoffice/package.json
  questionnaire/package-lock.json
  questionnaire/package.json
  stats/package-lock.json
  stats/package.json
  widget/package-lock.json
  widget/package.json
Labels: ready

#1014 Update questionnaire to be accessible
  backoffice/src/styles/variables.scss
  questionnaire/src/components/common/Formation.jsx
  questionnaire/src/components/common/formation.scss
  questionnaire/src/components/pages/questionnaire.scss
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
  questionnaire/src/components/pages/questionnaire/notes/Notes.jsx
  questionnaire/src/components/pages/questionnaire/notes/note.scss
  questionnaire/src/components/pages/questionnaire/notes/notes.scss
  questionnaire/src/components/pages/questionnaire/notes/stars.scss
  questionnaire/src/styles/variables.scss
Labels: ready

#1015 Generate test passwords during runtime
  backend/test/integration/http/routes/api/backoffice/gestion-organismes-routes-test.js
  backend/test/integration/http/routes/api/backoffice/login-routes-test.js
Labels: master, ready

#1018 Bind container ports to localhost only
  docker-compose.override.yml
Labels: ready

#1019 Rename publish into validate
  backend/package.json
  backend/src/common/components/workflow.js
  backend/src/http/routes/api/backoffice/avis-routes.js
  backend/src/jobs/data/dataset/tasks/emulateWorkflowActions.js
  backend/test/integration/http/routes/api/backoffice/avis-routes-moderateur-test.js
  ui/src/backoffice/components/common/avis/CommentaireEditor.jsx
  ui/src/backoffice/components/common/avis/buttons/ValidateButton.jsx
  ui/src/backoffice/components/common/avis/buttons/ValidateReponseButton.jsx
  ui/src/backoffice/services/avisService.js
Labels: ready
