Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-03, with the labels that each got.

#342 export for SMS campaign
  backend/src/jobs/phoning/export-stagiaires.js
  backend/src/jobs/phoning/index.js
Labels: ready

#366 Ouverture région BFC
  backend/config/default.json
  backend/src/http/public/img/regions/logo-email/logo_3.png
  backend/src/jobs/stats/buildOrganismesCSV.js
Labels: master

#333 [WIP] Ouverture Bourgogne-Franche-Comté et Normandie
  backend/config/default.json
  backend/src/http/public/img/regions/logo-email/logo_14.png
  backend/src/http/public/img/regions/logo-email/logo_3.png
  backend/src/jobs/stats/buildOrganismesCSV.js
Labels: master

#368 fix uri
  questionnaire/src/App.jsx
Labels: ready

#370 nginx location : remove useless trailing slash
  misc/nginx/app/nginx/conf.d/locations.inc
Labels: ready

#367 Active email for BFC
  backend/config/default.json
Labels: master

#371 Fix new questionnaire
  backend/src/http/routes/front/front.js
  backend/src/http/routes/front/questionnaire.js
  questionnaire/src/App.jsx
  questionnaire/src/components/Notes.jsx
  questionnaire/src/components/common/Note.jsx
  questionnaire/src/components/header.scss
  questionnaire/src/components/remerciements.scss
Labels: ready

#361 content of summary title to depend on status.
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
Labels: ready

#372 Show moderation messages during 2500ms
  backoffice/src/components/backoffice/common/message/GlobalMessage.jsx
  backoffice/src/components/backoffice/common/message/LocalMessage.jsx
Labels: ready

#373 New questionnaire UX
  questionnaire/src/components/Header.jsx
  questionnaire/src/components/Notes.jsx
  questionnaire/src/components/Questionnaire.jsx
  questionnaire/src/components/SummaryModal.jsx
  questionnaire/src/components/common/averageScore.scss
  questionnaire/src/components/common/stars.scss
  questionnaire/src/components/header.scss
  questionnaire/src/components/notes.scss
  questionnaire/src/components/panelRemerciements.scss
  questionnaire/src/components/questionnaire.scss
  questionnaire/src/components/summaryModal.scss
Labels: ready

#374 Polish UI and fix moderation issues
  backend/src/http/routes/backoffice/moderateur/gestion-organismes.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
  backoffice/src/components/backoffice/common/Header.scss
  backoffice/src/components/backoffice/common/Modal.scss
  backoffice/src/components/backoffice/common/message/Alert.jsx
  backoffice/src/components/backoffice/common/message/LocalMessage.scss
  backoffice/src/components/backoffice/common/panel/Pagination.jsx
  backoffice/src/components/backoffice/common/panel/ResultDivider.scss
  backoffice/src/components/backoffice/common/panel/Summary.jsx
  backoffice/src/components/backoffice/common/panel/toolbar/Toolbar.scss
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.scss
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.scss
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
Labels: ready

#375 Prevent compute score function to update moderateur accounts
  backend/src/jobs/import/organismes/computeOrganismesScore.js
  backend/test/integration/jobs/import/organismes/computeOrganismesScore-test.js
Labels: bug, master, ready

#377 archive avis > 24 months
  backend/src/jobs/archive/archive.js
Labels: ready

#376 Backoffice : fix CSV export
  backend/src/http/routes/backoffice/export.js
Labels: bug, ready

#378 fix avis saving
  backend/src/http/routes/front/questionnaire.js
Labels: ready

#379 Fix header color for /mon-compte route
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/account/MonComptePanel.jsx
  backoffice/src/components/backoffice/account/MonComptePanel.scss
  backoffice/src/components/backoffice/account/MyAccount.jsx
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Header.scss
  backoffice/src/components/backoffice/common/panel/Panel.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
Labels: ready

#380 Search organisme with an insensitive regex
  backend/src/http/routes/backoffice/moderateur/gestion-organismes.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
Labels: ready

#369 update FROM email
  backend/config/default.json
Labels: master, ready

#383 Fix Martinique activation
  backend/config/default.json
Labels: ready

#381 add browserstack
  README.md
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
  questionnaire/package-lock.json
  questionnaire/package.json
  questionnaire/test/conf.js
  questionnaire/test/spec.js
Labels: ready

#385 Improve email
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#386 Add new /kairos/check-if-organisme-is-eligible route
  backend/src/http/middlewares.js
  backend/src/http/routes/api/kairos.js
  backend/src/http/routes/backoffice/auth/kairos.js
  backend/src/http/routes/swagger.yml
  backend/src/http/server.js
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/test/integration/http/routes/kairos-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
Labels: ready

#389 fix excel export in financer panel
  backend/src/http/routes/backoffice/export.js
Labels: ready

#388 Add test coverage
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
Labels: ready

#390 Configurable tracker id for Google Analytics and Hotjar
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backoffice/Dockerfile
  backoffice/public/index.html
  docker-compose.yml
  questionnaire/Dockerfile
  questionnaire/public/index.html
Labels: ready

#392 BO: fix Dockerfile
  backoffice/Dockerfile
Labels: ready

#394 Fix hotjar and google env variables
  backoffice/Dockerfile
  backoffice/public/index.html
  docker-compose.yml
  questionnaire/Dockerfile
  questionnaire/public/index.html
Labels: ready

#391 Handle error when import organismes script fails
  backend/src/jobs/import/organismes/generateOrganismesFromKairos.js
Labels: ready

#395 Move library components into a dedicated folder
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/library/Button.jsx
  backoffice/src/components/backoffice/common/library/Button.scss
  backoffice/src/components/backoffice/common/library/Dropdown.jsx
  backoffice/src/components/backoffice/common/library/Dropdown.scss
  backoffice/src/components/backoffice/common/library/GridDisplayer.jsx
  backoffice/src/components/backoffice/common/library/GridDisplayer.scss
  backoffice/src/components/backoffice/common/library/Modal.jsx
  backoffice/src/components/backoffice/common/library/Modal.scss
  backoffice/src/components/backoffice/misc/LibraryPanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Notes.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectReponseButton.jsx
Labels: ready

#397 Convert textarea into input text
  backend/src/http/routes/front/questionnaire.js
  questionnaire/src/App.jsx
  questionnaire/src/components/NoMatch.jsx
  questionnaire/src/components/PanelRemerciements.jsx
  questionnaire/src/components/Questionnaire.jsx
  questionnaire/src/components/Remerciements.jsx
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/common/Formation.jsx
  questionnaire/src/components/common/formation.scss
  questionnaire/src/components/panelRemerciements.scss
  questionnaire/src/components/questionnaire.scss
  questionnaire/src/components/questionnaire/Autorisations.jsx
  questionnaire/src/components/questionnaire/Autorisations.scss
  questionnaire/src/components/questionnaire/GlobalError.jsx
  questionnaire/src/components/questionnaire/Summary.jsx
  questionnaire/src/components/questionnaire/commentaire/Badwords.jsx
  questionnaire/src/components/questionnaire/commentaire/Commentaire.jsx
  questionnaire/src/components/questionnaire/commentaire/Textarea.jsx
  questionnaire/src/components/questionnaire/commentaire/Textarea.scss
  questionnaire/src/components/questionnaire/commentaire/badwords.scss
  questionnaire/src/components/questionnaire/commentaire/commentaire.scss
  questionnaire/src/components/questionnaire/globalError.scss
  questionnaire/src/components/questionnaire/notes/FoldButton.jsx
  questionnaire/src/components/questionnaire/notes/Note.jsx
  questionnaire/src/components/questionnaire/notes/NoteMoyenne.jsx
  questionnaire/src/components/questionnaire/notes/NoteMoyenne.scss
  questionnaire/src/components/questionnaire/notes/Notes.jsx
  questionnaire/src/components/questionnaire/notes/foldButton.scss
  questionnaire/src/components/questionnaire/notes/note.scss
  questionnaire/src/components/questionnaire/notes/notes.scss
  questionnaire/src/components/remerciements.scss
Labels: ready

#401 Try to fix react env variables
  backoffice/public/index.html
  questionnaire/public/index.html
Labels: ready

#405 Trainee import : allow to filter on certif info
  backend/src/jobs/import/trainee/index.js
  backend/src/jobs/import/trainee/traineeImporter.js
  backend/test/helpers/data/stagiaires-pe.csv
  backend/test/integration/jobs/import/trainee/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/trainee/traineeImporter-test.js
Labels: ready

#408 Fix footer images
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/common/footer.scss
Labels: ready

#406 Remove router to be compatible with IE11
  backend/src/http/routes/front/questionnaire.js
  questionnaire/package-lock.json
  questionnaire/package.json
  questionnaire/public/images/logo-pole-emploi-530.png
  questionnaire/public/images/logo.svg
  questionnaire/public/index.html
  questionnaire/src/App.jsx
  questionnaire/src/App.scss
  questionnaire/src/components/Remerciements.jsx
  questionnaire/src/components/common/Footer.jsx
  questionnaire/src/components/common/footer.scss
  questionnaire/src/components/noMatch.scss
  questionnaire/src/components/pages/ErrorPage.jsx
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/Remerciements.jsx
  questionnaire/src/components/pages/errorPage.scss
  questionnaire/src/components/pages/questionnaire.scss
  questionnaire/src/components/pages/questionnaire/Autorisations.jsx
  questionnaire/src/components/pages/questionnaire/Autorisations.scss
  questionnaire/src/components/pages/questionnaire/ErrorMessage.jsx
  questionnaire/src/components/pages/questionnaire/Summary.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/Badwords.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/badwords.scss
  questionnaire/src/components/pages/questionnaire/commentaire/commentaire.scss
  questionnaire/src/components/pages/questionnaire/error-alert.scss
  questionnaire/src/components/pages/questionnaire/notes/AverageScore.jsx
  questionnaire/src/components/pages/questionnaire/notes/Note.jsx
  questionnaire/src/components/pages/questionnaire/notes/NoteMoyenne.jsx
  questionnaire/src/components/pages/questionnaire/notes/NoteMoyenne.scss
  questionnaire/src/components/pages/questionnaire/notes/Notes.jsx
  questionnaire/src/components/pages/questionnaire/notes/Stars.jsx
  questionnaire/src/components/pages/questionnaire/notes/averageScore.scss
  questionnaire/src/components/pages/questionnaire/notes/note.scss
  questionnaire/src/components/pages/questionnaire/notes/notes.scss
  questionnaire/src/components/pages/questionnaire/notes/stars.scss
  questionnaire/src/components/pages/questionnaire/summary.scss
  questionnaire/src/components/pages/remerciements.scss
  questionnaire/src/components/questionnaire/GlobalError.jsx
  questionnaire/src/components/questionnaire/error-alert.scss
  questionnaire/src/components/questionnaire/globalError.scss
  questionnaire/src/index.js
  questionnaire/src/lib/getToken.js
Labels: ready

#410 Acitvate organisme account mailing
  backend/config/default.json
Labels: ready

#411 fix link display
  questionnaire/src/components/pages/Remerciements.jsx
Labels: ready

#412 Fix mailing stats with lookup pipeline
  backend/src/http/routes/stats.js
  backend/src/jobs/data/indexes/mongoIndexes.js
Labels: ready

#414 fix email read tracking
  backend/src/http/routes/front/mailing.js
Labels: ready

#415 Add nbCommentaires to CSV
  backend/src/http/routes/stats.js
Labels: ready

#416 Fix error box on note
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/questionnaire/notes/Stars.jsx
  questionnaire/src/components/pages/questionnaire/notes/notes.scss
Labels: ready

#417 fix comment text
  questionnaire/src/components/pages/Questionnaire.jsx
Labels: ready

#418 fix archiving
  backend/src/jobs/archive/archive.js
  backend/src/jobs/archive/index.js
Labels: ready

#409 Add documentation about API
  API.md
  README.md
  backend/src/http/routes/swagger.yml
  misc/specifications/kairos/api-kairos.svg
  misc/specifications/kairos/api-kairos.txt
Labels: master, ready

#424 Debounce checkBadwords calls
  backend/src/http/server.js
  questionnaire/src/components/pages/Questionnaire.jsx
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
Labels: master, ready

#425 Send job errors to Sentry
  backend/src/common/components/sentry.js
  backend/src/jobs/job-utils.js
Labels: master, ready

#426 Add requestId to each request and send it to Sentry
  backend/src/common/components/sentry.js
  backend/src/http/server.js
Labels: ready

#421 Refactor active regions to be the same as in region collection
  backend/config/default.json
  backend/src/common/components/regions.js
  backend/src/components.js
  backend/src/http/routes/stats.js
  backend/src/jobs/import/organismes/index.js
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/src/jobs/import/trainee/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/trainee/index.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/mailing/organismes/account/index.js
  backend/src/jobs/mailing/organismes/notifications/index.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
  backend/src/jobs/stats/buildOrganismesCSV.js
  backend/test/integration/http/routes/public/stats-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
  backend/test/integration/jobs/import/trainee/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/trainee/traineeImporter-test.js
  backend/test/integration/jobs/import/trainee/validateCsvFile-test.js
Labels: ready

#422 Round notes
  backend/src/http/routes/api/v1/dto/convertToExposableAction.js
  backend/src/http/routes/api/v1/dto/convertToExposableSession.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/import/organismes/computeOrganismesScore.js
  backend/src/jobs/import/sessions/generateActions.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/src/jobs/import/sessions/roundNotes.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/jobs/import/organismes/computeOrganismesScore-test.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
Labels: ready

#428 Fix pseudo validation
  backend/src/http/routes/front/questionnaire.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/front/questionnaire-test.js
Labels: master, ready

#429 Create one debouncer per field and flush it onBlur
  backend/test/integration/http/routes/front/mailing-test.js
  questionnaire/src/components/pages/questionnaire/commentaire/Commentaire.jsx
Labels: master, ready

#430 Remove departements and regions collections
  backend/config/default.json
  backend/src/common/components/regions.js
  backend/src/components.js
  backend/src/http/routes/api/kairos.js
  backend/src/http/routes/backoffice/financeur/financeur.js
  backend/src/http/routes/stats.js
  backend/src/jobs/data/dataset/createRegionalData.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/remove-departements.js
  backend/src/jobs/data/migration/remove-regions.js
  backend/src/jobs/import/organismes/generateOrganismesFromKairos.js
  backend/src/jobs/import/organismes/kairos/getCodeRegionFromKairosRegionName.js
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/src/jobs/import/sessions/addCodeRegion.js
  backend/src/jobs/import/sessions/generateActions.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/src/jobs/import/trainee/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/stats/buildOrganismesCSV.js
  backend/test/helpers/data/departements.json
  backend/test/helpers/data/regions.json
  backend/test/helpers/data/stagiaires-pe-invalid-departement.csv
  backend/test/helpers/test-database.js
  backend/test/helpers/test-server.js
  backend/test/integration/common/components/regions-test.js
  backend/test/integration/http/routes/backoffice/login-test.js
  backend/test/integration/http/routes/kairos-test.js
  backend/test/integration/http/routes/public/stats-test.js
  backend/test/integration/jobs/import/organismes/generateOrganismesFromIntercarif-test.js
  backend/test/integration/jobs/import/organismes/generateOrganismesFromKairos-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
  backend/test/integration/jobs/import/trainee/poleEmploiCSVHandler-test.js
  backend/test/integration/jobs/import/trainee/traineeImporter-test.js
  backend/test/integration/jobs/import/trainee/validateCsvFile-test.js
  backend/test/unit/regions-test.js
  backoffice/src/components/backoffice/financeur/service/financeurService.js
Labels: ready

#431 Fix link when organisme creates its account
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/organisation/AccountActivation.jsx
Labels: ready

#432 Add code_region during intercarif XML import
  backend/config/default.json
  backend/config/regions.json
  backend/src/common/components/regions.js
  backend/src/components.js
  backend/src/jobs/import/intercarif/importIntercarif.js
  backend/src/jobs/import/intercarif/index.js
  backend/src/jobs/import/intercarif/utils/getFormationsFromXml.js
  backend/src/jobs/import/sessions/addCodeRegion.js
  backend/src/jobs/import/sessions/generateActions.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/src/jobs/import/sessions/index.js
  backend/test/helpers/test-database.js
  backend/test/integration/http/routes/kairos-test.js
  backend/test/integration/jobs/import/intercarif/importIntercarif-test.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
  backend/test/unit/jobs/import/intercarif/getFormationsFromXml-test.js
Labels: ready

#434 Use ephemeralForTest MongoDB engine on Travis
  .travis.yml
  docker-compose.test.yml
Labels: ready

#433 Add organismes responsables into sessions and actions
  backend/src/http/routes/api/v1/dto/convertToExposableAvis.js
  backend/src/jobs/import/sessions/generateActions.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
Labels: ready
