Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-02, with the labels that each got.

#269 fix check profile for financeur
  backend/src/http/routes/backoffice/financer.js
Labels: ready

#268 Reorder migration scripts to prevent failure during merge
  backend/src/jobs/data/migration/index.js
Labels: ready

#265 Update reject email wording
  backend/src/http/routes/backoffice/avis-moderation.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/avis_injure.txt
  backend/test/integration/http/routes/backoffice/avis-moderation-test.js
  backoffice/src/components/backoffice/moderation/stagiaires/avis/components/buttons/RejectButton.jsx
  backoffice/src/lib/avisService.js
Labels: ready

#266 Update database connection retry system
  backend/src/common/components/database.js
Labels: ready

#267 Align middlewares component with other components
  backend/src/http/routes/api/v1/actions.js
  backend/src/http/routes/api/v1/avis.js
  backend/src/http/routes/api/v1/organismes-formateurs.js
  backend/src/http/routes/api/v1/ping.js
  backend/src/http/routes/api/v1/sessions.js
  backend/src/http/routes/backoffice/avis-moderation.js
  backend/src/http/routes/backoffice/avis-organismes.js
  backend/src/http/routes/backoffice/dashboard.js
  backend/src/http/routes/backoffice/editCourriel.js
  backend/src/http/routes/backoffice/export.js
  backend/src/http/routes/backoffice/financer.js
  backend/src/http/routes/backoffice/kairos.js
  backend/src/http/routes/backoffice/organisation.js
  backend/src/http/routes/backoffice/stats.js
  backend/src/http/server.js
Labels: ready

#270 fix bo financeur stats on email stats
  backend/src/jobs/stats/emails/emailStatsBuilder.js
Labels: ready

#271 BO financeur : remove feature filter on menu
  backoffice/src/components/backoffice/financer/SideMenu.js
Labels: ready

#272 Rename import organismes functions
  backend/src/jobs/import/organismes/computeOrganismesScore.js
  backend/src/jobs/import/organismes/generateOrganismes.js
  backend/src/jobs/import/organismes/generateOrganismesFromIntercarif.js
  backend/src/jobs/import/organismes/generateOrganismesFromKairos.js
  backend/src/jobs/import/organismes/index.js
  backend/src/jobs/import/organismes/intercarif/generateOrganismesFormateurs.js
  backend/src/jobs/import/organismes/intercarif/generateOrganismesResponsables.js
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/test/integration/jobs/import/organismes/computeOrganismesScore-test.js
  backend/test/integration/jobs/import/organismes/generateOrganismesFromIntercarif-test.js
  backend/test/integration/jobs/import/organismes/generateOrganismesFromKairos-test.js
  backend/test/integration/jobs/import/organismes/intercarif/generateOrganismesFormateurs-test.js
  backend/test/integration/jobs/import/organismes/intercarif/generateOrganismesResponsables-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
Labels: ready

#275 Refactor import sessions and actions to be reusable
  backend/src/http/routes/api/v1/dto/convertToExposableAction.js
  backend/src/http/routes/api/v1/dto/convertToExposableAvis.js
  backend/src/http/routes/api/v1/dto/convertToExposableSession.js
  backend/src/jobs/import/sessions/generateActions.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/src/jobs/import/sessions/index.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/public/actions-test.js
  backend/test/integration/http/routes/public/avis-test.js
  backend/test/integration/http/routes/public/sessions-test.js
  backend/test/integration/jobs/import/reconciliation/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
  backend/test/unit/utils/convertToExposableAvis-test.js
Labels: ready

#279 Fix stagiaires buttons
  backoffice/src/components/backoffice/moderation/stagiaires/StagiairesPanel.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/avis/components/buttons/RejectButton.jsx
Labels: ready

#278 fix bo financeur stats
  backend/src/jobs/stats/organisations/organisationStatsBuilder.js
Labels: ready

#277 Allow moderation actions to be reused
  backend/src/common/components/moderation.js
  backend/src/common/errors/index.js
  backend/src/components.js
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/src/http/routes/backoffice/avis-organismes.js
  backend/src/http/server.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
  backend/test/integration/http/routes/backoffice/avis-organismes-test.js
  backoffice/src/lib/avisService.js
Labels: ready

#280 Add script to generate dataset
  backend/package-lock.json
  backend/package.json
  backend/src/common/components/moderation.js
  backend/src/jobs/data/dataset/createAccounts.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/dataset/createRegionalData.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/job-utils.js
  backend/test/helpers/data/dataset.js
  backend/test/helpers/data/intercarif-data-test.xml
  backend/test/integration/jobs/import/intercarif/importIntercarif-test.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
Labels: ready

#281 Activate notification emails for Grand-Est
  backend/config/default.json
Labels: ready

#283 Remove nginx json output
  misc/nginx/app/nginx/nginx.conf
Labels: ready

#282 Allow commentaire to be injected using a CLI parameter
  backend/src/jobs/import/dataset/createAccounts.js
  backend/src/jobs/import/dataset/createAvis.js
  backend/src/jobs/import/dataset/createRegionalData.js
  backend/src/jobs/import/dataset/index.js
Labels: ready

#285 polish CSS + half stars + fix note moyenne display
  questionnaire/src/components/ChampCommentaire.scss
  questionnaire/src/components/Commentaire.jsx
  questionnaire/src/components/Commentaire.scss
  questionnaire/src/components/Header.jsx
  questionnaire/src/components/NoteMoyenne.jsx
  questionnaire/src/components/NoteMoyenne.scss
  questionnaire/src/components/Notes.jsx
  questionnaire/src/components/Stars.jsx
  questionnaire/src/components/footer.scss
  questionnaire/src/components/note.scss
  questionnaire/src/components/stars.scss
Labels: ready

#288 Fix resend email to organisme
  backend/src/http/routes/backoffice/editCourriel.js
Labels: ready

#289 Add carif into dataset regional data
  backend/src/jobs/import/dataset/createRegionalData.js
Labels: ready

#287 Add reject reason in status
  backoffice/src/components/backoffice/moderation/stagiaires/StagiairesPanel.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/avis/components/Stagiaire.jsx
Labels: ready

#284 Fix missing profile when during organisme sync
  README.md
  backend/src/jobs/data/dataset/createAccounts.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/dataset/createRegionalData.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/reset-passwords/index.js
  backend/src/jobs/data/reset-passwords/resetPasswords.js
  backend/src/jobs/data/utils/reset-passwords.js
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
Labels: ready

#290 Stats backoffice financeur
  backend/src/http/routes/backoffice/stats.js
  backoffice/src/components/backoffice/financer/stats/Dashboard.js
  backoffice/src/components/backoffice/financer/stats/Graph.js
  backoffice/src/components/backoffice/financer/stats/Table.js
Labels: ready

#292 fix export when selecting an organisation
  backend/src/http/routes/backoffice/export.js
Labels: ready

#293 fix URI
  questionnaire/package.json
Labels: ready

#294 Search stagiaire instead of avis
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/src/http/routes/backoffice/utils/AvisSearchBuilder.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
  backoffice/src/components/backoffice/moderation/ModerationRoutes.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/Summary.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/Summary.scss
  backoffice/src/components/backoffice/moderation/stagiaires/Toolbar.jsx
  backoffice/src/lib/avisService.js
Labels: ready

#295 Regroup mask title and pseudo routes
  backend/src/common/components/moderation.js
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
  backoffice/src/components/backoffice/moderation/stagiaires/avis/components/Stagiaire.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/avis/components/Titre.jsx
  backoffice/src/lib/avisService.js
Labels: ready

#297 Fix action reconciliation
  backend/src/jobs/import/sessions/generateActions.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
Labels: ready

#298 New trainee form : fold button + enabling send button only if 5 notes are selected
  questionnaire/src/App.js
  questionnaire/src/components/Commentaire.jsx
  questionnaire/src/components/FoldButton.jsx
  questionnaire/src/components/NoteMoyenne.jsx
  questionnaire/src/components/NoteMoyenne.scss
  questionnaire/src/components/Notes.jsx
  questionnaire/src/components/SendButton.jsx
  questionnaire/src/components/SendButton.scss
  questionnaire/src/components/Stars.jsx
  questionnaire/src/components/commentaire.scss
  questionnaire/src/components/foldButton.scss
  questionnaire/src/components/notes.scss
Labels: ready

#301 Add script to generate dump dataset
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/dataset/dumpAvis.js
  backend/src/jobs/data/dataset/index.js
Labels: bug, ready

#303 Fix pagination and search on BO Moderation
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
  backoffice/src/components/backoffice/moderation/stagiaires/StagiairesPanel.jsx
Labels: ready

#300 Rollback nginx to stdout
  misc/nginx/app/nginx/nginx.conf
Labels: bug, ready

#302 Fix missing profile for organismes
  backend/src/http/routes/backoffice/kairos.js
  backend/src/jobs/import/organismes/synchronizeOrganismesWithAccounts.js
  backend/test/integration/http/routes/kairos-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
Labels: ready

#305 Sort dumped avis by date
  backend/src/jobs/data/dataset/dumpAvis.js
Labels: ready

#304 add confirmation modal with summary
  questionnaire/package-lock.json
  questionnaire/package.json
  questionnaire/public/index.html
  questionnaire/src/App.js
  questionnaire/src/App.scss
  questionnaire/src/components/ChampCommentaire.jsx
  questionnaire/src/components/Commentaire.jsx
  questionnaire/src/components/NoteMoyenne.jsx
  questionnaire/src/components/NoteMoyenne.scss
  questionnaire/src/components/Notes.jsx
  questionnaire/src/components/SummaryModal.jsx
  questionnaire/src/components/common/AverageScore.jsx
  questionnaire/src/components/common/FoldButton.jsx
  questionnaire/src/components/common/Note.jsx
  questionnaire/src/components/common/SendButton.jsx
  questionnaire/src/components/common/Stars.jsx
  questionnaire/src/components/common/averageScore.scss
  questionnaire/src/components/common/foldButton.scss
  questionnaire/src/components/common/note.scss
  questionnaire/src/components/common/sendButton.scss
  questionnaire/src/components/common/stars.scss
  questionnaire/src/components/notes.scss
  questionnaire/src/components/summaryModal.scss
  questionnaire/src/data.json
  questionnaire/src/index.js
Labels: ready

#309 Fix moderation filter
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
Labels: ready

#308 some CSS polish + hide/show animation when are every notes are selected
  questionnaire/public/index.html
  questionnaire/src/App.js
  questionnaire/src/components/Autorisations.jsx
  questionnaire/src/components/Autorisations.scss
  questionnaire/src/components/ChampCommentaire.scss
  questionnaire/src/components/Commentaire.jsx
  questionnaire/src/components/NoteMoyenne.scss
  questionnaire/src/components/Notes.jsx
  questionnaire/src/components/commentaire.scss
  questionnaire/src/components/common/FoldButton.jsx
  questionnaire/src/components/common/foldButton.scss
  questionnaire/src/components/common/sendButton.scss
  questionnaire/src/components/notes.scss
Labels: ready

#310 add google analytics + hotjar on backoffice
  backoffice/public/index.html
Labels: ready

#311 branching questionnaire to backend
  backend/src/http/routes/front/questionnaire.js
  backend/src/http/server.js
  questionnaire/package-lock.json
  questionnaire/package.json
  questionnaire/src/App.js
  questionnaire/src/App.jsx
  questionnaire/src/App.scss
  questionnaire/src/components/ErrorPanel.jsx
  questionnaire/src/components/Header.jsx
  questionnaire/src/components/NoMatch.jsx
  questionnaire/src/components/Questionnaire.jsx
  questionnaire/src/components/header.scss
  questionnaire/src/components/noMatch.scss
  questionnaire/src/components/questionnaire.scss
  questionnaire/src/lib/traineeService.js
  questionnaire/src/utils/http-client.js
  questionnaire/src/utils/token.js
Labels: ready

#306 Replace winston by bunyan and log http requests
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/common/components/logger.js
  backend/src/common/components/sentry.js
  backend/src/components.js
  backend/src/http/middlewares.js
  backend/src/http/server.js
  backend/src/jobs/job-utils.js
  backend/test/helpers/test-logger.js
Labels: master, ready

#313 Omit password and acces_token in logs
  backend/src/http/server.js
Labels: master, ready

#314 Fix actions score
  backend/src/jobs/import/sessions/generateActions.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
  backend/test/integration/jobs/import/sessions/generateSessions-test.js
Labels: bug, master, ready

#316 Reset migrations scripts
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/merge-account.js
  backend/src/jobs/data/migration/rename-password-to-passwordHash.js
Labels: ready

#318 Fix message in OrganismePanel
  backoffice/src/components/backoffice/moderation/organismes/OrganismePanel.jsx
Labels: bug, master, ready

#317 Fix login organisme when account has not been created
  backend/src/http/routes/backoffice/login.js
  backend/test/integration/http/routes/backoffice/login-test.js
Labels: bug, ready

#315 Moderation des réponses des organismes
  backend/src/common/components/moderation.js
  backend/src/common/errors.js
  backend/src/common/validators.js
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/src/http/routes/backoffice/avis-organismes.js
  backend/src/http/routes/backoffice/utils/computeInventory.js
  backend/src/http/routes/backoffice/utils/moderationStats.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
  backend/test/integration/http/routes/backoffice/avis-organismes-test.js
  backoffice/public/index.html
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Pagination.jsx
  backoffice/src/components/backoffice/common/Panel.jsx
  backoffice/src/components/backoffice/common/Panel.scss
  backoffice/src/components/backoffice/moderation/ModerationRoutes.jsx
  backoffice/src/components/backoffice/moderation/common/SearchInputTab.jsx
  backoffice/src/components/backoffice/moderation/common/ToolbarTab.jsx
  backoffice/src/components/backoffice/moderation/common/ToolbarTab.scss
  backoffice/src/components/backoffice/moderation/common/results/AvisResults.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Commentaire.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Commentaire.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/Edition.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Edition.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/Notes.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Notes.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/Organisme.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Organisme.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/Reponse.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Reponse.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Stagiaire.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/Titre.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Titre.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/EditButton.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/PublishButton.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/PublishReponseButton.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/RejectButton.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/RejectReponseButton.scss
  backoffice/src/components/backoffice/moderation/common/results/avis/index.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/index.scss
  backoffice/src/components/backoffice/moderation/common/results/summary/AvisResultsSummary.jsx
  backoffice/src/components/backoffice/moderation/common/results/summary/AvisResultsSummary.scss
  backoffice/src/components/backoffice/moderation/common/results/summary/ReponseResultsSummary.jsx
  backoffice/src/components/backoffice/moderation/panels/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderation/panels/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderation/panels/organismes/OrganismeCard.jsx
  backoffice/src/components/backoffice/moderation/panels/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/StagiairesPanel.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/Toolbar.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/avis/Avis.jsx
  backoffice/src/components/backoffice/moderation/stagiaires/avis/Avis.scss
  backoffice/src/lib/avisService.js
  backoffice/src/styles/variables.scss
Labels: ready

#312 New form: submit advice
  backend/src/common/errors.js
  backend/src/http/public/css/front/home.css
  backend/src/http/public/img/labonneformation.jpg
  backend/src/http/public/img/labonneformation.png
  backend/src/http/public/img/lbf.jpg
  backend/src/http/public/img/lbf.png
  backend/src/http/routes/front/questionnaire.js
  backend/src/http/views/front/homepage.ejs
  backend/src/http/views/front/questionnaire-step3.ejs
  questionnaire/src/App.jsx
  questionnaire/src/App.scss
  questionnaire/src/components/Autorisations.jsx
  questionnaire/src/components/ChampCommentaire.jsx
  questionnaire/src/components/ChampCommentaire.scss
  questionnaire/src/components/Commentaire.jsx
  questionnaire/src/components/ErrorAlert.jsx
  questionnaire/src/components/ErrorPanel.jsx
  questionnaire/src/components/Header.jsx
  questionnaire/src/components/PanelRemerciements.jsx
  questionnaire/src/components/Questionnaire.jsx
  questionnaire/src/components/Remerciements.jsx
  questionnaire/src/components/SummaryModal.jsx
  questionnaire/src/components/commentaire.scss
  questionnaire/src/components/common/AverageScore.jsx
  questionnaire/src/components/error-alert.scss
  questionnaire/src/components/errorPanel.scss
  questionnaire/src/components/footer.scss
  questionnaire/src/components/noMatch.scss
  questionnaire/src/components/panelRemerciements.scss
  questionnaire/src/components/remerciements.scss
  questionnaire/src/components/summaryModal.scss
  questionnaire/src/lib/stagiaireService.js
  questionnaire/src/lib/traineeService.js
Labels: ready

#319 Rename answer to reponse and lastModerationAction into lastStatusUpdate
  backend/src/common/components/moderation.js
  backend/src/http/routes/api/v1/dto/convertToExposableAvis.js
  backend/src/http/routes/backoffice/avis-moderateur.js
  backend/src/http/routes/backoffice/avis-organismes.js
  backend/src/http/routes/backoffice/organisation.js
  backend/src/http/routes/backoffice/utils/moderationStats.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/dataset/dumpAvis.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/remove-old-accounts.js
  backend/src/jobs/data/migration/rename-answer.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/backoffice/avis-moderateur-test.js
  backend/test/integration/http/routes/backoffice/avis-organismes-test.js
  backend/test/unit/utils/convertToExposableAvis-test.js
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/moderation/ModerationRoutes.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Reponse.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/moderation/common/results/avis/index.jsx
  backoffice/src/components/backoffice/moderation/panels/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderation/panels/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/organisation/OrganisationPanel.js
  backoffice/src/lib/avisService.js
Labels: ready

#322 Fix forgotten password and sentry
  backend/src/common/components/mailing/sendForgottenPasswordEmail.js
  backend/src/http/routes/backoffice/forgottenPassword.js
  backend/src/http/server.js
Labels: bug, master, ready

#323 Fix sentry
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/common/components/sentry.js
Labels: bug, master, ready

#325 Add stack to log
  backend/src/http/server.js
Labels: master, ready

#324 Add route to search organismes
  backend/src/http/routes/backoffice/moderateur/gestion-organismes.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
Labels: ready

#328 Reorder moderation panels
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/moderateur/ModerationRoutes.jsx
  backoffice/src/components/backoffice/moderateur/common/SearchInputTab.jsx
  backoffice/src/components/backoffice/moderateur/common/ToolbarTab.jsx
  backoffice/src/components/backoffice/moderateur/common/ToolbarTab.scss
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/AvisResults.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Commentaire.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Commentaire.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Edition.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Notes.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Notes.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Organisme.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Reponse.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Reponse.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Stagiaire.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Titre.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/Titre.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/EditButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/PublishButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/PublishReponseButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/RejectButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/buttons/RejectReponseButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/index.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/avis/index.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/summary/AvisResultsSummary.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/summary/AvisResultsSummary.scss
  backoffice/src/components/backoffice/moderateur/moderation/common/summary/ReponseResultsSummary.jsx
  backoffice/src/components/backoffice/moderateur/organismes/OrganismeCard.jsx
  backoffice/src/components/backoffice/moderateur/organismes/OrganismePanelDeprecated.jsx
  backoffice/src/components/backoffice/moderateur/service/gestionOrganismesService.js
  backoffice/src/components/backoffice/moderateur/service/moderationService.js
Labels: ready

#332 Ouverture du service à la Corse
  backend/config/default.json
  backend/src/http/public/img/regions/logo-email/logo_6.png
  backend/src/jobs/auth/prepareNewAccounts.js
  backend/src/jobs/job-utils.js
Labels: master, ready

#326 Remove legacy trainee form
  backend/package-lock.json
  backend/src/http/public/bootstrap/css/bootstrap-theme.css
  backend/src/http/public/bootstrap/css/bootstrap-theme.css.map
  backend/src/http/public/bootstrap/css/bootstrap-theme.min.css
  backend/src/http/public/bootstrap/css/bootstrap-theme.min.css.map
  backend/src/http/public/bootstrap/css/bootstrap.css
  backend/src/http/public/bootstrap/css/bootstrap.css.map
  backend/src/http/public/bootstrap/css/bootstrap.min.css
  backend/src/http/public/bootstrap/css/bootstrap.min.css.map
  backend/src/http/public/bootstrap/fonts/glyphicons-halflings-regular.eot
  backend/src/http/public/bootstrap/fonts/glyphicons-halflings-regular.svg
  backend/src/http/public/bootstrap/fonts/glyphicons-halflings-regular.ttf
  backend/src/http/public/bootstrap/fonts/glyphicons-halflings-regular.woff
  backend/src/http/public/bootstrap/fonts/glyphicons-halflings-regular.woff2
  backend/src/http/public/bootstrap/jquery.js
  backend/src/http/public/bootstrap/js/bootstrap.js
  backend/src/http/public/bootstrap/js/bootstrap.min.js
  backend/src/http/public/bootstrap/js/jquery.js
  backend/src/http/public/bootstrap/js/npm.js
  backend/src/http/public/css/front/errors.css
  backend/src/http/public/css/front/noteo.css
  backend/src/http/public/script/indexForm.js
  backend/src/http/public/script/jquery.js
  backend/src/http/routes/front/front.js
  backend/src/http/views/errors/401.ejs
  backend/src/http/views/errors/403.ejs
  backend/src/http/views/errors/404.ejs
  backend/src/http/views/errors/error.ejs
  backend/src/http/views/front/questionnaire-step1.ejs
  backend/src/http/views/front/questionnaire-step2.ejs
  backend/src/http/views/front/questionnaire-step3.ejs
  backend/src/http/views/front/refus.ejs
  backend/test/integration/http/routes/front/front-test.js
  misc/nginx/app/nginx/conf.d/locations.inc
  questionnaire/package.json
Labels: ready

#331 Add gestion des organismes
  backend/src/http/routes/backoffice/moderateur/gestion-organismes.js
  backend/src/http/routes/backoffice/moderateur/utils/convertOrganismeToDTO.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
  backoffice/src/components/backoffice/common/Panel.scss
  backoffice/src/components/backoffice/moderateur/ModerationRoutes.jsx
  backoffice/src/components/backoffice/moderateur/common/SearchInputTab.jsx
  backoffice/src/components/backoffice/moderateur/moderation/common/AvisResults.jsx
  backoffice/src/components/backoffice/moderateur/organismes/OrganismeCard.jsx
  backoffice/src/components/backoffice/moderateur/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/organismes/OrganismePanelDeprecated.jsx
  backoffice/src/components/backoffice/moderateur/organismes/OrganismeResults.jsx
  backoffice/src/components/backoffice/moderateur/organismes/components/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/organismes/components/EditButton.scss
  backoffice/src/components/backoffice/moderateur/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/organismes/components/Edition.scss
  backoffice/src/components/backoffice/moderateur/organismes/components/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/organismes/components/Organisme.scss
  backoffice/src/components/backoffice/moderateur/service/gestionOrganismesService.js
Labels: ready

#334 Enhance HTTP request logs
  backend/src/http/server.js
Labels: master, ready

#339 Enhance http logs again
  backend/src/http/server.js
Labels: master, ready

#327 Removing useless step filter on mongodb queries
  backend/src/http/routes/api/v1/avis.js
  backend/src/http/routes/backoffice/export.js
  backend/src/http/routes/backoffice/financeur/financeur.js
  backend/src/http/routes/backoffice/moderateur/moderation.js
  backend/src/http/routes/backoffice/moderateur/utils/moderationStats.js
  backend/src/http/routes/backoffice/organismes/organisme.js
  backend/src/http/routes/stats.js
  backend/src/jobs/data/dataset/createAvis.js
  backend/src/jobs/data/indexes/mongoIndexes.js
  backend/src/jobs/import/organismes/computeOrganismesScore.js
  backend/src/jobs/import/sessions/generateSessions.js
  backend/src/jobs/stats/emails/emailStatsBuilder.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/public/avis-test.js
Labels: ready

#336 calculate rate average
  backend/src/http/routes/front/questionnaire.js
Labels: ready

#335 data migration : remove step
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/remove-comment-step.js
  backend/src/jobs/data/stats.js
Labels: ready

#340 Add Moderatoin menu in Header
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Header.scss
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/gestion/gestionOrganismesService.js
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.scss
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.scss
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.scss
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.scss
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Titre.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/moderationService.js
Labels: ready

#338 Allow OF to add their answer on notes.
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
Labels: ready

#343 Fix region on the Bo financeur header
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/common/deprecated/DeprecatedHeader.jsx
  backoffice/src/components/backoffice/constantes/financeurs.js
  backoffice/src/components/backoffice/constantes/regions.js
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
Labels: ready

#344 Rework all buttons according to invision
  backoffice/src/App.jsx
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Button.jsx
  backoffice/src/components/backoffice/common/Button.scss
  backoffice/src/components/backoffice/common/Dropdown.jsx
  backoffice/src/components/backoffice/common/Dropdown.scss
  backoffice/src/components/backoffice/common/Message.scss
  backoffice/src/components/backoffice/common/Modal.jsx
  backoffice/src/components/backoffice/common/Modal.scss
  backoffice/src/components/backoffice/common/panel/Pagination.jsx
  backoffice/src/components/backoffice/misc/LibraryPanel.jsx
  backoffice/src/components/backoffice/misc/LibraryPanel.scss
  backoffice/src/components/backoffice/misc/MiscRoutes.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.scss
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/EditButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishReponseButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectReponseButton.scss
  backoffice/src/styles/button-mixins.scss
  backoffice/src/styles/buttons-mixins.scss
  backoffice/src/styles/dropdown-mixins.scss
  backoffice/src/styles/variables.scss
Labels: ready

#345 delete and optimise duplicate code.
  backoffice/src/App.jsx
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#346 Fix dropdown onClick and alignements
  backoffice/src/components/backoffice/common/Dropdown.jsx
  backoffice/src/components/backoffice/common/Dropdown.scss
  backoffice/src/components/backoffice/common/Modal.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
Labels: ready

#347 Replace message with new UI
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Button.jsx
  backoffice/src/components/backoffice/common/Button.scss
  backoffice/src/components/backoffice/common/Message.jsx
  backoffice/src/components/backoffice/common/Message.scss
  backoffice/src/components/backoffice/common/Modal.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/AvisResults.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Notes.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Stagiaire.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Titre.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
  backoffice/src/styles/buttons-mixins.scss
Labels: ready

#349 Fix exit code during job execution
  backend/src/jobs/job-utils.js
Labels: bug, master, ready

#348 Move mixins into React components
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Button.scss
  backoffice/src/components/backoffice/common/Dropdown.scss
  backoffice/src/components/backoffice/common/Message.scss
  backoffice/src/components/backoffice/common/Modal.scss
  backoffice/src/styles/buttons-mixins.scss
  backoffice/src/styles/dropdown-mixins.scss
Labels: ready

#350 Replace 'Details' button with new button component
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Button.scss
  backoffice/src/components/backoffice/misc/LibraryPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Notes.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Notes.scss
Labels: ready

#351 Align divider with offset
  backoffice/src/components/backoffice/common/Button.scss
  backoffice/src/components/backoffice/common/Message.scss
  backoffice/src/components/backoffice/common/panel/ResultDivider.jsx
  backoffice/src/components/backoffice/common/panel/ResultDivider.scss
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.scss
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.scss
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
Labels: ready

#352 Split message into global and local message
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Message.jsx
  backoffice/src/components/backoffice/common/message/Alert.jsx
  backoffice/src/components/backoffice/common/message/Alert.scss
  backoffice/src/components/backoffice/common/message/GlobalMessage.jsx
  backoffice/src/components/backoffice/common/message/GlobalMessage.scss
  backoffice/src/components/backoffice/common/message/LocalMessage.jsx
  backoffice/src/components/backoffice/common/message/LocalMessage.scss
  backoffice/src/components/backoffice/common/panel/Panel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisReponsesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Avis.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/PublishReponseButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectReponseButton.jsx
Labels: ready

#353 Filter organismes by status
  backend/src/http/routes/backoffice/moderateur/gestion-organismes.js
  backend/src/http/routes/backoffice/moderateur/utils/convertOrganismeToDTO.js
  backend/test/integration/http/routes/backoffice/gestion-organismes-test.js
  backoffice/src/App.scss
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/OrganismePanel.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/EditButton.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.jsx
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Organisme.scss
Labels: ready

#354 Prevent computeScore to be skipped when import fails
  backend/src/jobs/import/organismes/index.js
Labels: bug, master, ready

#355 Add qualification column for PE.
  backend/src/http/routes/backoffice/export.js
  backoffice/src/components/backoffice/common/deprecated/AdviceRates.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#356 Fix nb_avis in actions
  backend/src/jobs/import/sessions/generateActions.js
  backend/test/integration/jobs/import/sessions/generateActions-test.js
Labels: bug, master, ready
