Repository StartupsPoleEmploi/anotea, pull requests merged in 2019-07, with the labels that each got.

#655 Replace Header column positioning strategy by flex
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Header.scss
Labels: ready

#667 remove values < 10% from pie chart
  backoffice/src/components/backoffice/organisation/Graphes.js
Labels: ready

#661 Fix form submit and move contact-stagiaires export
  backend/src/common/utils/stream-utils.js
  backend/src/http/routes/api/backoffice/moderateur/gestion-organismes-routes.js
  backend/src/http/routes/api/contact-stagiaires-routes.js
  backend/src/http/routes/api/contactStagiaires-routes.js
  backend/src/http/routes/api/export-routes.js
  backend/src/http/routes/api/exports-routes.js
  backend/src/http/routes/routes-utils.js
  backend/src/http/server.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/job-utils.js
  backend/test/integration/http/routes/api/contactStagiaires-routes-test.js
  widget/src/components/common/ContactStagiaire.jsx
  widget/src/components/common/ContactStagiaire.scss
  widget/src/services/widgetService.js
Labels: ready

#670 hide label on pie charts
  backoffice/src/components/backoffice/organisation/Graphes.js
Labels: ready

#668 Clean patch code
  backend/src/jobs/patch/stagiaires/tasks/patchOrganismeResponsable.js
Labels: ready

#669 update hover's text
  stats/src/components/stats/ApiStatsTable.jsx
  stats/src/components/stats/OrganismesStatsTable.jsx
Labels: ready

#674 Revert "Deactivate sendReponseRejeteeNotification"
  backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js
  backend/test/integration/http/routes/api/backoffice/moderation-routes-test.js
Labels: ready

#659 change wording for notification email : reponse rejected
  backend/src/common/components/mailing/sendReponseRejeteeNotification.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
Labels: ready

#657 Mail template stagiaire
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#675 Send emails to organismes for all active regions
  backend/config/regions.json
Labels: master, ready

#678 Template reponse rejetee
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
Labels: ready

#680 wording + template questionnaire stagiaire
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#682 Move kairos import into a dedicated script
  backend/src/http/routes/api/kairos-routes.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/import/kairos/index.js
  backend/src/jobs/import/kairos/tasks/importKairosCSV.js
  backend/src/jobs/import/kairos/tasks/utils/getCodeRegionFromKairosRegionName.js
  backend/src/jobs/import/organismes/index.js
  backend/src/jobs/import/organismes/tasks/computeScore.js
  backend/src/jobs/import/organismes/tasks/generateOrganismesFromIntercarif.js
  backend/src/jobs/import/organismes/tasks/intercarif/generateOrganismesFormateurs.js
  backend/src/jobs/import/organismes/tasks/intercarif/generateOrganismesResponsables.js
  backend/src/jobs/import/organismes/tasks/synchronizeOrganismesWithAccounts.js
  backend/test/integration/jobs/import/kairos/importKairosCSV-test.js
  backend/test/integration/jobs/import/organismes/computeScore-test.js
  backend/test/integration/jobs/import/organismes/generateOrganismesFromIntercarif-test.js
  backend/test/integration/jobs/import/organismes/intercarif/generateOrganismesFormateurs-test.js
  backend/test/integration/jobs/import/organismes/intercarif/generateOrganismesResponsables-test.js
  backend/test/integration/jobs/import/organismes/synchronizeOrganismesWithAccounts-test.js
Labels: ready

#677 stats in mailing.csv to be integrated into stats project
  backend/src/jobs/stats/public/index.js
  backend/src/jobs/stats/public/tasks/computeCampaignStats.js
  stats/src/components/stats/AvisStatsTable.jsx
  stats/src/components/stats/StatsRoutes.jsx
  stats/src/components/stats/StatsTable.scss
Labels: ready

#683 Allow csv stream util to be reused
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/job-utils.js
Labels: ready

#681 Anonymous training title
  backend/package-lock.json
  backend/package.json
  backend/src/jobs/patch/anonymous/index.js
  backend/src/jobs/patch/anonymous/tasks/doAnonymization.js
  backend/src/jobs/patch/anonymous/tasks/export.js
  backend/src/jobs/patch/anonymous/utils.js
  backend/test/unit/jobs/patch/anonymous/utils-test.js
Labels: ready

#688 fix event logging for advice report
  backend/src/common/components/moderation.js
Labels: ready

#687 Use docker-compose v2.4
  docker-compose.override.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: ready

#685 Use kairos csv file during import instead of kairos collection
  backend/src/common/utils/stream-utils.js
  backend/src/http/routes/api/kairos-routes.js
  backend/src/jobs/data/migration/tasks/dropCollections.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/import/kairos/index.js
  backend/src/jobs/import/kairos/tasks/importKairosCSV.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/organismes/index.js
  backend/src/jobs/organismes/tasks/kairos/getCodeRegionFromKairosRegionName.js
  backend/src/jobs/organismes/tasks/kairos/getOrganismesFromKairosCSV.js
  backend/src/jobs/organismes/tasks/synchronizeAccountsWithKairos.js
  backend/test/helpers/data/kairos-organismes-invalid.csv
  backend/test/integration/jobs/import/kairos/importKairosCSV-test.js
  backend/test/integration/jobs/organismes/synchronizeAccountsWithKairos-test.js
Labels: ready

#691 Fix findRegionByCodeINSEE for Mayotte
  backend/src/common/components/regions.js
  backend/src/jobs/organismes/index.js
  backend/src/jobs/organismes/tasks/synchronizeAccountsWithIntercarif.js
  backend/test/integration/jobs/organismes/synchronizeAccountsWithIntercarif-test.js
  backend/test/integration/jobs/organismes/synchronizeAccountsWithKairos-test.js
  backend/test/unit/regions-test.js
Labels: ready

#686 should not modify numero bon de commande
  backend/src/jobs/patch/anonymous/utils.js
  backend/test/unit/jobs/patch/anonymous/utils-test.js
Labels: ready

#689 do not allow to report advice without comment
  backoffice/src/components/backoffice/organisation/OrganisationPanel.jsx
Labels: ready

#694 fix id regex + more unit test + fix export
  backend/src/jobs/patch/anonymous/tasks/export.js
  backend/src/jobs/patch/anonymous/utils.js
  backend/test/unit/jobs/patch/anonymous/utils-test.js
Labels: ready

#690 in BO financeur, add a link to access to public stats
  backoffice/src/components/backoffice/common/deprecated/DeprecatedHeader.jsx
  backoffice/src/components/backoffice/common/deprecated/header.css
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
Labels: ready

#696 Lbf logo
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#697 wording questionnaire stagiaire
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#698 typo
  backend/src/http/views/front/mailing/votre_avis.ejs
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#706 Fix contact stagiaire popup
  widget/src/components/common/library/Modal.scss
Labels: ready

#679 [RECONCILIATION-1] Boost performance
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropCollections.js
  backend/src/jobs/data/migration/tasks/unsetReconciliations.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/organismes/tasks/computeScore.js
  backend/src/jobs/organismes/tasks/synchronizeAccountsWithKairos.js
  backend/src/jobs/reconciliation/index.js
  backend/src/jobs/reconciliation/tasks/addReconciliationAvisMetadata.js
  backend/src/jobs/reconciliation/tasks/reconcile.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildAction.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildFormation.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildSession.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileActions.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileFormation.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileSessions.js
  backend/src/jobs/reconciliation/tasks/reconcile/utils/findAvisReconciliables.js
  backend/src/jobs/reconciliation/tasks/reconcile/utils/getReconcilatedAvis.js
  backend/src/jobs/reconciliation/tasks/utils/createReporter.js
  backend/src/jobs/stats/public/tasks/computeApiStats.js
  backend/test/helpers/data/dataset.js
  backend/test/helpers/data/intercarif-data-test.xml
  backend/test/integration/jobs/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
  backend/test/integration/jobs/reconciliation/removePreviousImports-test.js
Labels: ready

#707 [RECONCILIATION-2] Ajout de la reconciliation par ville
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
Labels: ready

#711 Remove width limitation on widget tooltip
  widget/src/components/common/Tooltip.scss
Labels: ready

#710 Add memory limits into docker-compose
  docker-compose.override.yml
  docker-compose.yml
Labels: ready

#716 fix statistiques bouton to open new tab
  backoffice/src/components/backoffice/common/deprecated/DeprecatedHeader.jsx
Labels: ready

#715 Extract logrotation from container
  misc/nginx/Dockerfile
  misc/nginx/app/logrotate.d/cron.daily/logrotate
Labels: master, ready

#712 Change resize widget strategy
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
Labels: master, ready

#714 Clean contact stagiaires data
  backend/src/http/routes/api/exports-routes.js
Labels: master, ready

#713 Wrap reponse into an object (API)
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/routes/api/swagger.yml
  backend/test/unit/utils/convertCommentToAvis-test.js
Labels: ready

#709 Remove organisme reponsable patch
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/rollbackOrganismeResponsablePatch.js
  backend/src/jobs/patch/stagiaires/index.js
  backend/src/jobs/patch/stagiaires/tasks/patchOrganismeResponsable.js
  backend/src/jobs/patch/stagiaires/tasks/utils/getOrganismesResponsables.js
  backend/test/integration/jobs/patch/patchOrganismeResponsable-test.js
Labels: ready

#718 Mise en production
  backend/src/common/utils/convertCommentToAvis.js
  backend/src/http/public/static/js/widget/anotea-widget-loader.js
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backend/src/http/routes/api/exports-routes.js
  backend/src/http/routes/api/swagger.yml
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropCollections.js
  backend/src/jobs/data/migration/tasks/rollbackOrganismeResponsablePatch.js
  backend/src/jobs/data/migration/tasks/unsetReconciliations.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/organismes/tasks/computeScore.js
  backend/src/jobs/organismes/tasks/synchronizeAccountsWithKairos.js
  backend/src/jobs/patch/stagiaires/index.js
  backend/src/jobs/patch/stagiaires/tasks/patchOrganismeResponsable.js
  backend/src/jobs/patch/stagiaires/tasks/utils/getOrganismesResponsables.js
  backend/src/jobs/reconciliation/index.js
  backend/src/jobs/reconciliation/tasks/addReconciliationAvisMetadata.js
  backend/src/jobs/reconciliation/tasks/reconcile.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildAction.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildFormation.js
  backend/src/jobs/reconciliation/tasks/reconcile/buildSession.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileActions.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileFormation.js
  backend/src/jobs/reconciliation/tasks/reconcile/reconcileSessions.js
  backend/src/jobs/reconciliation/tasks/reconcile/utils/findAvisReconciliables.js
  backend/src/jobs/reconciliation/tasks/reconcile/utils/getReconcilatedAvis.js
  backend/src/jobs/reconciliation/tasks/utils/createReporter.js
  backend/src/jobs/stats/public/tasks/computeApiStats.js
  backend/test/helpers/data/dataset.js
  backend/test/helpers/data/intercarif-data-test.xml
  backend/test/integration/jobs/patch/patchOrganismeResponsable-test.js
  backend/test/integration/jobs/reconciliation/addReconciliationAvisMetadata-test.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
  backend/test/integration/jobs/reconciliation/removePreviousImports-test.js
  backend/test/unit/utils/convertCommentToAvis-test.js
  backoffice/src/components/backoffice/common/deprecated/DeprecatedHeader.jsx
  docker-compose.override.yml
  docker-compose.yml
  misc/nginx/Dockerfile
  misc/nginx/app/logrotate.d/cron.daily/logrotate
  widget/src/components/common/Tooltip.scss
Labels: master, ready

#720 Set backend docker container memory to 1gb
  docker-compose.yml
Labels: ready

#717 Create a datalake log exporter
  backend/config/custom-environment-variables.json
  backend/config/default.json
  backend/package-lock.json
  backend/package.json
  backend/src/http/middlewares/middlewares.js
  backend/src/http/middlewares/utils/createDatalakeExporter.js
  backend/src/http/middlewares/utils/createResponseRecorder.js
  backend/src/http/routes/api/v1/ping-routes.js
  backend/src/http/server.js
  backend/src/jobs/data/auth/generateHMACAuthorizationHeader.js
  backend/src/jobs/data/auth/utils/buildHMACSignature.js
  backend/test/helpers/test-components.js
  backend/test/helpers/test-database.js
  backend/test/helpers/test-server.js
  backend/test/integration/http/routes/api/v1/datalake-exporter-test.js
  backend/test/integration/http/routes/api/v1/ping-routes-test.js
Labels: ready

#721 Prevent contact stagiaire double submit
  backoffice/src/components/backoffice/common/library/Modal.jsx
  questionnaire/src/components/common/library/Modal.jsx
  widget/src/components/common/ContactStagiaire.jsx
  widget/src/components/common/library/Modal.jsx
Labels: master, ready

#724 update mail template + wording
  backend/src/components.js
  backend/src/http/routes/api/backoffice/moderateur/moderation-routes.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/avis_injure.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisation_password.txt
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_avis_non_lus.txt
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/password_forgotten.txt
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
Labels: ready

#723 Remove previous migration scripts
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropCollections.js
  backend/src/jobs/data/migration/tasks/rollbackOrganismeResponsablePatch.js
  backend/src/jobs/data/migration/tasks/unsetReconciliations.js
Labels: ready

#722 Remove non longer used reporter
  backend/src/jobs/reconciliation/index.js
  backend/src/jobs/reconciliation/tasks/reconcile.js
  backend/src/jobs/reconciliation/tasks/utils/createReporter.js
Labels: ready

#726 wording email object + darker gray for mail templates
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#728 email martinique
  backend/config/regions.json
Labels: master, ready

#727 change smtp FROM address
  backend/config/default.json
  backend/src/smtp/mailer.js
Labels: ready

#731 wording in organisation mail
  backend/package-lock.json
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisation_password.txt
Labels: ready

#732 Fix datalake tests with file watcher
  backend/test/integration/http/routes/api/v1/datalake-exporter-test.js
Labels: ready

#729 Add fulltext search in moderation
  backend/src/http/routes/api/backoffice/moderateur/moderateur-routes.js
  backend/src/http/server.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/test/helpers/test-database.js
  backend/test/integration/http/routes/api/backoffice/moderateur-routes-test.js
  backoffice/src/components/backoffice/moderateur/moderation/AvisStagiairesPanel.jsx
Labels: ready

#735 job that reset email sent status for stagiaires/organismes
  backend/src/jobs/mailing/reset/index.js
Labels: ready

#730 Add tests against stream-utils
  backend/test/unit/utils/stream-utils-test.js
Labels: ready

#719 carousel to show emails models
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/common/Header.scss
  backoffice/src/components/backoffice/common/slide/Arrow.scss
  backoffice/src/components/backoffice/common/slide/CarouselIndicator.jsx
  backoffice/src/components/backoffice/common/slide/CarouselIndicator.scss
  backoffice/src/components/backoffice/common/slide/CarouselSlide.jsx
  backoffice/src/components/backoffice/common/slide/CarouselSlide.scss
  backoffice/src/components/backoffice/common/slide/LeftArrow.jsx
  backoffice/src/components/backoffice/common/slide/RightArrow.jsx
  backoffice/src/components/backoffice/common/slide/images/organismes_accès_compte.PNG
  backoffice/src/components/backoffice/common/slide/images/organismes_notifications_avis_non_lus.png
  backoffice/src/components/backoffice/common/slide/images/organismes_renouvellement_mdp.PNG
  backoffice/src/components/backoffice/common/slide/images/organismes_réponse_rejetée.PNG
  backoffice/src/components/backoffice/common/slide/images/stagiaire_avis_formation.PNG
  backoffice/src/components/backoffice/common/slide/images/stagiaire_commentaire_rejeté.PNG
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
  backoffice/src/components/backoffice/moderateur/moderation/TemplateCourrielsPanel.scss
  backoffice/src/components/backoffice/moderateur/moderation/TemplatesCourrielsPanel.jsx
Labels: ready

#734 update archived collections with an archived flag & migrate them
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/migrateArchivedCollections.js
Labels: ready

#733 add archived flag to old avis
  backend/src/jobs/archive/archive.js
  backend/src/jobs/archive/index.js
Labels: ready

#737 Email : change logo size + header size
  backend/src/http/public/static/images/email/01.jpg
  backend/src/http/public/static/images/email/02.jpg
  backend/src/http/public/static/images/email/03.jpg
  backend/src/http/public/static/images/email/logo_Anotea_Horizontal_baseline2.png
  backend/src/http/public/static/images/email/logo_Anotea_Vertical_baseline.png
  backend/src/http/public/static/images/email/logo_Anotea_Vertical_baseline2.png
  backend/src/http/public/static/images/email/white-star-icon.png
  backend/src/http/public/static/images/regions/logo-email/logo_10.png
  backend/src/http/public/static/images/regions/logo-email/logo_11.png
  backend/src/http/public/static/images/regions/logo-email/logo_12.png
  backend/src/http/public/static/images/regions/logo-email/logo_13.png
  backend/src/http/public/static/images/regions/logo-email/logo_14.png
  backend/src/http/public/static/images/regions/logo-email/logo_15.png
  backend/src/http/public/static/images/regions/logo-email/logo_16.png
  backend/src/http/public/static/images/regions/logo-email/logo_17.png
  backend/src/http/public/static/images/regions/logo-email/logo_18.png
  backend/src/http/public/static/images/regions/logo-email/logo_2.png
  backend/src/http/public/static/images/regions/logo-email/logo_3.png
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/src/http/public/static/images/regions/logo-email/logo_5.png
  backend/src/http/public/static/images/regions/logo-email/logo_6.png
  backend/src/http/public/static/images/regions/logo-email/logo_7.png
  backend/src/http/public/static/images/regions/logo-email/logo_8.png
  backend/src/http/public/static/images/regions/logo-email/logo_9.png
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/votre_avis.ejs
Labels: ready

#740 Use npm parallel-tranform instead of forked version
  backend/package-lock.json
  backend/package.json
  backend/src/common/utils/parallelTransform.js
  backend/src/common/utils/stream-utils.js
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backend/src/http/routes/api/backoffice/moderateur/gestion-organismes-routes.js
  backend/src/http/routes/routes-utils.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/src/jobs/job-utils.js
  backend/src/jobs/organismes/tasks/kairos/getOrganismesFromKairosCSV.js
  backend/src/jobs/organismes/tasks/synchronizeAccountsWithKairos.js
  backend/src/jobs/patch/stagiaires/tasks/patchCertifInfos.js
  backend/test/integration/jobs/organismes/synchronizeAccountsWithKairos-test.js
  backend/test/unit/utils/stream-utils-test.js
Labels: ready

#742 Fix reconciliation tests
  backend/test/integration/http/routes/api/v1/actions-routes-test.js
  backend/test/integration/http/routes/api/v1/sessions-routes-test.js
Labels: ready

#744 Revert "change smtp FROM address"
  backend/config/default.json
  backend/src/smtp/mailer.js
Labels: ready

#743 Add task to refresh data from datalake
  backend/src/jobs/patch/stagiaires/index.js
  backend/src/jobs/patch/stagiaires/tasks/refreshDataFromDatalake.js
Labels: ready

#747 update images & fix arrows position
  backoffice/src/components/backoffice/common/slide/images/OF_JoinAnotéa.png
  backoffice/src/components/backoffice/common/slide/images/OF_NewMDP.png
  backoffice/src/components/backoffice/common/slide/images/OF_NonLus.png
  backoffice/src/components/backoffice/common/slide/images/OF_ReponseRejeté.png
  backoffice/src/components/backoffice/common/slide/images/Stag_6mois.png
  backoffice/src/components/backoffice/common/slide/images/Stag_AvisRejeté.png
  backoffice/src/components/backoffice/common/slide/images/Stag_DonnerVotreAvis.png
  backoffice/src/components/backoffice/common/slide/images/organismes_accès_compte.PNG
  backoffice/src/components/backoffice/common/slide/images/organismes_notifications_avis_non_lus.png
  backoffice/src/components/backoffice/common/slide/images/organismes_renouvellement_mdp.PNG
  backoffice/src/components/backoffice/common/slide/images/organismes_réponse_rejetée.PNG
  backoffice/src/components/backoffice/common/slide/images/stagiaire_avis_formation.PNG
  backoffice/src/components/backoffice/common/slide/images/stagiaire_commentaire_rejeté.PNG
  backoffice/src/components/backoffice/moderateur/ModerateurRoutes.jsx
Labels: ready

#746 replace . with , to enable math operations in excel
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
Labels: ready

#741 creates a new doc if no doublon
  backend/src/jobs/archive/archive.js
  backend/src/jobs/archive/index.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropArchivedCollections.js
  backend/src/jobs/data/migration/tasks/migrateArchivedCollections.js
  backend/src/jobs/data/migration/tasks/removeInvalidComment.js
Labels: ready

#748 Replace NULL value with '' in datalake file
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/test/helpers/data/stagiaires-pe-with-NULL.csv
  backend/test/integration/jobs/import/stagiaires/importTrainee-test.js
Labels: ready

#745 Rename convertIntoCSV util into transformObjectIntoCSV
  backend/src/common/utils/stream-utils.js
  backend/src/http/routes/routes-utils.js
  backend/src/jobs/export/exportDQSCSV.js
  backend/src/jobs/export/exportOrganismesCSV.js
  backend/src/jobs/export/exportReconciliationCSV.js
Labels: ready

#739 Change script to init all avis to archived = false
  backend/src/http/routes/api/backoffice/moderateur/moderateur-routes.js
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
  backend/src/http/routes/api/questionnaire/questionnaire-routes.js
  backend/src/http/routes/api/v1/avis-routes.js
  backend/src/http/routes/api/v1/organismes-formateurs-routes.js
  backend/src/jobs/archive/archive.js
  backend/src/jobs/archive/index.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/initArchivedField.js
  backend/src/jobs/data/migration/tasks/removeInvalidComment.js
  backend/src/jobs/reconciliation/tasks/reconcile/findAvisReconciliables.js
  backend/test/helpers/data/dataset.js
  backend/test/integration/http/routes/api/backoffice/moderateur-routes-test.js
  backend/test/integration/http/routes/api/questionnaire-routes-test.js
  backend/test/integration/http/routes/api/v1/avis-routes-test.js
  backend/test/integration/http/routes/api/v1/organismes-formateurs-routes-test.js
  backend/test/integration/jobs/reconciliation/reconcileActions-test.js
  backend/test/integration/jobs/reconciliation/reconcileFormation-test.js
  backend/test/integration/jobs/reconciliation/reconcileSessions-test.js
Labels: ready

#752 Remove deprecated stats from jobs and BO Financeur
  backend/src/jobs/stats/emails/domainMailStatsBuilder.js
  backend/src/jobs/stats/emails/emailStatsBuilder.js
  backend/src/jobs/stats/emails/index.js
  backend/src/jobs/stats/index.js
  backend/src/jobs/stats/organisations/datafix.js
  backend/src/jobs/stats/organisations/index.js
  backend/src/jobs/stats/organisations/organisationStatsBuilder.js
  backend/src/jobs/stats/sessions/index.js
  backend/src/jobs/stats/sessions/sessionStatsBuilder.js
  backend/src/jobs/stats/tasks/computeApiStats.js
  backend/src/jobs/stats/tasks/computeAvisStats.js
  backend/src/jobs/stats/tasks/computeCampaignStats.js
  backend/src/jobs/stats/tasks/computeOrganismesStats.js
  backoffice/src/components/backoffice/financeur/FinancerPanel.jsx
  backoffice/src/components/backoffice/financeur/SideMenu.js
  backoffice/src/components/backoffice/financeur/stats/Dashboard.js
  backoffice/src/components/backoffice/financeur/stats/Graph.js
  backoffice/src/components/backoffice/financeur/stats/Table.js
  backoffice/src/components/backoffice/financeur/stats/dashboard.css
  backoffice/src/components/backoffice/financeur/stats/table.css
Labels: ready

#751 Fix reset password script
  backend/src/jobs/data/reset/emails/index.js
  backend/src/jobs/data/reset/index.js
  backend/src/jobs/data/reset/passwords/index.js
  backend/src/jobs/data/reset/tasks/resetEmails.js
  backend/src/jobs/data/reset/tasks/resetPasswords.js
Labels: ready

#750 Revert all emails stuff
  backend/src/components.js
  backend/src/http/public/static/images/email/01.jpg
  backend/src/http/public/static/images/email/02.jpg
  backend/src/http/public/static/images/email/03.jpg
  backend/src/http/public/static/images/email/logo_Anotea_Horizontal_baseline2.png
  backend/src/http/public/static/images/email/logo_Anotea_Vertical_baseline.png
  backend/src/http/public/static/images/email/logo_Anotea_Vertical_baseline2.png
  backend/src/http/public/static/images/email/white-star-icon.png
  backend/src/http/public/static/images/regions/logo-email/logo_10.png
  backend/src/http/public/static/images/regions/logo-email/logo_11.png
  backend/src/http/public/static/images/regions/logo-email/logo_12.png
  backend/src/http/public/static/images/regions/logo-email/logo_13.png
  backend/src/http/public/static/images/regions/logo-email/logo_14.png
  backend/src/http/public/static/images/regions/logo-email/logo_15.png
  backend/src/http/public/static/images/regions/logo-email/logo_16.png
  backend/src/http/public/static/images/regions/logo-email/logo_17.png
  backend/src/http/public/static/images/regions/logo-email/logo_18.png
  backend/src/http/public/static/images/regions/logo-email/logo_2.png
  backend/src/http/public/static/images/regions/logo-email/logo_3.png
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/src/http/public/static/images/regions/logo-email/logo_5.png
  backend/src/http/public/static/images/regions/logo-email/logo_6.png
  backend/src/http/public/static/images/regions/logo-email/logo_7.png
  backend/src/http/public/static/images/regions/logo-email/logo_8.png
  backend/src/http/public/static/images/regions/logo-email/logo_9.png
  backend/src/http/routes/api/backoffice/moderateur/moderateur-routes.js
  backend/src/jobs/mailing/stagiaires/avis/AvisMailer.js
  backend/src/jobs/mailing/stagiaires/avis/actions/ResendAction.js
  backend/src/jobs/mailing/stagiaires/avis/actions/RetryAction.js
  backend/src/jobs/mailing/stagiaires/avis/actions/SendAction.js
  backend/src/jobs/mailing/stagiaires/avis/index.js
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/index.js
  backend/src/jobs/mailing/stagiaires/questionnaire6mois/tasks/Questionnaire6MoisMailer.js
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/avis_injure.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisation_password.txt
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_avis_non_lus.txt
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/password_forgotten.txt
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/questionnaire_6mois.txt
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
  backend/test/helpers/data/dataset.js
  backend/test/integration/jobs/mailing/fake-mailers.js
  backend/test/integration/jobs/mailing/stagiaires/avis/AvisMailer-test.js
  backend/test/integration/jobs/mailing/stagiaires/avis/actions/ResendAction-test.js
  backend/test/integration/jobs/mailing/stagiaires/avis/actions/RetryAction-test.js
  backend/test/integration/jobs/mailing/stagiaires/avis/actions/SendAction-test.js
  backend/test/integration/jobs/mailing/stagiaires/questionnaire6mois/Questionnaire6MoisMailer-test.js
Labels: ready

#755 Fix dataset builder
  backend/src/http/routes/api/backoffice/moderateur/moderateur-routes.js
  backend/src/http/routes/api/backoffice/moderateur/stats.js
  backend/src/http/routes/api/backoffice/moderateur/utils/computeModerationStats.js
  backend/src/http/routes/api/backoffice/moderateur/utils/moderationStats.js
  backend/src/http/server.js
  backend/src/jobs/data/dataset/index.js
  backend/src/jobs/data/dataset/tasks/createAvis.js
  backend/src/jobs/data/reset/tasks/resetPasswords.js
  backoffice/src/components/backoffice/common/Header.jsx
  backoffice/src/components/backoffice/moderateur/moderation/moderationService.js
Labels: ready

#758 Update README
  README.md
Labels: master, ready

#759 Remove deprecated stats (routes and collections)
  backend/src/http/routes/api/backoffice/stats-routes.js
  backend/src/http/server.js
  backend/src/jobs/data/indexes/tasks/mongoIndexes.js
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropArchivedCollections.js
  backend/src/jobs/data/migration/tasks/initArchivedField.js
  backend/src/jobs/data/migration/tasks/migrateArchivedCollections.js
  backoffice/src/lib/mailStatsService.js
Labels: master, ready

#760 Fix stats import
  backend/src/jobs/stats/index.js
Labels: master, ready

#761 Fix invalid archived flag and prevent error
  backend/src/http/routes/api/backoffice/organismes/organisme-routes.js
Labels: master, ready

#757 update columns of excel export
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
Labels: ready

#766 Update questionnaire 6 mois wording
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/questionnaire_6mois.txt
Labels: ready

#765 Prevent stagiaires script to fail on each datalake file error
  backend/src/jobs/import/stagiaires/tasks/importTrainee.js
  backend/test/integration/jobs/import/stagiaires/poleEmploiCSVHandler-test.js
Labels: ready

#764 Allow patch script to be launched without certifInfos
  backend/src/jobs/patch/stagiaires/index.js
  backend/src/jobs/patch/stagiaires/tasks/refreshCertifInfos.js
  backend/test/integration/jobs/refresh/refreshCertifInfos-test.js
Labels: ready

#767 Add migration script to fix avisCreated flag
  backend/src/jobs/data/migration/index.js
  backend/src/jobs/data/migration/tasks/dropArchivedCollections.js
  backend/src/jobs/data/migration/tasks/fixAvisCreated.js
  backend/src/jobs/data/migration/tasks/markOrphanComments.js
Labels: master, ready

#768 Search avis by email OR fulltext
  backend/package.json
  backend/src/http/routes/api/backoffice/moderateur/moderateur-routes.js
Labels: bug, master, ready

#769 Update Slack notification when emails are sent
  backend/src/jobs/mailing/stagiaires/avis/index.js
Labels: master, ready

#771 Opt-out stagiaire
  backend/src/jobs/data/optOut/index.js
  backend/src/jobs/data/optOut/tasks/optOutStagiaire.js
  backend/src/jobs/import/stagiaires/tasks/handlers/poleEmploiCSVHandler.js
  backend/test/integration/jobs/data/optOut/optOutStagiaire-test.js
  backend/test/integration/jobs/import/rome/romeImporter-test.js
  backend/test/integration/jobs/import/stagiaires/poleEmploiCSVHandler-test.js
Labels: master, ready

#772 Move mailjet spike into a dedicated folder
  backend/test/spikes/mailjet/index.js
  backend/test/spikes/mailjet/mailjet.js
Labels: ready

#773 mentions légales pour tout les emails
  README.md
  backend/src/common/components/mailing/sendForgottenPasswordEmail.js
  backend/src/http/views/front/faq.ejs
  backend/src/smtp/mailer.js
  backend/src/smtp/views/avis_injure.ejs
  backend/src/smtp/views/avis_injure.txt
  backend/src/smtp/views/legal/financeurs/mentions.ejs
  backend/src/smtp/views/legal/financeurs/mentions.txt
  backend/src/smtp/views/legal/organismes/mentions.ejs
  backend/src/smtp/views/legal/organismes/mentions.txt
  backend/src/smtp/views/legal/stagiaires/mentions.ejs
  backend/src/smtp/views/legal/stagiaires/mentions.txt
  backend/src/smtp/views/organisation_password.ejs
  backend/src/smtp/views/organisation_password.txt
  backend/src/smtp/views/organisme_avis_non_lus.ejs
  backend/src/smtp/views/organisme_avis_non_lus.txt
  backend/src/smtp/views/organisme_reponse_rejetee.ejs
  backend/src/smtp/views/organisme_reponse_rejetee.txt
  backend/src/smtp/views/password_forgotten.ejs
  backend/src/smtp/views/password_forgotten.txt
  backend/src/smtp/views/questionnaire_6mois.ejs
  backend/src/smtp/views/questionnaire_6mois.txt
  backend/src/smtp/views/votre_avis.ejs
  backend/src/smtp/views/votre_avis.txt
  backoffice/src/components/backoffice/moderateur/gestion/organismes/components/Edition.jsx
  backoffice/src/components/backoffice/moderateur/moderation/components/avis/buttons/RejectButton.jsx
  backoffice/src/components/backoffice/organisation/AccountActivation.jsx
  backoffice/src/components/login/ForgottenPassword.jsx
  misc/doc/diagram/anotea-diagram.svg
  widget/src/components/common/ContactStagiaire.jsx
Labels: ready

#774 Change datalake export file pattern
  backend/src/http/middlewares/utils/createDatalakeExporter.js
Labels: master, ready

#777 update logo
  backend/src/http/public/static/images/regions/logo-email/logo_10.png
  backend/src/http/public/static/images/regions/logo-email/logo_11.png
  backend/src/http/public/static/images/regions/logo-email/logo_12.png
  backend/src/http/public/static/images/regions/logo-email/logo_13.png
  backend/src/http/public/static/images/regions/logo-email/logo_14.png
  backend/src/http/public/static/images/regions/logo-email/logo_15.png
  backend/src/http/public/static/images/regions/logo-email/logo_16.png
  backend/src/http/public/static/images/regions/logo-email/logo_17.png
  backend/src/http/public/static/images/regions/logo-email/logo_18.png
  backend/src/http/public/static/images/regions/logo-email/logo_2.png
  backend/src/http/public/static/images/regions/logo-email/logo_3.png
  backend/src/http/public/static/images/regions/logo-email/logo_4.png
  backend/src/http/public/static/images/regions/logo-email/logo_5.png
  backend/src/http/public/static/images/regions/logo-email/logo_6.png
  backend/src/http/public/static/images/regions/logo-email/logo_7.png
  backend/src/http/public/static/images/regions/logo-email/logo_8.png
  backend/src/http/public/static/images/regions/logo-email/logo_9.png
Labels: ready

#775 Fix nbReponses in organismes stats
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backend/src/jobs/stats/tasks/computeOrganismesStats.js
  stats/src/components/stats/ApiStatsTable.jsx
  stats/src/components/stats/AvisStatsTable.jsx
  stats/src/components/stats/OrganismesStatsTable.jsx
Labels: master, ready

#776 Fix reponse column in OF export
  backend/src/common/utils/getReponseStatus.js
  backend/src/http/routes/api/backoffice/financeur/financeur-routes.js
  backoffice/src/components/backoffice/common/utils/getReponseStatus.js
Labels: master, ready
